// ========== Alphabet / Character Learning Data ==========
// Character sets for zero-foundation learners: Hiragana, Katakana, Hangul, Cyrillic, Arabic
// Each entry: { char, romanization, type, example }

const ALPHABET_DATA = {
  ja: {
    name: '日语',
    nameEn: 'Japanese',
    flag: '🇯🇵',
    groups: [
      {
        id: 'hiragana',
        name: '平假名',
        description: '日语最基础的表音文字，用于日常书写和语法助词',
        characters: [
          { char: 'あ', romanization: 'a', type: '元音', example: 'あさ (asa) 早晨' },
          { char: 'い', romanization: 'i', type: '元音', example: 'いえ (ie) 家' },
          { char: 'う', romanization: 'u', type: '元音', example: 'うえ (ue) 上面' },
          { char: 'え', romanization: 'e', type: '元音', example: 'えき (eki) 车站' },
          { char: 'お', romanization: 'o', type: '元音', example: 'おかね (okane) 钱' },
          { char: 'か', romanization: 'ka', type: '清音', example: 'かさ (kasa) 伞' },
          { char: 'き', romanization: 'ki', type: '清音', example: 'きた (kita) 北' },
          { char: 'く', romanization: 'ku', type: '清音', example: 'くに (kuni) 国家' },
          { char: 'け', romanization: 'ke', type: '清音', example: 'けさ (kesa) 今天早上' },
          { char: 'こ', romanization: 'ko', type: '清音', example: 'こえ (koe) 声音' },
          { char: 'さ', romanization: 'sa', type: '清音', example: 'さかな (sakana) 鱼' },
          { char: 'し', romanization: 'shi', type: '清音', example: 'しろ (shiro) 白色' },
          { char: 'す', romanization: 'su', type: '清音', example: 'すし (sushi) 寿司' },
          { char: 'せ', romanization: 'se', type: '清音', example: 'せんせい (sensei) 老师' },
          { char: 'そ', romanization: 'so', type: '清音', example: 'そと (soto) 外面' },
          { char: 'た', romanization: 'ta', type: '清音', example: 'たべる (taberu) 吃' },
          { char: 'ち', romanization: 'chi', type: '清音', example: 'ちいさい (chiisai) 小' },
          { char: 'つ', romanization: 'tsu', type: '清音', example: 'つくえ (tsukue) 桌子' },
          { char: 'て', romanization: 'te', type: '清音', example: 'て (te) 手' },
          { char: 'と', romanization: 'to', type: '清音', example: 'とけい (tokei) 钟表' },
          { char: 'な', romanization: 'na', type: '清音', example: 'なか (naka) 里面' },
          { char: 'に', romanization: 'ni', type: '清音', example: 'にほん (nihon) 日本' },
          { char: 'ぬ', romanization: 'nu', type: '清音', example: 'ぬの (nuno) 布' },
          { char: 'ね', romanization: 'ne', type: '清音', example: 'ねこ (neko) 猫' },
          { char: 'の', romanization: 'no', type: '清音', example: 'のみもの (nomimono) 饮料' },
          { char: 'は', romanization: 'ha', type: '清音', example: 'はな (hana) 花' },
          { char: 'ひ', romanization: 'hi', type: '清音', example: 'ひと (hito) 人' },
          { char: 'ふ', romanization: 'fu', type: '清音', example: 'ふゆ (fuyu) 冬天' },
          { char: 'へ', romanization: 'he', type: '清音', example: 'へや (heya) 房间' },
          { char: 'ほ', romanization: 'ho', type: '清音', example: 'ほん (hon) 书' },
          { char: 'ま', romanization: 'ma', type: '清音', example: 'まど (mado) 窗户' },
          { char: 'み', romanization: 'mi', type: '清音', example: 'みず (mizu) 水' },
          { char: 'む', romanization: 'mu', type: '清音', example: 'むし (mushi) 虫' },
          { char: 'め', romanization: 'me', type: '清音', example: 'め (me) 眼睛' },
          { char: 'も', romanization: 'mo', type: '清音', example: 'もも (momo) 桃子' },
          { char: 'や', romanization: 'ya', type: '清音', example: 'やま (yama) 山' },
          { char: 'ゆ', romanization: 'yu', type: '清音', example: 'ゆき (yuki) 雪' },
          { char: 'よ', romanization: 'yo', type: '清音', example: 'よる (yoru) 夜晚' },
          { char: 'ら', romanization: 'ra', type: '清音', example: 'らいねん (rainen) 明年' },
          { char: 'り', romanization: 'ri', type: '清音', example: 'りんご (ringo) 苹果' },
          { char: 'る', romanization: 'ru', type: '清音', example: 'るす (rusu) 不在家' },
          { char: 'れ', romanization: 're', type: '清音', example: 'れきし (rekishi) 历史' },
          { char: 'ろ', romanization: 'ro', type: '清音', example: 'ろく (roku) 六' },
          { char: 'わ', romanization: 'wa', type: '清音', example: 'わたし (watashi) 我' },
          { char: 'を', romanization: 'wo', type: '清音', example: 'を - 宾格助词' },
          { char: 'ん', romanization: 'n', type: '拨音', example: 'ほん (hon) 书' },
        ],
      },
      {
        id: 'katakana',
        name: '片假名',
        description: '用于外来语、拟声词和强调',
        characters: [
          { char: 'ア', romanization: 'a', type: '元音', example: 'アメリカ (amerika) 美国' },
          { char: 'イ', romanization: 'i', type: '元音', example: 'イギリス (igirisu) 英国' },
          { char: 'ウ', romanization: 'u', type: '元音', example: 'ウイスキー (uisukii) 威士忌' },
          { char: 'エ', romanization: 'e', type: '元音', example: 'エレベーター (erebeetaa) 电梯' },
          { char: 'オ', romanization: 'o', type: '元音', example: 'オペラ (opera) 歌剧' },
          { char: 'カ', romanization: 'ka', type: '清音', example: 'カメラ (kamera) 相机' },
          { char: 'キ', romanization: 'ki', type: '清音', example: 'キーボード (kiiboodo) 键盘' },
          { char: 'ク', romanization: 'ku', type: '清音', example: 'クラス (kurasu) 班级' },
          { char: 'ケ', romanization: 'ke', type: '清音', example: 'ケーキ (keeki) 蛋糕' },
          { char: 'コ', romanization: 'ko', type: '清音', example: 'コーヒー (koohii) 咖啡' },
          { char: 'サ', romanization: 'sa', type: '清音', example: 'サラダ (sarada) 沙拉' },
          { char: 'シ', romanization: 'shi', type: '清音', example: 'シャツ (shatsu) 衬衫' },
          { char: 'ス', romanization: 'su', type: '清音', example: 'スポーツ (supootsu) 运动' },
          { char: 'セ', romanization: 'se', type: '清音', example: 'セーター (seetaa) 毛衣' },
          { char: 'ソ', romanization: 'so', type: '清音', example: 'ソファ (sofa) 沙发' },
          { char: 'タ', romanization: 'ta', type: '清音', example: 'タクシー (takushii) 出租车' },
          { char: 'チ', romanization: 'chi', type: '清音', example: 'チケット (chiketto) 票' },
          { char: 'ツ', romanization: 'tsu', type: '清音', example: 'ツール (tsuuru) 工具' },
          { char: 'テ', romanization: 'te', type: '清音', example: 'テレビ (terebi) 电视' },
          { char: 'ト', romanization: 'to', type: '清音', example: 'トマト (tomato) 番茄' },
          { char: 'ナ', romanization: 'na', type: '清音', example: 'ナイフ (naifu) 刀' },
          { char: 'ニ', romanization: 'ni', type: '清音', example: 'ニュース (nyuusu) 新闻' },
          { char: 'ヌ', romanization: 'nu', type: '清音', example: 'ヌードル (nuudoru) 面条' },
          { char: 'ネ', romanization: 'ne', type: '清音', example: 'ネクタイ (nekutai) 领带' },
          { char: 'ノ', romanization: 'no', type: '清音', example: 'ノート (nooto) 笔记本' },
          { char: 'ハ', romanization: 'ha', type: '清音', example: 'ハンバーガー (hanbaagaa) 汉堡' },
          { char: 'ヒ', romanization: 'hi', type: '清音', example: 'ヒーター (hiitaa) 暖气' },
          { char: 'フ', romanization: 'fu', type: '清音', example: 'フィルム (firumu) 胶卷' },
          { char: 'ヘ', romanization: 'he', type: '清音', example: 'ヘッド (heddo) 头部' },
          { char: 'ホ', romanization: 'ho', type: '清音', example: 'ホテル (hoteru) 酒店' },
          { char: 'マ', romanization: 'ma', type: '清音', example: 'マスク (masuku) 口罩' },
          { char: 'ミ', romanization: 'mi', type: '清音', example: 'ミルク (miruku) 牛奶' },
          { char: 'ム', romanization: 'mu', type: '清音', example: 'ムービー (muubii) 电影' },
          { char: 'メ', romanization: 'me', type: '清音', example: 'メニュー (menyuu) 菜单' },
          { char: 'モ', romanization: 'mo', type: '清音', example: 'モデル (moderu) 模特' },
          { char: 'ヤ', romanization: 'ya', type: '清音', example: 'ヤクルト (yakuruto) 养乐多' },
          { char: 'ユ', romanization: 'yu', type: '清音', example: 'ユーモア (yumoa) 幽默' },
          { char: 'ヨ', romanization: 'yo', type: '清音', example: 'ヨーロッパ (yooroppa) 欧洲' },
          { char: 'ラ', romanization: 'ra', type: '清音', example: 'ラジオ (rajio) 收音机' },
          { char: 'リ', romanization: 'ri', type: '清音', example: 'リスト (risuto) 清单' },
          { char: 'ル', romanization: 'ru', type: '清音', example: 'ルール (ruuru) 规则' },
          { char: 'レ', romanization: 're', type: '清音', example: 'レストラン (resutoran) 餐厅' },
          { char: 'ロ', romanization: 'ro', type: '清音', example: 'ロボット (robotto) 机器人' },
          { char: 'ワ', romanization: 'wa', type: '清音', example: 'ワイン (wain) 葡萄酒' },
          { char: 'ヲ', romanization: 'wo', type: '清音', example: 'ヲ - 书面语助词' },
          { char: 'ン', romanization: 'n', type: '拨音', example: 'パン (pan) 面包' },
        ],
      },
    ],
  },
  ko: {
    name: '韩语',
    nameEn: 'Korean',
    flag: '🇰🇷',
    groups: [
      {
        id: 'consonants',
        name: '辅音',
        description: '韩语辅音共14个基本字母',
        characters: [
          { char: 'ㄱ', romanization: 'g / k', type: '松音', example: '가수 (gasu) 歌手' },
          { char: 'ㄴ', romanization: 'n', type: '鼻音', example: '나라 (nara) 国家' },
          { char: 'ㄷ', romanization: 'd / t', type: '松音', example: '다리 (dari) 腿' },
          { char: 'ㄹ', romanization: 'r / l', type: '闪音', example: '라디오 (radio) 收音机' },
          { char: 'ㅁ', romanization: 'm', type: '鼻音', example: '마음 (maeum) 心' },
          { char: 'ㅂ', romanization: 'b / p', type: '松音', example: '바다 (bada) 大海' },
          { char: 'ㅅ', romanization: 's', type: '擦音', example: '사람 (saram) 人' },
          { char: 'ㅇ', romanization: 'ng / 无声', type: '鼻音/占位', example: '아이 (ai) 孩子' },
          { char: 'ㅈ', romanization: 'j', type: '塞擦音', example: '자동차 (jadongcha) 汽车' },
          { char: 'ㅊ', romanization: 'ch', type: '送气音', example: '차 (cha) 茶' },
          { char: 'ㅋ', romanization: 'k', type: '送气音', example: '커피 (keopi) 咖啡' },
          { char: 'ㅌ', romanization: 't', type: '送气音', example: '택시 (taeksi) 出租车' },
          { char: 'ㅍ', romanization: 'p', type: '送气音', example: '피자 (pija) 披萨' },
          { char: 'ㅎ', romanization: 'h', type: '擦音', example: '하늘 (haneul) 天空' },
        ],
      },
      {
        id: 'vowels',
        name: '元音',
        description: '韩语元音共10个基本字母',
        characters: [
          { char: 'ㅏ', romanization: 'a', type: '单元音', example: '아버지 (abeoji) 父亲' },
          { char: 'ㅑ', romanization: 'ya', type: '单元音', example: '야구 (yagu) 棒球' },
          { char: 'ㅓ', romanization: 'eo', type: '单元音', example: '어머니 (eomeoni) 母亲' },
          { char: 'ㅕ', romanization: 'yeo', type: '单元音', example: '여자 (yeoja) 女人' },
          { char: 'ㅗ', romanization: 'o', type: '单元音', example: '오늘 (oneul) 今天' },
          { char: 'ㅛ', romanization: 'yo', type: '单元音', example: '요리 (yori) 料理' },
          { char: 'ㅜ', romanization: 'u', type: '单元音', example: '우유 (uyu) 牛奶' },
          { char: 'ㅠ', romanization: 'yu', type: '单元音', example: '유리 (yuri) 玻璃' },
          { char: 'ㅡ', romanization: 'eu', type: '单元音', example: '으으 (eu) 呃' },
          { char: 'ㅣ', romanization: 'i', type: '单元音', example: '이 (i) 牙齿/二' },
        ],
      },
    ],
  },
  ru: {
    name: '俄语',
    nameEn: 'Russian',
    flag: '🇷🇺',
    groups: [
      {
        id: 'cyrillic',
        name: '西里尔字母',
        description: '俄语字母表，共33个字母，含元音、辅音及特殊符号',
        characters: [
          { char: 'А а', romanization: 'a', type: '元音', example: 'Анна (Anna) 安娜' },
          { char: 'Б б', romanization: 'b', type: '浊辅音', example: 'банк (bank) 银行' },
          { char: 'В в', romanization: 'v', type: '浊辅音', example: 'вода (voda) 水' },
          { char: 'Г г', romanization: 'g', type: '浊辅音', example: 'город (gorod) 城市' },
          { char: 'Д д', romanization: 'd', type: '浊辅音', example: 'дом (dom) 房子' },
          { char: 'Е е', romanization: 'ye / yo', type: '元音', example: 'Европа (Yevropa) 欧洲' },
          { char: 'Ё ё', romanization: 'yo', type: '元音', example: 'ёлка (yolka) 云杉' },
          { char: 'Ж ж', romanization: 'zh', type: '浊辅音', example: 'журнал (zhurnal) 杂志' },
          { char: 'З з', romanization: 'z', type: '浊辅音', example: 'зима (zima) 冬天' },
          { char: 'И и', romanization: 'i', type: '元音', example: 'Иван (Ivan) 伊万' },
          { char: 'Й й', romanization: 'y', type: '半元音', example: 'май (may) 五月' },
          { char: 'К к', romanization: 'k', type: '清辅音', example: 'кот (kot) 猫' },
          { char: 'Л л', romanization: 'l', type: '浊辅音', example: 'лес (les) 森林' },
          { char: 'М м', romanization: 'm', type: '浊辅音', example: 'мама (mama) 妈妈' },
          { char: 'Н н', romanization: 'n', type: '浊辅音', example: 'нет (nyet) 不' },
          { char: 'О о', romanization: 'o', type: '元音', example: 'окно (okno) 窗户' },
          { char: 'П п', romanization: 'p', type: '清辅音', example: 'папа (papa) 爸爸' },
          { char: 'Р р', romanization: 'r', type: '浊辅音', example: 'рука (ruka) 手' },
          { char: 'С с', romanization: 's', type: '清辅音', example: 'стол (stol) 桌子' },
          { char: 'Т т', romanization: 't', type: '清辅音', example: 'такси (taksi) 出租车' },
          { char: 'У у', romanization: 'u', type: '元音', example: 'улица (ulitsa) 街道' },
          { char: 'Ф ф', romanization: 'f', type: '清辅音', example: 'фото (foto) 照片' },
          { char: 'Х х', romanization: 'kh', type: '清辅音', example: 'хлеб (khlyeb) 面包' },
          { char: 'Ц ц', romanization: 'ts', type: '清辅音', example: 'цена (tsena) 价格' },
          { char: 'Ч ч', romanization: 'ch', type: '清辅音', example: 'чай (chay) 茶' },
          { char: 'Ш ш', romanization: 'sh', type: '清辅音', example: 'школа (shkola) 学校' },
          { char: 'Щ щ', romanization: 'shch', type: '清辅音', example: 'щука (shchuka) 梭鱼' },
          { char: 'Ъ ъ', romanization: '硬音符号', type: '符号', example: 'объект (obyekt) 对象' },
          { char: 'Ы ы', romanization: 'y', type: '元音', example: 'сын (syn) 儿子' },
          { char: 'Ь ь', romanization: '软音符号', type: '符号', example: 'мать (mat) 母亲' },
          { char: 'Э э', romanization: 'e', type: '元音', example: 'это (eto) 这' },
          { char: 'Ю ю', romanization: 'yu', type: '元音', example: 'юг (yug) 南方' },
          { char: 'Я я', romanization: 'ya', type: '元音', example: 'я (ya) 我' },
        ],
      },
    ],
  },
  ar: {
    name: '阿拉伯语',
    nameEn: 'Arabic',
    flag: '🇸🇦',
    groups: [
      {
        id: 'arabic',
        name: '阿拉伯字母',
        description: '阿拉伯字母共28个，从右向左书写，字母形态随位置变化',
        characters: [
          { char: 'ا', romanization: 'alif', type: '喉音/长元音', example: 'أب (ab) 父亲' },
          { char: 'ب', romanization: 'ba', type: '唇音', example: 'باب (bab) 门' },
          { char: 'ت', romanization: 'ta', type: '齿音', example: 'تمر (tamr) 枣' },
          { char: 'ث', romanization: 'tha', type: '齿间音', example: 'ثلاثة (thalatha) 三' },
          { char: 'ج', romanization: 'jim', type: '龈腭音', example: 'جمل (jamal) 骆驼' },
          { char: 'ح', romanization: 'ha', type: '喉擦音', example: 'حب (hubb) 爱' },
          { char: 'خ', romanization: 'kha', type: '软腭擦音', example: 'خبز (khubz) 面包' },
          { char: 'د', romanization: 'dal', type: '齿音', example: 'دار (dar) 房子' },
          { char: 'ذ', romanization: 'dhal', type: '齿间音', example: 'ذهب (dhahab) 金子' },
          { char: 'ر', romanization: 'ra', type: '齿龈闪音', example: 'رمل (raml) 沙子' },
          { char: 'ز', romanization: 'zay', type: '齿龈音', example: 'زرافة (zirafa) 长颈鹿' },
          { char: 'س', romanization: 'sin', type: '齿龈擦音', example: 'سمك (samak) 鱼' },
          { char: 'ش', romanization: 'shin', type: '龈腭擦音', example: 'شمس (shams) 太阳' },
          { char: 'ص', romanization: 'sad', type: '咽化擦音', example: 'صباح (sabah) 早晨' },
          { char: 'ض', romanization: 'dad', type: '咽化塞音', example: 'ضيف (dayf) 客人' },
          { char: 'ط', romanization: 'ta', type: '咽化塞音', example: 'طالب (talib) 学生' },
          { char: 'ظ', romanization: 'zha', type: '咽化擦音', example: 'ظل (zill) 影子' },
          { char: 'ع', romanization: 'ain', type: '喉塞音', example: 'عين (ayn) 眼睛' },
          { char: 'غ', romanization: 'ghain', type: '软腭擦音', example: 'غداء (ghada) 午餐' },
          { char: 'ف', romanization: 'fa', type: '唇齿音', example: 'فاكهة (fakiha) 水果' },
          { char: 'ق', romanization: 'qaf', type: '小舌塞音', example: 'قلب (qalb) 心' },
          { char: 'ك', romanization: 'kaf', type: '软腭音', example: 'كتاب (kitab) 书' },
          { char: 'ل', romanization: 'lam', type: '齿龈边音', example: 'ليمون (laymun) 柠檬' },
          { char: 'م', romanization: 'mim', type: '双唇鼻音', example: 'ماء (ma) 水' },
          { char: 'ن', romanization: 'nun', type: '齿龈鼻音', example: 'نار (nar) 火' },
          { char: 'ه', romanization: 'ha', type: '声门擦音', example: 'هاتف (hatif) 电话' },
          { char: 'و', romanization: 'waw', type: '半元音/长u', example: 'ورد (ward) 玫瑰' },
          { char: 'ي', romanization: 'ya', type: '半元音/长i', example: 'يد (yad) 手' },
        ],
      },
    ],
  },
};

// Flatten all characters into a single array per language for card navigation
const getFlattenedChars = (langCode) => {
  const lang = ALPHABET_DATA[langCode];
  if (!lang) return [];
  const flat = [];
  lang.groups.forEach((group) => {
    group.characters.forEach((char, idx) => {
      flat.push({
        ...char,
        groupId: group.id,
        groupName: group.name,
        langCode,
        langName: lang.name,
        langFlag: lang.flag,
        globalIndex: flat.length,
        groupIndex: idx,
      });
    });
  });
  return flat;
};

// Get total character count per language
const getAlphabetCount = (langCode) => {
  const lang = ALPHABET_DATA[langCode];
  if (!lang) return 0;
  return lang.groups.reduce((sum, g) => sum + g.characters.length, 0);
};

// Get supported alphabet languages
const ALPHABET_LANGUAGES = ['ja', 'ko', 'ru', 'ar'];

Object.assign(window, {
  ALPHABET_DATA,
  getFlattenedChars,
  getAlphabetCount,
  ALPHABET_LANGUAGES,
});
