// ========== Listening Practice Data ==========
// 24 languages × ≥16 questions each = ≥384 questions total
// Types: listen-meaning (hear word, pick meaning) + listen-word (hear word, pick spelling)
// All distractors are real vocabulary from the same language
// Scenes covered: daily / travel / basic business

const LISTENING_DATA = {
  en: {
    meaning: [
      {
        id: 'en-lm-01',
        audioText: 'Hello',
        question: '听到的词是什么意思？',
        options: ['谢谢', '对不起', '再见', '你好'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'en-lm-02',
        audioText: 'Apple',
        question: '听到的词是什么意思？',
        options: ['香蕉', '苹果', '橙子', '葡萄'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'en-lm-03',
        audioText: 'Water',
        question: '听到的词是什么意思？',
        options: ['水', '牛奶', '茶', '咖啡'],
        correctAnswer: '水',
        difficulty: 1,
      },
      {
        id: 'en-lm-04',
        audioText: 'Thank you',
        question: '听到的短语是什么意思？',
        options: ['请', '你好', '对不起', '谢谢'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'en-lm-05',
        audioText: 'Friend',
        question: '听到的词是什么意思？',
        options: ['老师', '家人', '朋友', '同事'],
        correctAnswer: '朋友',
        difficulty: 2,
      },
      {
        id: 'en-lm-06',
        audioText: 'Hotel',
        question: '听到的词是什么意思？',
        options: ['银行', '医院', '酒店', '学校'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'en-lm-07',
        audioText: 'How much is it',
        question: '听到的句子是什么意思？',
        options: ['这是什么', '几点了', '在哪里', '多少钱'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'en-lm-08',
        audioText: 'Meeting',
        question: '听到的词是什么意思？',
        options: ['会议', '聚会', '课程', '宴会'],
        correctAnswer: '会议',
        difficulty: 3,
      },
    ],
    word: [
      {
        id: 'en-lw-01',
        audioText: 'Hello',
        question: '听到的词是哪个？',
        options: ['Yellow', 'Hello', 'Hollow', 'Hallo'],
        correctAnswer: 'Hello',
        difficulty: 1,
      },
      {
        id: 'en-lw-02',
        audioText: 'Apple',
        question: '听到的词是哪个？',
        options: ['Ample', 'Apply', 'Apple', 'Appeal'],
        correctAnswer: 'Apple',
        difficulty: 1,
      },
      {
        id: 'en-lw-03',
        audioText: 'Water',
        question: '听到的词是哪个？',
        options: ['Water', 'Weather', 'Winter', 'Waiter'],
        correctAnswer: 'Water',
        difficulty: 2,
      },
      {
        id: 'en-lw-04',
        audioText: 'Friend',
        question: '听到的词是哪个？',
        options: ['Friend', 'Fried', 'Found', 'Fiend'],
        correctAnswer: 'Friend',
        difficulty: 2,
      },
      {
        id: 'en-lw-05',
        audioText: 'Beautiful',
        question: '听到的词是哪个？',
        options: ['Beautifully', 'Beauty', 'Beatiful', 'Beautiful'],
        correctAnswer: 'Beautiful',
        difficulty: 3,
      },
      {
        id: 'en-lw-06',
        audioText: 'Hospital',
        question: '听到的词是哪个？',
        options: ['History', 'Hostel', 'Hotel', 'Hospital'],
        correctAnswer: 'Hospital',
        difficulty: 2,
      },
      {
        id: 'en-lw-07',
        audioText: 'Reservation',
        question: '听到的词是哪个？',
        options: ['Conservation', 'Observation', 'Preservation', 'Reservation'],
        correctAnswer: 'Reservation',
        difficulty: 3,
      },
      {
        id: 'en-lw-08',
        audioText: 'Interview',
        question: '听到的词是哪个？',
        options: ['Overview', 'Review', 'Interview', 'Preview'],
        correctAnswer: 'Interview',
        difficulty: 3,
      },
    ],
  },
  ja: {
    meaning: [
      {
        id: 'ja-lm-01',
        audioText: 'こんにちは',
        question: '听到的词是什么意思？',
        options: ['谢谢', '对不起', '你好', '再见'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'ja-lm-02',
        audioText: 'ありがとう',
        question: '听到的词是什么意思？',
        options: ['再见', '谢谢', '对不起', '你好'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'ja-lm-03',
        audioText: 'さようなら',
        question: '听到的词是什么意思？',
        options: ['你好', '谢谢', '再见', '早上好'],
        correctAnswer: '再见',
        difficulty: 1,
      },
      {
        id: 'ja-lm-04',
        audioText: 'りんご',
        question: '听到的词是什么意思？',
        options: ['葡萄', '橙子', '苹果', '香蕉'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'ja-lm-05',
        audioText: 'おはよう',
        question: '听到的词是什么意思？',
        options: ['早上好', '你好', '晚上好', '再见'],
        correctAnswer: '早上好',
        difficulty: 2,
      },
      {
        id: 'ja-lm-06',
        audioText: 'ホテル',
        question: '听到的词是什么意思？',
        options: ['车站', '医院', '酒店', '机场'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'ja-lm-07',
        audioText: 'いくらですか',
        question: '听到的句子是什么意思？',
        options: ['多少钱', '几点了', '在哪里', '这是什么'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'ja-lm-08',
        audioText: '会議',
        question: '听到的词是什么意思？',
        options: ['宴会', '聚会', '课程', '会议'],
        correctAnswer: '会议',
        difficulty: 3,
      },
    ],
    word: [
      {
        id: 'ja-lw-01',
        audioText: 'こんにちは',
        question: '听到的词是哪个？',
        options: ['おはよう', 'こんばんは', 'さようなら', 'こんにちは'],
        correctAnswer: 'こんにちは',
        difficulty: 1,
      },
      {
        id: 'ja-lw-02',
        audioText: 'ありがとう',
        question: '听到的词是哪个？',
        options: ['すみません', 'ありがとう', 'お願い', 'どういたしまして'],
        correctAnswer: 'ありがとう',
        difficulty: 1,
      },
      {
        id: 'ja-lw-03',
        audioText: 'りんご',
        question: '听到的词是哪个？',
        options: ['みかん', 'ばなな', 'ぶどう', 'りんご'],
        correctAnswer: 'りんご',
        difficulty: 1,
      },
      {
        id: 'ja-lw-04',
        audioText: 'すみません',
        question: '听到的词是哪个？',
        options: ['こんにちは', 'おはよう', 'ありがとう', 'すみません'],
        correctAnswer: 'すみません',
        difficulty: 2,
      },
      {
        id: 'ja-lw-05',
        audioText: 'お名前は何ですか',
        question: '听到的句子是哪个？',
        options: ['お元気ですか', 'お名前は何ですか', 'どこですか', '何時ですか'],
        correctAnswer: 'お名前は何ですか',
        difficulty: 3,
      },
      {
        id: 'ja-lw-06',
        audioText: 'ホテル',
        question: '听到的词是哪个？',
        options: ['病院', '空港', '駅', 'ホテル'],
        correctAnswer: 'ホテル',
        difficulty: 2,
      },
      {
        id: 'ja-lw-07',
        audioText: '予約',
        question: '听到的词是哪个？',
        options: ['予想', '予言', '予約', '予防'],
        correctAnswer: '予約',
        difficulty: 2,
      },
      {
        id: 'ja-lw-08',
        audioText: '面接',
        question: '听到的词是哪个？',
        options: ['会議', '商談', '面談', '面接'],
        correctAnswer: '面接',
        difficulty: 3,
      },
    ],
  },
  ko: {
    meaning: [
      {
        id: 'ko-lm-01',
        audioText: '안녕하세요',
        question: '听到的词是什么意思？',
        options: ['你好', '再见', '谢谢', '对不起'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'ko-lm-02',
        audioText: '감사합니다',
        question: '听到的词是什么意思？',
        options: ['谢谢', '再见', '对不起', '你好'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'ko-lm-03',
        audioText: '미안합니다',
        question: '听到的词是什么意思？',
        options: ['再见', '对不起', '谢谢', '你好'],
        correctAnswer: '对不起',
        difficulty: 1,
      },
      {
        id: 'ko-lm-04',
        audioText: '사과',
        question: '听到的词是什么意思？',
        options: ['橙子', '葡萄', '苹果', '香蕉'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'ko-lm-05',
        audioText: '물',
        question: '听到的词是什么意思？',
        options: ['水', '咖啡', '牛奶', '茶'],
        correctAnswer: '水',
        difficulty: 1,
      },
      {
        id: 'ko-lm-06',
        audioText: '호텔',
        question: '听到的词是什么意思？',
        options: ['酒店', '银行', '医院', '学校'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'ko-lm-07',
        audioText: '얼마예요',
        question: '听到的句子是什么意思？',
        options: ['多少钱', '几点了', '在哪里', '这是什么'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'ko-lm-08',
        audioText: '회의',
        question: '听到的词是什么意思？',
        options: ['会议', '聚会', '宴会', '课程'],
        correctAnswer: '会议',
        difficulty: 3,
      },
    ],
    word: [
      {
        id: 'ko-lw-01',
        audioText: '안녕하세요',
        question: '听到的词是哪个？',
        options: ['미안합니다', '안녕하세요', '감사합니다', '잘 가요'],
        correctAnswer: '안녕하세요',
        difficulty: 1,
      },
      {
        id: 'ko-lw-02',
        audioText: '감사합니다',
        question: '听到的词是哪个？',
        options: ['사랑해요', '안녕하세요', '감사합니다', '미안합니다'],
        correctAnswer: '감사합니다',
        difficulty: 1,
      },
      {
        id: 'ko-lw-03',
        audioText: '사과',
        question: '听到的词是哪个？',
        options: ['포도', '사과', '오렌지', '바나나'],
        correctAnswer: '사과',
        difficulty: 1,
      },
      {
        id: 'ko-lw-04',
        audioText: '화장실',
        question: '听到的词是哪个？',
        options: ['식당', '학교', '병원', '화장실'],
        correctAnswer: '화장실',
        difficulty: 2,
      },
      {
        id: 'ko-lw-05',
        audioText: '맛있어요',
        question: '听到的词是哪个？',
        options: ['작아요', '맛있어요', '커요', '예뻐요'],
        correctAnswer: '맛있어요',
        difficulty: 3,
      },
      {
        id: 'ko-lw-06',
        audioText: '호텔',
        question: '听到的词是哪个？',
        options: ['학교', '병원', '호텔', '은행'],
        correctAnswer: '호텔',
        difficulty: 2,
      },
      {
        id: 'ko-lw-07',
        audioText: '예약',
        question: '听到的词是哪个？',
        options: ['예상', '예언', '예방', '예약'],
        correctAnswer: '예약',
        difficulty: 2,
      },
      {
        id: 'ko-lw-08',
        audioText: '면접',
        question: '听到的词是哪个？',
        options: ['상담', '면접', '회의', '면담'],
        correctAnswer: '면접',
        difficulty: 3,
      },
    ],
  },
  'zh-CN': {
    meaning: [
      {
        id: 'zh-CN-lm-01',
        audioText: '你好',
        question: '听到的词是什么意思？',
        options: ['再见', '对不起', '谢谢', '你好'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'zh-CN-lm-02',
        audioText: '谢谢',
        question: '听到的词是什么意思？',
        options: ['谢谢', '对不起', '你好', '再见'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'zh-CN-lm-03',
        audioText: '再见',
        question: '听到的词是什么意思？',
        options: ['再见', '你好', '谢谢', '早上好'],
        correctAnswer: '再见',
        difficulty: 1,
      },
      {
        id: 'zh-CN-lm-04',
        audioText: '苹果',
        question: '听到的词是什么意思？',
        options: ['橙子', '葡萄', '苹果', '香蕉'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'zh-CN-lm-05',
        audioText: '早上好',
        question: '听到的词是什么意思？',
        options: ['你好', '早上好', '再见', '晚上好'],
        correctAnswer: '早上好',
        difficulty: 1,
      },
      {
        id: 'zh-CN-lm-06',
        audioText: '酒店',
        question: '听到的词是什么意思？',
        options: ['酒店', '机场', '医院', '车站'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'zh-CN-lm-07',
        audioText: '多少钱',
        question: '听到的句子是什么意思？',
        options: ['多少钱', '几点了', '这是什么', '在哪里'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'zh-CN-lm-08',
        audioText: '会议',
        question: '听到的词是什么意思？',
        options: ['课程', '会议', '宴会', '聚会'],
        correctAnswer: '会议',
        difficulty: 2,
      },
    ],
    word: [
      {
        id: 'zh-CN-lw-01',
        audioText: '你好',
        question: '听到的词是哪个？',
        options: ['再见', '你好', '您好', '谢谢'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'zh-CN-lw-02',
        audioText: '谢谢',
        question: '听到的词是哪个？',
        options: ['谢谢', '感激', '感动', '感谢'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'zh-CN-lw-03',
        audioText: '苹果',
        question: '听到的词是哪个？',
        options: ['苹果', '葡萄', '橙子', '香蕉'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'zh-CN-lw-04',
        audioText: '早上好',
        question: '听到的词是哪个？',
        options: ['早上好', '下午好', '中午好', '晚上好'],
        correctAnswer: '早上好',
        difficulty: 1,
      },
      {
        id: 'zh-CN-lw-05',
        audioText: '酒店',
        question: '听到的词是哪个？',
        options: ['宾馆', '酒店', '旅馆', '饭店'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'zh-CN-lw-06',
        audioText: '火车站',
        question: '听到的词是哪个？',
        options: ['汽车站', '地铁站', '飞机场', '火车站'],
        correctAnswer: '火车站',
        difficulty: 2,
      },
      {
        id: 'zh-CN-lw-07',
        audioText: '会议室',
        question: '听到的词是哪个？',
        options: ['办公室', '会议室', '餐厅', '教室'],
        correctAnswer: '会议室',
        difficulty: 2,
      },
      {
        id: 'zh-CN-lw-08',
        audioText: '名片',
        question: '听到的词是哪个？',
        options: ['银行卡', '身份证', '名片', '会员卡'],
        correctAnswer: '名片',
        difficulty: 3,
      },
    ],
  },
  es: {
    meaning: [
      {
        id: 'es-lm-01',
        audioText: 'Hola',
        question: '听到的词是什么意思？',
        options: ['你好', '对不起', '谢谢', '再见'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'es-lm-02',
        audioText: 'Gracias',
        question: '听到的词是什么意思？',
        options: ['再见', '谢谢', '你好', '对不起'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'es-lm-03',
        audioText: 'Adiós',
        question: '听到的词是什么意思？',
        options: ['早上好', '你好', '再见', '谢谢'],
        correctAnswer: '再见',
        difficulty: 1,
      },
      {
        id: 'es-lm-04',
        audioText: 'Manzana',
        question: '听到的词是什么意思？',
        options: ['香蕉', '苹果', '橙子', '葡萄'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'es-lm-05',
        audioText: 'Buenos días',
        question: '听到的短语是什么意思？',
        options: ['早上好', '你好', '再见', '晚上好'],
        correctAnswer: '早上好',
        difficulty: 1,
      },
      {
        id: 'es-lm-06',
        audioText: 'Hotel',
        question: '听到的词是什么意思？',
        options: ['酒店', '医院', '车站', '机场'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'es-lm-07',
        audioText: '¿Cuánto cuesta?',
        question: '听到的句子是什么意思？',
        options: ['这是什么', '在哪里', '几点了', '多少钱'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'es-lm-08',
        audioText: 'Reunión',
        question: '听到的词是什么意思？',
        options: ['宴会', '会议', '聚会', '课程'],
        correctAnswer: '会议',
        difficulty: 3,
      },
    ],
    word: [
      {
        id: 'es-lw-01',
        audioText: 'Hola',
        question: '听到的词是哪个？',
        options: ['Ola', 'Hula', 'Hola', 'Hala'],
        correctAnswer: 'Hola',
        difficulty: 1,
      },
      {
        id: 'es-lw-02',
        audioText: 'Gracias',
        question: '听到的词是哪个？',
        options: ['Graciosa', 'Gracioso', 'Gracias', 'Gracia'],
        correctAnswer: 'Gracias',
        difficulty: 1,
      },
      {
        id: 'es-lw-03',
        audioText: 'Manzana',
        question: '听到的词是哪个？',
        options: ['Uva', 'Naranja', 'Manzana', 'Banana'],
        correctAnswer: 'Manzana',
        difficulty: 1,
      },
      {
        id: 'es-lw-04',
        audioText: 'Adiós',
        question: '听到的词是哪个？',
        options: ['Bueno', 'Adiós', 'Bien', 'Hola'],
        correctAnswer: 'Adiós',
        difficulty: 1,
      },
      {
        id: 'es-lw-05',
        audioText: 'Hotel',
        question: '听到的词是哪个？',
        options: ['Banco', 'Hospital', 'Hotel', 'Escuela'],
        correctAnswer: 'Hotel',
        difficulty: 2,
      },
      {
        id: 'es-lw-06',
        audioText: 'Aeropuerto',
        question: '听到的词是哪个？',
        options: ['Puerto', 'Puerta', 'Aeropuerto', 'Estación'],
        correctAnswer: 'Aeropuerto',
        difficulty: 2,
      },
      {
        id: 'es-lw-07',
        audioText: 'Reserva',
        question: '听到的词是哪个？',
        options: ['Observa', 'Conserva', 'Preserva', 'Reserva'],
        correctAnswer: 'Reserva',
        difficulty: 2,
      },
      {
        id: 'es-lw-08',
        audioText: 'Entrevista',
        question: '听到的词是哪个？',
        options: ['Entrevista', 'Encuesta', 'Entrada', 'Entrega'],
        correctAnswer: 'Entrevista',
        difficulty: 3,
      },
    ],
  },
  ru: {
    meaning: [
      {
        id: 'ru-lm-01',
        audioText: 'Привет',
        question: '听到的词是什么意思？',
        options: ['谢谢', '对不起', '再见', '你好'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'ru-lm-02',
        audioText: 'Спасибо',
        question: '听到的词是什么意思？',
        options: ['对不起', '谢谢', '再见', '你好'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'ru-lm-03',
        audioText: 'До свидания',
        question: '听到的短语是什么意思？',
        options: ['谢谢', '早上好', '再见', '你好'],
        correctAnswer: '再见',
        difficulty: 1,
      },
      {
        id: 'ru-lm-04',
        audioText: 'Яблоко',
        question: '听到的词是什么意思？',
        options: ['葡萄', '香蕉', '橙子', '苹果'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'ru-lm-05',
        audioText: 'Доброе утро',
        question: '听到的短语是什么意思？',
        options: ['晚上好', '再见', '你好', '早上好'],
        correctAnswer: '早上好',
        difficulty: 1,
      },
      {
        id: 'ru-lm-06',
        audioText: 'Отель',
        question: '听到的词是什么意思？',
        options: ['酒店', '车站', '机场', '医院'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'ru-lm-07',
        audioText: 'Сколько стоит?',
        question: '听到的句子是什么意思？',
        options: ['这是什么', '在哪里', '多少钱', '几点了'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'ru-lm-08',
        audioText: 'Совещание',
        question: '听到的词是什么意思？',
        options: ['会议', '聚会', '课程', '宴会'],
        correctAnswer: '会议',
        difficulty: 3,
      },
    ],
    word: [
      {
        id: 'ru-lw-01',
        audioText: 'Привет',
        question: '听到的词是哪个？',
        options: ['Приветик', 'Привет', 'Превет', 'Привед'],
        correctAnswer: 'Привет',
        difficulty: 1,
      },
      {
        id: 'ru-lw-02',
        audioText: 'Спасибо',
        question: '听到的词是哪个？',
        options: ['Спасти', 'Спаси', 'Спасибо', 'Спасение'],
        correctAnswer: 'Спасибо',
        difficulty: 1,
      },
      {
        id: 'ru-lw-03',
        audioText: 'Яблоко',
        question: '听到的词是哪个？',
        options: ['Яблоко', 'Апельсин', 'Банан', 'Виноград'],
        correctAnswer: 'Яблоко',
        difficulty: 1,
      },
      {
        id: 'ru-lw-04',
        audioText: 'До свидания',
        question: '听到的短语是哪个？',
        options: ['Добрый день', 'До свидания', 'Добрый вечер', 'До завтра'],
        correctAnswer: 'До свидания',
        difficulty: 1,
      },
      {
        id: 'ru-lw-05',
        audioText: 'Отель',
        question: '听到的词是哪个？',
        options: ['Отель', 'Гостиница', 'Школа', 'Больница'],
        correctAnswer: 'Отель',
        difficulty: 2,
      },
      {
        id: 'ru-lw-06',
        audioText: 'Аэропорт',
        question: '听到的词是哪个？',
        options: ['Вокзал', 'Аэропорт', 'Порт', 'Станция'],
        correctAnswer: 'Аэропорт',
        difficulty: 2,
      },
      {
        id: 'ru-lw-07',
        audioText: 'Бронирование',
        question: '听到的词是哪个？',
        options: ['Бронза', 'Брожение', 'Броня', 'Бронирование'],
        correctAnswer: 'Бронирование',
        difficulty: 2,
      },
      {
        id: 'ru-lw-08',
        audioText: 'Собеседование',
        question: '听到的词是哪个？',
        options: ['Собеседование', 'Совещание', 'Совет', 'Собрание'],
        correctAnswer: 'Собеседование',
        difficulty: 3,
      },
    ],
  },
  de: {
    meaning: [
      {
        id: 'de-lm-01',
        audioText: 'Hallo',
        question: '听到的词是什么意思？',
        options: ['对不起', '再见', '谢谢', '你好'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'de-lm-02',
        audioText: 'Danke',
        question: '听到的词是什么意思？',
        options: ['你好', '对不起', '再见', '谢谢'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'de-lm-03',
        audioText: 'Auf Wiedersehen',
        question: '听到的短语是什么意思？',
        options: ['早上好', '你好', '谢谢', '再见'],
        correctAnswer: '再见',
        difficulty: 1,
      },
      {
        id: 'de-lm-04',
        audioText: 'Apfel',
        question: '听到的词是什么意思？',
        options: ['橙子', '香蕉', '苹果', '葡萄'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'de-lm-05',
        audioText: 'Guten Morgen',
        question: '听到的短语是什么意思？',
        options: ['再见', '你好', '早上好', '晚上好'],
        correctAnswer: '早上好',
        difficulty: 1,
      },
      {
        id: 'de-lm-06',
        audioText: 'Hotel',
        question: '听到的词是什么意思？',
        options: ['车站', '医院', '酒店', '机场'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'de-lm-07',
        audioText: 'Wie viel kostet das?',
        question: '听到的句子是什么意思？',
        options: ['在哪里', '多少钱', '几点了', '这是什么'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'de-lm-08',
        audioText: 'Besprechung',
        question: '听到的词是什么意思？',
        options: ['聚会', '宴会', '会议', '课程'],
        correctAnswer: '会议',
        difficulty: 3,
      },
    ],
    word: [
      {
        id: 'de-lw-01',
        audioText: 'Hallo',
        question: '听到的词是哪个？',
        options: ['Hallo', 'Heil', 'Hall', 'Holla'],
        correctAnswer: 'Hallo',
        difficulty: 1,
      },
      {
        id: 'de-lw-02',
        audioText: 'Danke',
        question: '听到的词是哪个？',
        options: ['Dank', 'Danke', 'Denke', 'Dunkel'],
        correctAnswer: 'Danke',
        difficulty: 1,
      },
      {
        id: 'de-lw-03',
        audioText: 'Apfel',
        question: '听到的词是哪个？',
        options: ['Orange', 'Banane', 'Traube', 'Apfel'],
        correctAnswer: 'Apfel',
        difficulty: 1,
      },
      {
        id: 'de-lw-04',
        audioText: 'Auf Wiedersehen',
        question: '听到的短语是哪个？',
        options: ['Bis bald', 'Auf Wiedersehen', 'Guten Tag', 'Guten Morgen'],
        correctAnswer: 'Auf Wiedersehen',
        difficulty: 1,
      },
      {
        id: 'de-lw-05',
        audioText: 'Hotel',
        question: '听到的词是哪个？',
        options: ['Krankenhaus', 'Hotel', 'Bahnhof', 'Flughafen'],
        correctAnswer: 'Hotel',
        difficulty: 2,
      },
      {
        id: 'de-lw-06',
        audioText: 'Flughafen',
        question: '听到的词是哪个？',
        options: ['Bahnhof', 'Flughafen', 'Hafen', 'Markt'],
        correctAnswer: 'Flughafen',
        difficulty: 2,
      },
      {
        id: 'de-lw-07',
        audioText: 'Reservierung',
        question: '听到的词是哪个？',
        options: ['Konservierung', 'Beobachtung', 'Reservierung', 'Präsentation'],
        correctAnswer: 'Reservierung',
        difficulty: 2,
      },
      {
        id: 'de-lw-08',
        audioText: 'Vorstellungsgespräch',
        question: '听到的词是哪个？',
        options: ['Vorstellungsgespräch', 'Besprechung', 'Unterhaltung', 'Gespräch'],
        correctAnswer: 'Vorstellungsgespräch',
        difficulty: 3,
      },
    ],
  },
  fr: {
    meaning: [
      {
        id: 'fr-lm-01',
        audioText: 'Bonjour',
        question: '听到的词是什么意思？',
        options: ['你好', '再见', '对不起', '谢谢'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'fr-lm-02',
        audioText: 'Merci',
        question: '听到的词是什么意思？',
        options: ['你好', '谢谢', '对不起', '再见'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'fr-lm-03',
        audioText: 'Au revoir',
        question: '听到的短语是什么意思？',
        options: ['你好', '谢谢', '再见', '早上好'],
        correctAnswer: '再见',
        difficulty: 1,
      },
      {
        id: 'fr-lm-04',
        audioText: 'Pomme',
        question: '听到的词是什么意思？',
        options: ['葡萄', '橙子', '苹果', '香蕉'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'fr-lm-05',
        audioText: 'Bon matin',
        question: '听到的短语是什么意思？',
        options: ['你好', '晚上好', '早上好', '再见'],
        correctAnswer: '早上好',
        difficulty: 1,
      },
      {
        id: 'fr-lm-06',
        audioText: 'Hôtel',
        question: '听到的词是什么意思？',
        options: ['机场', '医院', '车站', '酒店'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'fr-lm-07',
        audioText: 'Combien ça coûte?',
        question: '听到的句子是什么意思？',
        options: ['这是什么', '多少钱', '几点了', '在哪里'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'fr-lm-08',
        audioText: 'Réunion',
        question: '听到的词是什么意思？',
        options: ['课程', '宴会', '聚会', '会议'],
        correctAnswer: '会议',
        difficulty: 3,
      },
    ],
    word: [
      {
        id: 'fr-lw-01',
        audioText: 'Bonjour',
        question: '听到的词是哪个？',
        options: ['Bonsoir', 'Bonjour', 'Bon', 'Bonbon'],
        correctAnswer: 'Bonjour',
        difficulty: 1,
      },
      {
        id: 'fr-lw-02',
        audioText: 'Merci',
        question: '听到的词是哪个？',
        options: ['Marci', 'Mercredi', 'Merce', 'Merci'],
        correctAnswer: 'Merci',
        difficulty: 1,
      },
      {
        id: 'fr-lw-03',
        audioText: 'Pomme',
        question: '听到的词是哪个？',
        options: ['Orange', 'Banane', 'Raisin', 'Pomme'],
        correctAnswer: 'Pomme',
        difficulty: 1,
      },
      {
        id: 'fr-lw-04',
        audioText: 'Au revoir',
        question: '听到的短语是哪个？',
        options: ['Au revoir', 'À bientôt', 'Bonsoir', 'Bonjour'],
        correctAnswer: 'Au revoir',
        difficulty: 1,
      },
      {
        id: 'fr-lw-05',
        audioText: 'Hôtel',
        question: '听到的词是哪个？',
        options: ['Gare', 'Aéroport', 'Hôtel', 'Hôpital'],
        correctAnswer: 'Hôtel',
        difficulty: 2,
      },
      {
        id: 'fr-lw-06',
        audioText: 'Aéroport',
        question: '听到的词是哪个？',
        options: ['Place', 'Gare', 'Port', 'Aéroport'],
        correctAnswer: 'Aéroport',
        difficulty: 2,
      },
      {
        id: 'fr-lw-07',
        audioText: 'Réservation',
        question: '听到的词是哪个？',
        options: ['Conservation', 'Réservation', 'Préservation', 'Observation'],
        correctAnswer: 'Réservation',
        difficulty: 2,
      },
      {
        id: 'fr-lw-08',
        audioText: 'Entretien',
        question: '听到的词是哪个？',
        options: ['Entretien', 'Entrée', 'Entretemps', 'Entreprise'],
        correctAnswer: 'Entretien',
        difficulty: 3,
      },
    ],
  },
  it: {
    meaning: [
      {
        id: 'it-lm-01',
        audioText: 'Ciao',
        question: '听到的词是什么意思？',
        options: ['谢谢', '你好', '再见', '对不起'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'it-lm-02',
        audioText: 'Grazie',
        question: '听到的词是什么意思？',
        options: ['对不起', '再见', '谢谢', '你好'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'it-lm-03',
        audioText: 'Arrivederci',
        question: '听到的词是什么意思？',
        options: ['再见', '早上好', '你好', '谢谢'],
        correctAnswer: '再见',
        difficulty: 1,
      },
      {
        id: 'it-lm-04',
        audioText: 'Mela',
        question: '听到的词是什么意思？',
        options: ['橙子', '葡萄', '香蕉', '苹果'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'it-lm-05',
        audioText: 'Buongiorno',
        question: '听到的短语是什么意思？',
        options: ['晚上好', '你好', '早上好', '再见'],
        correctAnswer: '早上好',
        difficulty: 1,
      },
      {
        id: 'it-lm-06',
        audioText: 'Albergo',
        question: '听到的词是什么意思？',
        options: ['医院', '车站', '机场', '酒店'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'it-lm-07',
        audioText: 'Quanto costa?',
        question: '听到的句子是什么意思？',
        options: ['多少钱', '几点了', '这是什么', '在哪里'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'it-lm-08',
        audioText: 'Riunione',
        question: '听到的词是什么意思？',
        options: ['宴会', '课程', '聚会', '会议'],
        correctAnswer: '会议',
        difficulty: 3,
      },
    ],
    word: [
      {
        id: 'it-lw-01',
        audioText: 'Ciao',
        question: '听到的词是哪个？',
        options: ['Chao', 'Cioa', 'Ciao', 'Ciaoo'],
        correctAnswer: 'Ciao',
        difficulty: 1,
      },
      {
        id: 'it-lw-02',
        audioText: 'Grazie',
        question: '听到的词是哪个？',
        options: ['Graziosa', 'Grazioso', 'Grazie', 'Grazia'],
        correctAnswer: 'Grazie',
        difficulty: 1,
      },
      {
        id: 'it-lw-03',
        audioText: 'Mela',
        question: '听到的词是哪个？',
        options: ['Arancia', 'Banana', 'Uva', 'Mela'],
        correctAnswer: 'Mela',
        difficulty: 1,
      },
      {
        id: 'it-lw-04',
        audioText: 'Arrivederci',
        question: '听到的词是哪个？',
        options: ['Buonasera', 'Arrivederci', 'Buongiorno', 'A presto'],
        correctAnswer: 'Arrivederci',
        difficulty: 1,
      },
      {
        id: 'it-lw-05',
        audioText: 'Albergo',
        question: '听到的词是哪个？',
        options: ['Ospedale', 'Stazione', 'Aeroporto', 'Albergo'],
        correctAnswer: 'Albergo',
        difficulty: 2,
      },
      {
        id: 'it-lw-06',
        audioText: 'Aeroporto',
        question: '听到的词是哪个？',
        options: ['Stazione', 'Piazza', 'Aeroporto', 'Porto'],
        correctAnswer: 'Aeroporto',
        difficulty: 2,
      },
      {
        id: 'it-lw-07',
        audioText: 'Prenotazione',
        question: '听到的词是哪个？',
        options: ['Conservazione', 'Osservazione', 'Presentazione', 'Prenotazione'],
        correctAnswer: 'Prenotazione',
        difficulty: 2,
      },
      {
        id: 'it-lw-08',
        audioText: 'Colloquio',
        question: '听到的词是哪个？',
        options: ['Colloquio', 'Conferenza', 'Discussione', 'Conversazione'],
        correctAnswer: 'Colloquio',
        difficulty: 3,
      },
    ],
  },
  pt: {
    meaning: [
      {
        id: 'pt-lm-01',
        audioText: 'Olá',
        question: '听到的词是什么意思？',
        options: ['对不起', '你好', '再见', '谢谢'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'pt-lm-02',
        audioText: 'Obrigado',
        question: '听到的词是什么意思？',
        options: ['你好', '谢谢', '再见', '对不起'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'pt-lm-03',
        audioText: 'Adeus',
        question: '听到的词是什么意思？',
        options: ['再见', '你好', '谢谢', '早上好'],
        correctAnswer: '再见',
        difficulty: 1,
      },
      {
        id: 'pt-lm-04',
        audioText: 'Maçã',
        question: '听到的词是什么意思？',
        options: ['橙子', '香蕉', '葡萄', '苹果'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'pt-lm-05',
        audioText: 'Bom dia',
        question: '听到的短语是什么意思？',
        options: ['早上好', '你好', '再见', '晚上好'],
        correctAnswer: '早上好',
        difficulty: 1,
      },
      {
        id: 'pt-lm-06',
        audioText: 'Hotel',
        question: '听到的词是什么意思？',
        options: ['机场', '酒店', '医院', '车站'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'pt-lm-07',
        audioText: 'Quanto custa?',
        question: '听到的句子是什么意思？',
        options: ['几点了', '在哪里', '多少钱', '这是什么'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'pt-lm-08',
        audioText: 'Reunião',
        question: '听到的词是什么意思？',
        options: ['课程', '宴会', '聚会', '会议'],
        correctAnswer: '会议',
        difficulty: 3,
      },
    ],
    word: [
      {
        id: 'pt-lw-01',
        audioText: 'Olá',
        question: '听到的词是哪个？',
        options: ['Ola', 'Olla', 'Olá', 'Olea'],
        correctAnswer: 'Olá',
        difficulty: 1,
      },
      {
        id: 'pt-lw-02',
        audioText: 'Obrigado',
        question: '听到的词是哪个？',
        options: ['Brigado', 'Obrigada', 'Obrigar', 'Obrigado'],
        correctAnswer: 'Obrigado',
        difficulty: 1,
      },
      {
        id: 'pt-lw-03',
        audioText: 'Maçã',
        question: '听到的词是哪个？',
        options: ['Banana', 'Laranja', 'Uva', 'Maçã'],
        correctAnswer: 'Maçã',
        difficulty: 1,
      },
      {
        id: 'pt-lw-04',
        audioText: 'Adeus',
        question: '听到的词是哪个？',
        options: ['Bem', 'Olá', 'Bom', 'Adeus'],
        correctAnswer: 'Adeus',
        difficulty: 1,
      },
      {
        id: 'pt-lw-05',
        audioText: 'Hotel',
        question: '听到的词是哪个？',
        options: ['Hotel', 'Hospital', 'Banco', 'Escola'],
        correctAnswer: 'Hotel',
        difficulty: 2,
      },
      {
        id: 'pt-lw-06',
        audioText: 'Aeroporto',
        question: '听到的词是哪个？',
        options: ['Estação', 'Porto', 'Porta', 'Aeroporto'],
        correctAnswer: 'Aeroporto',
        difficulty: 2,
      },
      {
        id: 'pt-lw-07',
        audioText: 'Reserva',
        question: '听到的词是哪个？',
        options: ['Preserva', 'Conserva', 'Observa', 'Reserva'],
        correctAnswer: 'Reserva',
        difficulty: 2,
      },
      {
        id: 'pt-lw-08',
        audioText: 'Entrevista',
        question: '听到的词是哪个？',
        options: ['Entrevista', 'Entrega', 'Entrada', 'Enquete'],
        correctAnswer: 'Entrevista',
        difficulty: 3,
      },
    ],
  },
  ar: {
    meaning: [
      {
        id: 'ar-lm-01',
        audioText: 'مرحبا',
        question: '听到的词是什么意思？',
        options: ['谢谢', '再见', '对不起', '你好'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'ar-lm-02',
        audioText: 'شكرا',
        question: '听到的词是什么意思？',
        options: ['对不起', '你好', '谢谢', '再见'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'ar-lm-03',
        audioText: 'مع السلامة',
        question: '听到的短语是什么意思？',
        options: ['谢谢', '再见', '你好', '早上好'],
        correctAnswer: '再见',
        difficulty: 1,
      },
      {
        id: 'ar-lm-04',
        audioText: 'تفاح',
        question: '听到的词是什么意思？',
        options: ['橙子', '香蕉', '葡萄', '苹果'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'ar-lm-05',
        audioText: 'صباح الخير',
        question: '听到的短语是什么意思？',
        options: ['再见', '早上好', '你好', '晚上好'],
        correctAnswer: '早上好',
        difficulty: 1,
      },
      {
        id: 'ar-lm-06',
        audioText: 'فندق',
        question: '听到的词是什么意思？',
        options: ['医院', '酒店', '机场', '车站'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'ar-lm-07',
        audioText: 'كم السعر؟',
        question: '听到的句子是什么意思？',
        options: ['几点了', '在哪里', '这是什么', '多少钱'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'ar-lm-08',
        audioText: 'اجتماع',
        question: '听到的词是什么意思？',
        options: ['聚会', '课程', '会议', '宴会'],
        correctAnswer: '会议',
        difficulty: 3,
      },
    ],
    word: [
      {
        id: 'ar-lw-01',
        audioText: 'مرحبا (marhaba)',
        question: '听到的词是哪个？',
        options: ['مربى (murabba)', 'مرحبا (marhaba)', 'مريض (marid)', 'مرة (mara)'],
        correctAnswer: 'مرحبا (marhaba)',
        difficulty: 1,
      },
      {
        id: 'ar-lw-02',
        audioText: 'شكرا (shukran)',
        question: '听到的词是哪个？',
        options: ['شرق (sharq)', 'شكرا (shukran)', 'شمس (shams)', 'شاي (shay)'],
        correctAnswer: 'شكرا (shukran)',
        difficulty: 1,
      },
      {
        id: 'ar-lw-03',
        audioText: 'تفاح (tuffah)',
        question: '听到的词是哪个？',
        options: ['برتقال (burtuqal)', 'تفاح (tuffah)', 'عنب (inab)', 'موز (mawz)'],
        correctAnswer: 'تفاح (tuffah)',
        difficulty: 1,
      },
      {
        id: 'ar-lw-04',
        audioText: 'مع السلامة (ma\'a salama)',
        question: '听到的短语是哪个？',
        options: ['مع السلامة (ma\'a salama)', 'إلى اللقاء (ila al-liqa)', 'مرحبا (marhaba)', 'صباح الخير (sabah al-khayr)'],
        correctAnswer: 'مع السلامة (ma\'a salama)',
        difficulty: 1,
      },
      {
        id: 'ar-lw-05',
        audioText: 'فندق (funduq)',
        question: '听到的词是哪个？',
        options: ['مطار (matar)', 'مستشفى (mustashfa)', 'محطة (mahatta)', 'فندق (funduq)'],
        correctAnswer: 'فندق (funduq)',
        difficulty: 2,
      },
      {
        id: 'ar-lw-06',
        audioText: 'مطار (matar)',
        question: '听到的词是哪个？',
        options: ['سوق (suq)', 'مطار (matar)', 'ميناء (mina)', 'محطة (mahatta)'],
        correctAnswer: 'مطار (matar)',
        difficulty: 2,
      },
      {
        id: 'ar-lw-07',
        audioText: 'حجز (hajz)',
        question: '听到的词是哪个？',
        options: ['حجر (hajar)', 'حساب (hisab)', 'حجز (hajz)', 'حدث (hadath)'],
        correctAnswer: 'حجز (hajz)',
        difficulty: 2,
      },
      {
        id: 'ar-lw-08',
        audioText: 'مقابلة (muqabala)',
        question: '听到的词是哪个？',
        options: ['محاضرة (muhadara)', 'مناظرة (munazara)', 'مقابلة (muqabala)', 'اجتماع (ijtima)'],
        correctAnswer: 'مقابلة (muqabala)',
        difficulty: 3,
      },
    ],
  },
  hi: {
    meaning: [
      {
        id: 'hi-lm-01',
        audioText: 'नमस्ते',
        question: '听到的词是什么意思？',
        options: ['再见', '你好', '对不起', '谢谢'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'hi-lm-02',
        audioText: 'धन्यवाद',
        question: '听到的词是什么意思？',
        options: ['再见', '谢谢', '你好', '对不起'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'hi-lm-03',
        audioText: 'अलविदा',
        question: '听到的词是什么意思？',
        options: ['谢谢', '再见', '早上好', '你好'],
        correctAnswer: '再见',
        difficulty: 1,
      },
      {
        id: 'hi-lm-04',
        audioText: 'सेब',
        question: '听到的词是什么意思？',
        options: ['橙子', '香蕉', '葡萄', '苹果'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'hi-lm-05',
        audioText: 'सुप्रभात',
        question: '听到的词是什么意思？',
        options: ['早上好', '再见', '晚上好', '你好'],
        correctAnswer: '早上好',
        difficulty: 1,
      },
      {
        id: 'hi-lm-06',
        audioText: 'होटल',
        question: '听到的词是什么意思？',
        options: ['车站', '医院', '机场', '酒店'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'hi-lm-07',
        audioText: 'यह कितने का है?',
        question: '听到的句子是什么意思？',
        options: ['这是什么', '几点了', '多少钱', '在哪里'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'hi-lm-08',
        audioText: 'बैठक',
        question: '听到的词是什么意思？',
        options: ['课程', '聚会', '会议', '宴会'],
        correctAnswer: '会议',
        difficulty: 3,
      },
    ],
    word: [
      {
        id: 'hi-lw-01',
        audioText: 'नमस्ते (namaste)',
        question: '听到的词是哪个？',
        options: ['नमस्ते (namaste)', 'नमक (namak)', 'नमकीन (namkeen)', 'नमूना (namuna)'],
        correctAnswer: 'नमस्ते (namaste)',
        difficulty: 1,
      },
      {
        id: 'hi-lw-02',
        audioText: 'धन्यवाद (dhanyavad)',
        question: '听到的词是哪个？',
        options: ['दान (daan)', 'धन्यवाद (dhanyavad)', 'धन्य (dhanya)', 'धन (dhan)'],
        correctAnswer: 'धन्यवाद (dhanyavad)',
        difficulty: 1,
      },
      {
        id: 'hi-lw-03',
        audioText: 'सेब (seb)',
        question: '听到的词是哪个？',
        options: ['संतरा (santra)', 'अंगूर (angur)', 'सेब (seb)', 'केला (kela)'],
        correctAnswer: 'सेब (seb)',
        difficulty: 1,
      },
      {
        id: 'hi-lw-04',
        audioText: 'अलविदा (alavida)',
        question: '听到的词是哪个？',
        options: ['शुभ प्रभात (shubh prabhat)', 'अलविदा (alavida)', 'फिर मिलेंगे (phir milenge)', 'नमस्ते (namaste)'],
        correctAnswer: 'अलविदा (alavida)',
        difficulty: 1,
      },
      {
        id: 'hi-lw-05',
        audioText: 'होटल (hotel)',
        question: '听到的词是哪个？',
        options: ['स्टेशन (station)', 'अस्पताल (aspatal)', 'हवाई अड्डा (havai adda)', 'होटल (hotel)'],
        correctAnswer: 'होटल (hotel)',
        difficulty: 2,
      },
      {
        id: 'hi-lw-06',
        audioText: 'हवाई अड्डा (havai adda)',
        question: '听到的词是哪个？',
        options: ['स्टेशन (station)', 'बाजार (bazaar)', 'हवाई अड्डा (havai adda)', 'बंदरगाह (bandargah)'],
        correctAnswer: 'हवाई अड्डा (havai adda)',
        difficulty: 2,
      },
      {
        id: 'hi-lw-07',
        audioText: 'आरक्षण (aarakshan)',
        question: '听到的词是哪个？',
        options: ['प्रस्तुति (prastuti)', 'आरक्षण (aarakshan)', 'निरीक्षण (nirikshan)', 'संरक्षण (sanrakshan)'],
        correctAnswer: 'आरक्षण (aarakshan)',
        difficulty: 2,
      },
      {
        id: 'hi-lw-08',
        audioText: 'साक्षात्कार (sakshatkar)',
        question: '听到的词是哪个？',
        options: ['वार्ता (varta)', 'साक्षात्कार (sakshatkar)', 'सम्मेलन (sammelan)', 'बैठक (baithak)'],
        correctAnswer: 'साक्षात्कार (sakshatkar)',
        difficulty: 3,
      },
    ],
  },
  th: {
    meaning: [
      {
        id: 'th-lm-01',
        audioText: 'สวัสดี',
        question: '听到的词是什么意思？',
        options: ['再见', '你好', '对不起', '谢谢'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'th-lm-02',
        audioText: 'ขอบคุณ',
        question: '听到的词是什么意思？',
        options: ['谢谢', '再见', '对不起', '你好'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'th-lm-03',
        audioText: 'ลาก่อน',
        question: '听到的词是什么意思？',
        options: ['你好', '谢谢', '再见', '早上好'],
        correctAnswer: '再见',
        difficulty: 1,
      },
      {
        id: 'th-lm-04',
        audioText: 'แอปเปิ้ล',
        question: '听到的词是什么意思？',
        options: ['葡萄', '香蕉', '苹果', '橙子'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'th-lm-05',
        audioText: 'สวัสดีตอนเช้า',
        question: '听到的短语是什么意思？',
        options: ['晚上好', '你好', '再见', '早上好'],
        correctAnswer: '早上好',
        difficulty: 1,
      },
      {
        id: 'th-lm-06',
        audioText: 'โรงแรม',
        question: '听到的词是什么意思？',
        options: ['车站', '医院', '机场', '酒店'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'th-lm-07',
        audioText: 'เท่าไหร่',
        question: '听到的句子是什么意思？',
        options: ['几点了', '这是什么', '在哪里', '多少钱'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'th-lm-08',
        audioText: 'การประชุม',
        question: '听到的词是什么意思？',
        options: ['宴会', '课程', '会议', '聚会'],
        correctAnswer: '会议',
        difficulty: 3,
      },
    ],
    word: [
      {
        id: 'th-lw-01',
        audioText: 'สวัสดี (sawatdee)',
        question: '听到的词是哪个？',
        options: ['สว่าง (sawang)', 'สวัสดี (sawatdee)', 'สวย (suay)', 'สวน (suan)'],
        correctAnswer: 'สวัสดี (sawatdee)',
        difficulty: 1,
      },
      {
        id: 'th-lw-02',
        audioText: 'ขอบคุณ (khob khun)',
        question: '听到的词是哪个？',
        options: ['ขอบคุณ (khob khun)', 'คุณ (khun)', 'ขอ (khor)', 'ขนม (khanom)'],
        correctAnswer: 'ขอบคุณ (khob khun)',
        difficulty: 1,
      },
      {
        id: 'th-lw-03',
        audioText: 'แอปเปิ้ล (apple)',
        question: '听到的词是哪个？',
        options: ['แอปเปิ้ล (apple)', 'ส้ม (som)', 'องุ่น (angun)', 'กล้วย (kluay)'],
        correctAnswer: 'แอปเปิ้ล (apple)',
        difficulty: 1,
      },
      {
        id: 'th-lw-04',
        audioText: 'ลาก่อน (la kon)',
        question: '听到的词是哪个？',
        options: ['แล้วเจอกัน (laew choe kan)', 'สวัสดี (sawatdee)', 'สวัสดีตอนเช้า (sawatdee ton chao)', 'ลาก่อน (la kon)'],
        correctAnswer: 'ลาก่อน (la kon)',
        difficulty: 1,
      },
      {
        id: 'th-lw-05',
        audioText: 'โรงแรม (rong raem)',
        question: '听到的词是哪个？',
        options: ['สถานี (sathani)', 'โรงแรม (rong raem)', 'โรงพยาบาล (rong phayaban)', 'สนามบิน (sanam bin)'],
        correctAnswer: 'โรงแรม (rong raem)',
        difficulty: 2,
      },
      {
        id: 'th-lw-06',
        audioText: 'สนามบิน (sanam bin)',
        question: '听到的词是哪个？',
        options: ['สนามบิน (sanam bin)', 'สถานี (sathani)', 'ท่าเรือ (tharuea)', 'ตลาด (talat)'],
        correctAnswer: 'สนามบิน (sanam bin)',
        difficulty: 2,
      },
      {
        id: 'th-lw-07',
        audioText: 'การจอง (kan jong)',
        question: '听到的词是哪个？',
        options: ['การจอง (kan jong)', 'การรักษา (kan raksa)', 'การค้า (kan kha)', 'การศึกษา (kan sueksa)'],
        correctAnswer: 'การจอง (kan jong)',
        difficulty: 2,
      },
      {
        id: 'th-lw-08',
        audioText: 'การสัมภาษณ์ (kan samphat)',
        question: '听到的词是哪个？',
        options: ['การสนทนา (kan sonthana)', 'การสัมภาษณ์ (kan samphat)', 'การประชุม (kan prachum)', 'การอภิปราย (kan aphiprai)'],
        correctAnswer: 'การสัมภาษณ์ (kan samphat)',
        difficulty: 3,
      },
    ],
  },
  vi: {
    meaning: [
      {
        id: 'vi-lm-01',
        audioText: 'Xin chào',
        question: '听到的词是什么意思？',
        options: ['你好', '再见', '谢谢', '对不起'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'vi-lm-02',
        audioText: 'Cảm ơn',
        question: '听到的词是什么意思？',
        options: ['再见', '对不起', '你好', '谢谢'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'vi-lm-03',
        audioText: 'Tạm biệt',
        question: '听到的词是什么意思？',
        options: ['谢谢', '再见', '你好', '早上好'],
        correctAnswer: '再见',
        difficulty: 1,
      },
      {
        id: 'vi-lm-04',
        audioText: 'Táo',
        question: '听到的词是什么意思？',
        options: ['苹果', '香蕉', '葡萄', '橙子'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'vi-lm-05',
        audioText: 'Chào buổi sáng',
        question: '听到的短语是什么意思？',
        options: ['你好', '再见', '晚上好', '早上好'],
        correctAnswer: '早上好',
        difficulty: 1,
      },
      {
        id: 'vi-lm-06',
        audioText: 'Khách sạn',
        question: '听到的词是什么意思？',
        options: ['酒店', '车站', '医院', '机场'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'vi-lm-07',
        audioText: 'Bao nhiêu tiền?',
        question: '听到的句子是什么意思？',
        options: ['这是什么', '多少钱', '在哪里', '几点了'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'vi-lm-08',
        audioText: 'Cuộc họp',
        question: '听到的词是什么意思？',
        options: ['聚会', '课程', '宴会', '会议'],
        correctAnswer: '会议',
        difficulty: 3,
      },
    ],
    word: [
      {
        id: 'vi-lw-01',
        audioText: 'Xin chào',
        question: '听到的词是哪个？',
        options: ['Xin lỗi', 'Xin cảm ơn', 'Xin phép', 'Xin chào'],
        correctAnswer: 'Xin chào',
        difficulty: 1,
      },
      {
        id: 'vi-lw-02',
        audioText: 'Cảm ơn',
        question: '听到的词是哪个？',
        options: ['Cảm động', 'Cảm xúc', 'Cảm ơn', 'Cảm thấy'],
        correctAnswer: 'Cảm ơn',
        difficulty: 1,
      },
      {
        id: 'vi-lw-03',
        audioText: 'Táo',
        question: '听到的词是哪个？',
        options: ['Chuối', 'Cam', 'Táo', 'Nho'],
        correctAnswer: 'Táo',
        difficulty: 1,
      },
      {
        id: 'vi-lw-04',
        audioText: 'Tạm biệt',
        question: '听到的词是哪个？',
        options: ['Tạm biệt', 'Xin chào', 'Hẹn gặp lại', 'Chào buổi sáng'],
        correctAnswer: 'Tạm biệt',
        difficulty: 1,
      },
      {
        id: 'vi-lw-05',
        audioText: 'Khách sạn',
        question: '听到的词是哪个？',
        options: ['Khách sạn', 'Ga xe lửa', 'Bệnh viện', 'Sân bay'],
        correctAnswer: 'Khách sạn',
        difficulty: 2,
      },
      {
        id: 'vi-lw-06',
        audioText: 'Sân bay',
        question: '听到的词是哪个？',
        options: ['Ga xe lửa', 'Sân bay', 'Chợ', 'Cảng'],
        correctAnswer: 'Sân bay',
        difficulty: 2,
      },
      {
        id: 'vi-lw-07',
        audioText: 'Đặt chỗ',
        question: '听到的词是哪个？',
        options: ['Đặt chỗ', 'Đặt tên', 'Đặt hàng', 'Đặt cược'],
        correctAnswer: 'Đặt chỗ',
        difficulty: 2,
      },
      {
        id: 'vi-lw-08',
        audioText: 'Phỏng vấn',
        question: '听到的词是哪个？',
        options: ['Phỏng đoán', 'Phỏng vấn trực tiếp', 'Phỏng chừng', 'Phỏng vấn'],
        correctAnswer: 'Phỏng vấn',
        difficulty: 3,
      },
    ],
  },
  tr: {
    meaning: [
      {
        id: 'tr-lm-01',
        audioText: 'Merhaba',
        question: '听到的词是什么意思？',
        options: ['谢谢', '对不起', '你好', '再见'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'tr-lm-02',
        audioText: 'Teşekkür ederim',
        question: '听到的短语是什么意思？',
        options: ['再见', '对不起', '谢谢', '你好'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'tr-lm-03',
        audioText: 'Hoşça kal',
        question: '听到的短语是什么意思？',
        options: ['你好', '谢谢', '早上好', '再见'],
        correctAnswer: '再见',
        difficulty: 1,
      },
      {
        id: 'tr-lm-04',
        audioText: 'Elma',
        question: '听到的词是什么意思？',
        options: ['橙子', '苹果', '葡萄', '香蕉'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'tr-lm-05',
        audioText: 'Günaydın',
        question: '听到的词是什么意思？',
        options: ['早上好', '晚上好', '你好', '再见'],
        correctAnswer: '早上好',
        difficulty: 1,
      },
      {
        id: 'tr-lm-06',
        audioText: 'Otel',
        question: '听到的词是什么意思？',
        options: ['车站', '酒店', '医院', '机场'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'tr-lm-07',
        audioText: 'Ne kadar?',
        question: '听到的句子是什么意思？',
        options: ['这是什么', '多少钱', '几点了', '在哪里'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'tr-lm-08',
        audioText: 'Toplantı',
        question: '听到的词是什么意思？',
        options: ['会议', '聚会', '宴会', '课程'],
        correctAnswer: '会议',
        difficulty: 3,
      },
    ],
    word: [
      {
        id: 'tr-lw-01',
        audioText: 'Merhaba',
        question: '听到的词是哪个？',
        options: ['Mübarek', 'Marhaba', 'Mürhaba', 'Merhaba'],
        correctAnswer: 'Merhaba',
        difficulty: 1,
      },
      {
        id: 'tr-lw-02',
        audioText: 'Teşekkür ederim',
        question: '听到的短语是哪个？',
        options: ['Teşekkürler', 'Eyvallah', 'Teşekkür ederim', 'Sağ ol'],
        correctAnswer: 'Teşekkür ederim',
        difficulty: 1,
      },
      {
        id: 'tr-lw-03',
        audioText: 'Elma',
        question: '听到的词是哪个？',
        options: ['Muz', 'Portakal', 'Üzüm', 'Elma'],
        correctAnswer: 'Elma',
        difficulty: 1,
      },
      {
        id: 'tr-lw-04',
        audioText: 'Hoşça kal',
        question: '听到的短语是哪个？',
        options: ['Hoşça kal', 'Güle güle', 'Merhaba', 'Günaydın'],
        correctAnswer: 'Hoşça kal',
        difficulty: 1,
      },
      {
        id: 'tr-lw-05',
        audioText: 'Otel',
        question: '听到的词是哪个？',
        options: ['İstasyon', 'Otel', 'Hastane', 'Havalimanı'],
        correctAnswer: 'Otel',
        difficulty: 2,
      },
      {
        id: 'tr-lw-06',
        audioText: 'Havalimanı',
        question: '听到的词是哪个？',
        options: ['Pazar', 'Havalimanı', 'İstasyon', 'Liman'],
        correctAnswer: 'Havalimanı',
        difficulty: 2,
      },
      {
        id: 'tr-lw-07',
        audioText: 'Rezervasyon',
        question: '听到的词是哪个？',
        options: ['Prezervasyon', 'Observasyon', 'Konservasyon', 'Rezervasyon'],
        correctAnswer: 'Rezervasyon',
        difficulty: 2,
      },
      {
        id: 'tr-lw-08',
        audioText: 'Mülakat',
        question: '听到的词是哪个？',
        options: ['Görüşme', 'Müzakere', 'Toplantı', 'Mülakat'],
        correctAnswer: 'Mülakat',
        difficulty: 3,
      },
    ],
  },
  pl: {
    meaning: [
      {
        id: 'pl-lm-01',
        audioText: 'Cześć',
        question: '听到的词是什么意思？',
        options: ['谢谢', '再见', '对不起', '你好'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'pl-lm-02',
        audioText: 'Dziękuję',
        question: '听到的词是什么意思？',
        options: ['再见', '你好', '对不起', '谢谢'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'pl-lm-03',
        audioText: 'Do widzenia',
        question: '听到的短语是什么意思？',
        options: ['再见', '早上好', '你好', '谢谢'],
        correctAnswer: '再见',
        difficulty: 1,
      },
      {
        id: 'pl-lm-04',
        audioText: 'Jabłko',
        question: '听到的词是什么意思？',
        options: ['橙子', '香蕉', '苹果', '葡萄'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'pl-lm-05',
        audioText: 'Dzień dobry',
        question: '听到的短语是什么意思？',
        options: ['再见', '你好', '晚上好', '早上好'],
        correctAnswer: '早上好',
        difficulty: 1,
      },
      {
        id: 'pl-lm-06',
        audioText: 'Hotel',
        question: '听到的词是什么意思？',
        options: ['酒店', '机场', '医院', '车站'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'pl-lm-07',
        audioText: 'Ile to kosztuje?',
        question: '听到的句子是什么意思？',
        options: ['在哪里', '多少钱', '这是什么', '几点了'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'pl-lm-08',
        audioText: 'Spotkanie',
        question: '听到的词是什么意思？',
        options: ['宴会', '会议', '课程', '聚会'],
        correctAnswer: '会议',
        difficulty: 3,
      },
    ],
    word: [
      {
        id: 'pl-lw-01',
        audioText: 'Cześć',
        question: '听到的词是哪个？',
        options: ['Część', 'Cześć', 'Cieśń', 'Cześćik'],
        correctAnswer: 'Cześć',
        difficulty: 1,
      },
      {
        id: 'pl-lw-02',
        audioText: 'Dziękuję',
        question: '听到的词是哪个？',
        options: ['Dziwny', 'Dziękuję', 'Dziki', 'Dzięki'],
        correctAnswer: 'Dziękuję',
        difficulty: 1,
      },
      {
        id: 'pl-lw-03',
        audioText: 'Jabłko',
        question: '听到的词是哪个？',
        options: ['Pomarańcza', 'Jabłko', 'Banan', 'Winogrono'],
        correctAnswer: 'Jabłko',
        difficulty: 1,
      },
      {
        id: 'pl-lw-04',
        audioText: 'Do widzenia',
        question: '听到的短语是哪个？',
        options: ['Dzień dobry', 'Do zobaczenia', 'Do widzenia', 'Cześć'],
        correctAnswer: 'Do widzenia',
        difficulty: 1,
      },
      {
        id: 'pl-lw-05',
        audioText: 'Hotel',
        question: '听到的词是哪个？',
        options: ['Hotel', 'Szpital', 'Lotnisko', 'Dworzec'],
        correctAnswer: 'Hotel',
        difficulty: 2,
      },
      {
        id: 'pl-lw-06',
        audioText: 'Lotnisko',
        question: '听到的词是哪个？',
        options: ['Rynek', 'Port', 'Dworzec', 'Lotnisko'],
        correctAnswer: 'Lotnisko',
        difficulty: 2,
      },
      {
        id: 'pl-lw-07',
        audioText: 'Rezerwacja',
        question: '听到的词是哪个？',
        options: ['Rezerwacja', 'Konservacja', 'Prezerwacja', 'Obserwacja'],
        correctAnswer: 'Rezerwacja',
        difficulty: 2,
      },
      {
        id: 'pl-lw-08',
        audioText: 'Wywiad',
        question: '听到的词是哪个？',
        options: ['Rozmowa', 'Wywiad', 'Spotkanie', 'Wykład'],
        correctAnswer: 'Wywiad',
        difficulty: 3,
      },
    ],
  },
  nl: {
    meaning: [
      {
        id: 'nl-lm-01',
        audioText: 'Hallo',
        question: '听到的词是什么意思？',
        options: ['再见', '你好', '对不起', '谢谢'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'nl-lm-02',
        audioText: 'Dank je',
        question: '听到的词是什么意思？',
        options: ['再见', '谢谢', '对不起', '你好'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'nl-lm-03',
        audioText: 'Tot ziens',
        question: '听到的短语是什么意思？',
        options: ['再见', '你好', '谢谢', '早上好'],
        correctAnswer: '再见',
        difficulty: 1,
      },
      {
        id: 'nl-lm-04',
        audioText: 'Appel',
        question: '听到的词是什么意思？',
        options: ['橙子', '苹果', '香蕉', '葡萄'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'nl-lm-05',
        audioText: 'Goedemorgen',
        question: '听到的短语是什么意思？',
        options: ['晚上好', '你好', '再见', '早上好'],
        correctAnswer: '早上好',
        difficulty: 1,
      },
      {
        id: 'nl-lm-06',
        audioText: 'Hotel',
        question: '听到的词是什么意思？',
        options: ['车站', '机场', '酒店', '医院'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'nl-lm-07',
        audioText: 'Hoeveel kost dat?',
        question: '听到的句子是什么意思？',
        options: ['多少钱', '这是什么', '几点了', '在哪里'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'nl-lm-08',
        audioText: 'Vergadering',
        question: '听到的词是什么意思？',
        options: ['课程', '会议', '聚会', '宴会'],
        correctAnswer: '会议',
        difficulty: 3,
      },
    ],
    word: [
      {
        id: 'nl-lw-01',
        audioText: 'Hallo',
        question: '听到的词是哪个？',
        options: ['Hallo', 'Hola', 'Hulloo', 'Hei'],
        correctAnswer: 'Hallo',
        difficulty: 1,
      },
      {
        id: 'nl-lw-02',
        audioText: 'Dank je',
        question: '听到的词是哪个？',
        options: ['Bedankt', 'Dankbaar', 'Dank je', 'Dank u'],
        correctAnswer: 'Dank je',
        difficulty: 1,
      },
      {
        id: 'nl-lw-03',
        audioText: 'Appel',
        question: '听到的词是哪个？',
        options: ['Sinaasappel', 'Druif', 'Banaan', 'Appel'],
        correctAnswer: 'Appel',
        difficulty: 1,
      },
      {
        id: 'nl-lw-04',
        audioText: 'Tot ziens',
        question: '听到的短语是哪个？',
        options: ['Goedemorgen', 'Hallo', 'Tot later', 'Tot ziens'],
        correctAnswer: 'Tot ziens',
        difficulty: 1,
      },
      {
        id: 'nl-lw-05',
        audioText: 'Hotel',
        question: '听到的词是哪个？',
        options: ['Vliegveld', 'Hotel', 'Ziekenhuis', 'Station'],
        correctAnswer: 'Hotel',
        difficulty: 2,
      },
      {
        id: 'nl-lw-06',
        audioText: 'Vliegveld',
        question: '听到的词是哪个？',
        options: ['Vliegveld', 'Markt', 'Haven', 'Station'],
        correctAnswer: 'Vliegveld',
        difficulty: 2,
      },
      {
        id: 'nl-lw-07',
        audioText: 'Reservering',
        question: '听到的词是哪个？',
        options: ['Reservering', 'Preservatie', 'Observatie', 'Conservatie'],
        correctAnswer: 'Reservering',
        difficulty: 2,
      },
      {
        id: 'nl-lw-08',
        audioText: 'Sollicitatiegesprek',
        question: '听到的词是哪个？',
        options: ['Vergadering', 'Sollicitatiegesprek', 'Onderhoud', 'Gesprek'],
        correctAnswer: 'Sollicitatiegesprek',
        difficulty: 3,
      },
    ],
  },
  el: {
    meaning: [
      {
        id: 'el-lm-01',
        audioText: 'Γειά σου',
        question: '听到的短语是什么意思？',
        options: ['你好', '再见', '谢谢', '对不起'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'el-lm-02',
        audioText: 'Ευχαριστώ',
        question: '听到的词是什么意思？',
        options: ['你好', '对不起', '再见', '谢谢'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'el-lm-03',
        audioText: 'Αντίο',
        question: '听到的词是什么意思？',
        options: ['谢谢', '你好', '再见', '早上好'],
        correctAnswer: '再见',
        difficulty: 1,
      },
      {
        id: 'el-lm-04',
        audioText: 'Μήλο',
        question: '听到的词是什么意思？',
        options: ['葡萄', '橙子', '香蕉', '苹果'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'el-lm-05',
        audioText: 'Καλημέρα',
        question: '听到的词是什么意思？',
        options: ['你好', '再见', '早上好', '晚上好'],
        correctAnswer: '早上好',
        difficulty: 1,
      },
      {
        id: 'el-lm-06',
        audioText: 'Ξενοδοχείο',
        question: '听到的词是什么意思？',
        options: ['医院', '酒店', '车站', '机场'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'el-lm-07',
        audioText: 'Πόσο κοστίζει;',
        question: '听到的句子是什么意思？',
        options: ['这是什么', '多少钱', '在哪里', '几点了'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'el-lm-08',
        audioText: 'Συνάντηση',
        question: '听到的词是什么意思？',
        options: ['课程', '聚会', '会议', '宴会'],
        correctAnswer: '会议',
        difficulty: 3,
      },
    ],
    word: [
      {
        id: 'el-lw-01',
        audioText: 'Γειά σου (Yia sou)',
        question: '听到的短语是哪个？',
        options: ['Σου (Sou)', 'Γειά (Yia)', 'Σας (Sas)', 'Γειά σου (Yia sou)'],
        correctAnswer: 'Γειά σου (Yia sou)',
        difficulty: 1,
      },
      {
        id: 'el-lw-02',
        audioText: 'Ευχαριστώ (Efharisto)',
        question: '听到的词是哪个？',
        options: ['Ευχαριστώ (Efharisto)', 'Χάρη (Hari)', 'Χαρά (Hara)', 'Ευχή (Efhi)'],
        correctAnswer: 'Ευχαριστώ (Efharisto)',
        difficulty: 1,
      },
      {
        id: 'el-lw-03',
        audioText: 'Μήλο (Milo)',
        question: '听到的词是哪个？',
        options: ['Σταφύλι (Stafyli)', 'Μήλο (Milo)', 'Πορτοκάλι (Portokali)', 'Μπανάνα (Banana)'],
        correctAnswer: 'Μήλο (Milo)',
        difficulty: 1,
      },
      {
        id: 'el-lw-04',
        audioText: 'Αντίο (Adio)',
        question: '听到的词是哪个？',
        options: ['Τα λέμε (Ta leme)', 'Καλημέρα (Kalimera)', 'Γειά σου (Yia sou)', 'Αντίο (Adio)'],
        correctAnswer: 'Αντίο (Adio)',
        difficulty: 1,
      },
      {
        id: 'el-lw-05',
        audioText: 'Ξενοδοχείο (Xenodohio)',
        question: '听到的词是哪个？',
        options: ['Αεροδρόμιο (Aerodromio)', 'Νοσοκομείο (Nosokomio)', 'Σταθμός (Stathmos)', 'Ξενοδοχείο (Xenodohio)'],
        correctAnswer: 'Ξενοδοχείο (Xenodohio)',
        difficulty: 2,
      },
      {
        id: 'el-lw-06',
        audioText: 'Αεροδρόμιο (Aerodromio)',
        question: '听到的词是哪个？',
        options: ['Αεροδρόμιο (Aerodromio)', 'Αγορά (Agora)', 'Σταθμός (Stathmos)', 'Λιμάνι (Limani)'],
        correctAnswer: 'Αεροδρόμιο (Aerodromio)',
        difficulty: 2,
      },
      {
        id: 'el-lw-07',
        audioText: 'Κράτηση (Kratisi)',
        question: '听到的词是哪个？',
        options: ['Κράτηση (Kratisi)', 'Παρατήρηση (Paratirisi)', 'Διατήρηση (Diatirisi)', 'Παράσταση (Parastasi)'],
        correctAnswer: 'Κράτηση (Kratisi)',
        difficulty: 2,
      },
      {
        id: 'el-lw-08',
        audioText: 'Συνέντευξη (Sinenteuksi)',
        question: '听到的词是哪个？',
        options: ['Συνέλευση (Sinelefsi)', 'Συνάντηση (Sinantisi)', 'Συζήτηση (Sizitisi)', 'Συνέντευξη (Sinenteuksi)'],
        correctAnswer: 'Συνέντευξη (Sinenteuksi)',
        difficulty: 3,
      },
    ],
  },
  yue: {
    meaning: [
      {
        id: 'yue-lm-01',
        audioText: '你好',
        question: '听到的词是什么意思？',
        options: ['再见', '对不起', '你好', '谢谢'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'yue-lm-02',
        audioText: '多謝',
        question: '听到的词是什么意思？',
        options: ['谢谢', '再见', '你好', '对不起'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'yue-lm-03',
        audioText: '再見',
        question: '听到的词是什么意思？',
        options: ['早上好', '再见', '你好', '谢谢'],
        correctAnswer: '再见',
        difficulty: 1,
      },
      {
        id: 'yue-lm-04',
        audioText: '蘋果',
        question: '听到的词是什么意思？',
        options: ['苹果', '葡萄', '橙子', '香蕉'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'yue-lm-05',
        audioText: '早晨',
        question: '听到的词是什么意思？',
        options: ['你好', '再见', '早上好', '晚上好'],
        correctAnswer: '早上好',
        difficulty: 1,
      },
      {
        id: 'yue-lm-06',
        audioText: '酒店',
        question: '听到的词是什么意思？',
        options: ['医院', '机场', '车站', '酒店'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'yue-lm-07',
        audioText: '幾多錢',
        question: '听到的句子是什么意思？',
        options: ['多少钱', '几点了', '这是什么', '在哪里'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'yue-lm-08',
        audioText: '開會',
        question: '听到的词是什么意思？',
        options: ['宴会', '聚会', '课程', '会议'],
        correctAnswer: '会议',
        difficulty: 2,
      },
    ],
    word: [
      {
        id: 'yue-lw-01',
        audioText: '你好 (nei5 hou2)',
        question: '听到的词是哪个？',
        options: ['多謝 (do1 ze6)', '你好 (nei5 hou2)', '再見 (zoi3 gin3)', '您好 (nei5 hou2)'],
        correctAnswer: '你好 (nei5 hou2)',
        difficulty: 1,
      },
      {
        id: 'yue-lw-02',
        audioText: '多謝 (do1 ze6)',
        question: '听到的词是哪个？',
        options: ['唔該 (m4 goi1)', '多謝 (do1 ze6)', '多謝晒 (do1 ze6 saai3)', '對唔住 (deoi3 m4 zyu6)'],
        correctAnswer: '多謝 (do1 ze6)',
        difficulty: 1,
      },
      {
        id: 'yue-lw-03',
        audioText: '蘋果 (ping4 gwo2)',
        question: '听到的词是哪个？',
        options: ['香蕉 (hoeng1 ziu1)', '蘋果 (ping4 gwo2)', '提子 (tai4 zi2)', '橙 (caang2)'],
        correctAnswer: '蘋果 (ping4 gwo2)',
        difficulty: 1,
      },
      {
        id: 'yue-lw-04',
        audioText: '早晨 (zou2 san4)',
        question: '听到的词是哪个？',
        options: ['早唞 (zou2 tau2)', '晚安 (maan5 on1)', '午安 (ng5 on1)', '早晨 (zou2 san4)'],
        correctAnswer: '早晨 (zou2 san4)',
        difficulty: 1,
      },
      {
        id: 'yue-lw-05',
        audioText: '酒店 (zau2 dim3)',
        question: '听到的词是哪个？',
        options: ['醫院 (ji1 jyun6)', '酒店 (zau2 dim3)', '車站 (ce1 zaam6)', '賓館 (ban1 gun2)'],
        correctAnswer: '酒店 (zau2 dim3)',
        difficulty: 2,
      },
      {
        id: 'yue-lw-06',
        audioText: '機場 (gei1 coeng4)',
        question: '听到的词是哪个？',
        options: ['碼頭 (maa5 tau4)', '機場 (gei1 coeng4)', '火車站 (fo2 ce1 zaam6)', '街市 (gaai1 si5)'],
        correctAnswer: '機場 (gei1 coeng4)',
        difficulty: 2,
      },
      {
        id: 'yue-lw-07',
        audioText: '訂位 (deng6 wai2)',
        question: '听到的词是哪个？',
        options: ['訂餐 (deng6 caan1)', '訂貨 (deng6 fo3)', '訂位 (deng6 wai2)', '訂票 (deng6 piu3)'],
        correctAnswer: '訂位 (deng6 wai2)',
        difficulty: 2,
      },
      {
        id: 'yue-lw-08',
        audioText: '面試 (min6 si3)',
        question: '听到的词是哪个？',
        options: ['商談 (soeng1 taam4)', '面試 (min6 si3)', '會議 (wui5 ji5)', '面談 (min6 taam4)'],
        correctAnswer: '面試 (min6 si3)',
        difficulty: 3,
      },
    ],
  },
  nan: {
    meaning: [
      {
        id: 'nan-lm-01',
        audioText: '你好',
        question: '听到的词是什么意思？',
        options: ['你好', '再见', '对不起', '谢谢'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'nan-lm-02',
        audioText: '多謝',
        question: '听到的词是什么意思？',
        options: ['对不起', '再见', '谢谢', '你好'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'nan-lm-03',
        audioText: '再會',
        question: '听到的词是什么意思？',
        options: ['再见', '你好', '谢谢', '早上好'],
        correctAnswer: '再见',
        difficulty: 1,
      },
      {
        id: 'nan-lm-04',
        audioText: '蘋果',
        question: '听到的词是什么意思？',
        options: ['葡萄', '香蕉', '苹果', '橙子'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'nan-lm-05',
        audioText: '早安',
        question: '听到的词是什么意思？',
        options: ['早上好', '再见', '晚上好', '你好'],
        correctAnswer: '早上好',
        difficulty: 1,
      },
      {
        id: 'nan-lm-06',
        audioText: '飯店',
        question: '听到的词是什么意思？',
        options: ['医院', '机场', '酒店', '车站'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'nan-lm-07',
        audioText: '偌濟錢',
        question: '听到的句子是什么意思？',
        options: ['几点了', '在哪里', '这是什么', '多少钱'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'nan-lm-08',
        audioText: '開會',
        question: '听到的词是什么意思？',
        options: ['宴会', '聚会', '会议', '课程'],
        correctAnswer: '会议',
        difficulty: 2,
      },
    ],
    word: [
      {
        id: 'nan-lw-01',
        audioText: '你好 (lí-hó)',
        question: '听到的词是哪个？',
        options: ['再會 (tsài-huē)', '多謝 (to-siā)', '你好 (lí-hó)', '您好 (lín-hó)'],
        correctAnswer: '你好 (lí-hó)',
        difficulty: 1,
      },
      {
        id: 'nan-lw-02',
        audioText: '多謝 (to-siā)',
        question: '听到的词是哪个？',
        options: ['對不住 (tuì-put-tsū)', '多謝你 (to-siā-lí)', '感謝 (kám-siā)', '多謝 (to-siā)'],
        correctAnswer: '多謝 (to-siā)',
        difficulty: 1,
      },
      {
        id: 'nan-lw-03',
        audioText: '蘋果 (pîn-kó)',
        question: '听到的词是哪个？',
        options: ['柑仔 (kam-á)', '蘋果 (pîn-kó)', '葡萄 (phû-tô)', '弓蕉 (king-tsio)'],
        correctAnswer: '蘋果 (pîn-kó)',
        difficulty: 1,
      },
      {
        id: 'nan-lw-04',
        audioText: '早安 (tsá-ān)',
        question: '听到的词是哪个？',
        options: ['日安 (ji̍t-ān)', '再會 (tsài-huē)', '早安 (tsá-ān)', '晚安 (ám-ān)'],
        correctAnswer: '早安 (tsá-ān)',
        difficulty: 1,
      },
      {
        id: 'nan-lw-05',
        audioText: '飯店 (pn̄g-tiàm)',
        question: '听到的词是哪个？',
        options: ['車站 (tshia-tsām)', '賓館 (pin-kuán)', '醫院 (i-īnn)', '飯店 (pn̄g-tiàm)'],
        correctAnswer: '飯店 (pn̄g-tiàm)',
        difficulty: 2,
      },
      {
        id: 'nan-lw-06',
        audioText: '機場 (ki-tiûnn)',
        question: '听到的词是哪个？',
        options: ['碼頭 (bé-thâu)', '機場 (ki-tiûnn)', '街市 (ke-tshī)', '火車站 (hé-tshia-tsām)'],
        correctAnswer: '機場 (ki-tiûnn)',
        difficulty: 2,
      },
      {
        id: 'nan-lw-07',
        audioText: '訂位 (tīng-uī)',
        question: '听到的词是哪个？',
        options: ['訂位 (tīng-uī)', '訂貨 (tīng-huè)', '訂票 (tīng-phiò)', '訂餐 (tīng-tshán)'],
        correctAnswer: '訂位 (tīng-uī)',
        difficulty: 2,
      },
      {
        id: 'nan-lw-08',
        audioText: '面試 (bīn-shì)',
        question: '听到的词是哪个？',
        options: ['商談 (siong-tâm)', '面談 (bīn-tâm)', '面試 (bīn-shì)', '會議 (huē-gī)'],
        correctAnswer: '面試 (bīn-shì)',
        difficulty: 3,
      },
    ],
  },
  'zh-SC': {
    meaning: [
      {
        id: 'zh-SC-lm-01',
        audioText: '你好',
        question: '听到的词是什么意思？',
        options: ['对不起', '谢谢', '你好', '再见'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'zh-SC-lm-02',
        audioText: '谢谢',
        question: '听到的词是什么意思？',
        options: ['你好', '对不起', '再见', '谢谢'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'zh-SC-lm-03',
        audioText: '再见',
        question: '听到的词是什么意思？',
        options: ['你好', '再见', '早上好', '谢谢'],
        correctAnswer: '再见',
        difficulty: 1,
      },
      {
        id: 'zh-SC-lm-04',
        audioText: '苹果',
        question: '听到的词是什么意思？',
        options: ['橙子', '葡萄', '香蕉', '苹果'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'zh-SC-lm-05',
        audioText: '早上好',
        question: '听到的词是什么意思？',
        options: ['再见', '晚上好', '你好', '早上好'],
        correctAnswer: '早上好',
        difficulty: 1,
      },
      {
        id: 'zh-SC-lm-06',
        audioText: '宾馆',
        question: '听到的词是什么意思？',
        options: ['医院', '酒店', '车站', '机场'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'zh-SC-lm-07',
        audioText: '好多钱',
        question: '听到的句子是什么意思？',
        options: ['这是什么', '多少钱', '在哪里', '几点了'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'zh-SC-lm-08',
        audioText: '开会',
        question: '听到的词是什么意思？',
        options: ['宴会', '课程', '聚会', '会议'],
        correctAnswer: '会议',
        difficulty: 2,
      },
    ],
    word: [
      {
        id: 'zh-SC-lw-01',
        audioText: '你好 (ni3 hao3)',
        question: '听到的词是哪个？',
        options: ['你好 (ni3 hao3)', '您好 (nin2 hao3)', '谢谢 (xie4 xie)', '再见 (zai4 jian4)'],
        correctAnswer: '你好 (ni3 hao3)',
        difficulty: 1,
      },
      {
        id: 'zh-SC-lw-02',
        audioText: '谢谢 (xie4 xie)',
        question: '听到的词是哪个？',
        options: ['对不住 (dui4 bu5 zhu4)', '感谢 (gan3 xie4)', '多谢 (do1 xie4)', '谢谢 (xie4 xie)'],
        correctAnswer: '谢谢 (xie4 xie)',
        difficulty: 1,
      },
      {
        id: 'zh-SC-lw-03',
        audioText: '苹果 (ping2 guo3)',
        question: '听到的词是哪个？',
        options: ['香蕉 (xiang1 jiao1)', '橙子 (cen2 zi3)', '葡萄 (pu2 tao2)', '苹果 (ping2 guo3)'],
        correctAnswer: '苹果 (ping2 guo3)',
        difficulty: 1,
      },
      {
        id: 'zh-SC-lw-04',
        audioText: '早上好 (zao3 shang1 hao3)',
        question: '听到的词是哪个？',
        options: ['晚上好 (wan3 shang1 hao3)', '再见 (zai4 jian4)', '早上好 (zao3 shang1 hao3)', '中午好 (zong1 wu3 hao3)'],
        correctAnswer: '早上好 (zao3 shang1 hao3)',
        difficulty: 1,
      },
      {
        id: 'zh-SC-lw-05',
        audioText: '宾馆 (bin1 guan3)',
        question: '听到的词是哪个？',
        options: ['医院 (yi1 yuan4)', '宾馆 (bin1 guan3)', '车站 (ce1 zhan4)', '酒店 (jiu3 dian4)'],
        correctAnswer: '宾馆 (bin1 guan3)',
        difficulty: 2,
      },
      {
        id: 'zh-SC-lw-06',
        audioText: '机场 (ji1 chang3)',
        question: '听到的词是哪个？',
        options: ['机场 (ji1 chang3)', '码头 (ma3 tou2)', '火车站 (huo3 ce1 zhan4)', '街市 (gai1 si4)'],
        correctAnswer: '机场 (ji1 chang3)',
        difficulty: 2,
      },
      {
        id: 'zh-SC-lw-07',
        audioText: '订位 (din4 wei4)',
        question: '听到的词是哪个？',
        options: ['订货 (din4 huo4)', '订位 (din4 wei4)', '订票 (din4 piao4)', '订餐 (din4 can1)'],
        correctAnswer: '订位 (din4 wei4)',
        difficulty: 2,
      },
      {
        id: 'zh-SC-lw-08',
        audioText: '面试 (mian4 si4)',
        question: '听到的词是哪个？',
        options: ['商谈 (shang1 tan2)', '会议 (hui4 yi4)', '面谈 (mian4 tan2)', '面试 (mian4 si4)'],
        correctAnswer: '面试 (mian4 si4)',
        difficulty: 3,
      },
    ],
  },
  'zh-DB': {
    meaning: [
      {
        id: 'zh-DB-lm-01',
        audioText: '你好',
        question: '听到的词是什么意思？',
        options: ['谢谢', '再见', '对不起', '你好'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'zh-DB-lm-02',
        audioText: '谢谢',
        question: '听到的词是什么意思？',
        options: ['谢谢', '你好', '再见', '对不起'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'zh-DB-lm-03',
        audioText: '再见',
        question: '听到的词是什么意思？',
        options: ['谢谢', '再见', '你好', '早上好'],
        correctAnswer: '再见',
        difficulty: 1,
      },
      {
        id: 'zh-DB-lm-04',
        audioText: '苹果',
        question: '听到的词是什么意思？',
        options: ['橙子', '葡萄', '香蕉', '苹果'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'zh-DB-lm-05',
        audioText: '早上好',
        question: '听到的词是什么意思？',
        options: ['晚上好', '你好', '早上好', '再见'],
        correctAnswer: '早上好',
        difficulty: 1,
      },
      {
        id: 'zh-DB-lm-06',
        audioText: '宾馆',
        question: '听到的词是什么意思？',
        options: ['医院', '车站', '酒店', '机场'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'zh-DB-lm-07',
        audioText: '多钱',
        question: '听到的句子是什么意思？',
        options: ['这是什么', '几点了', '在哪里', '多少钱'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'zh-DB-lm-08',
        audioText: '开会',
        question: '听到的词是什么意思？',
        options: ['会议', '课程', '宴会', '聚会'],
        correctAnswer: '会议',
        difficulty: 2,
      },
    ],
    word: [
      {
        id: 'zh-DB-lw-01',
        audioText: '你好 (ni3 hao3)',
        question: '听到的词是哪个？',
        options: ['您好 (nin2 hao3)', '再见 (zai4 jian4)', '你好 (ni3 hao3)', '谢谢 (xie4 xie)'],
        correctAnswer: '你好 (ni3 hao3)',
        difficulty: 1,
      },
      {
        id: 'zh-DB-lw-02',
        audioText: '谢谢 (xie4 xie)',
        question: '听到的词是哪个？',
        options: ['谢谢 (xie4 xie)', '对不住 (dui4 bu5 zhu4)', '感谢 (gan3 xie4)', '多谢 (duo1 xie4)'],
        correctAnswer: '谢谢 (xie4 xie)',
        difficulty: 1,
      },
      {
        id: 'zh-DB-lw-03',
        audioText: '苹果 (ping2 guo3)',
        question: '听到的词是哪个？',
        options: ['苹果 (ping2 guo3)', '香蕉 (xiang1 jiao1)', '葡萄 (pu2 tao2)', '橙子 (cheng2 zi3)'],
        correctAnswer: '苹果 (ping2 guo3)',
        difficulty: 1,
      },
      {
        id: 'zh-DB-lw-04',
        audioText: '早上好 (zao3 shang1 hao3)',
        question: '听到的词是哪个？',
        options: ['再见 (zai4 jian4)', '晚上好 (wan3 shang1 hao3)', '中午好 (zhong1 wu3 hao3)', '早上好 (zao3 shang1 hao3)'],
        correctAnswer: '早上好 (zao3 shang1 hao3)',
        difficulty: 1,
      },
      {
        id: 'zh-DB-lw-05',
        audioText: '宾馆 (bin1 guan3)',
        question: '听到的词是哪个？',
        options: ['酒店 (jiu3 dian4)', '医院 (yi1 yuan4)', '宾馆 (bin1 guan3)', '车站 (che1 zhan4)'],
        correctAnswer: '宾馆 (bin1 guan3)',
        difficulty: 2,
      },
      {
        id: 'zh-DB-lw-06',
        audioText: '机场 (ji1 chang3)',
        question: '听到的词是哪个？',
        options: ['码头 (ma3 tou2)', '机场 (ji1 chang3)', '火车站 (huo3 che1 zhan4)', '街市 (jie1 shi4)'],
        correctAnswer: '机场 (ji1 chang3)',
        difficulty: 2,
      },
      {
        id: 'zh-DB-lw-07',
        audioText: '订位 (ding4 wei4)',
        question: '听到的词是哪个？',
        options: ['订货 (ding4 huo4)', '订位 (ding4 wei4)', '订餐 (ding4 can1)', '订票 (ding4 piao4)'],
        correctAnswer: '订位 (ding4 wei4)',
        difficulty: 2,
      },
      {
        id: 'zh-DB-lw-08',
        audioText: '面试 (mian4 shi4)',
        question: '听到的词是哪个？',
        options: ['会议 (hui4 yi4)', '商谈 (shang1 tan2)', '面试 (mian4 shi4)', '面谈 (mian4 tan2)'],
        correctAnswer: '面试 (mian4 shi4)',
        difficulty: 3,
      },
    ],
  },
  sh: {
    meaning: [
      {
        id: 'sh-lm-01',
        audioText: '侬好',
        question: '听到的词是什么意思？',
        options: ['对不起', '你好', '再见', '谢谢'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'sh-lm-02',
        audioText: '谢谢',
        question: '听到的词是什么意思？',
        options: ['再见', '你好', '对不起', '谢谢'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'sh-lm-03',
        audioText: '再会',
        question: '听到的词是什么意思？',
        options: ['谢谢', '你好', '早上好', '再见'],
        correctAnswer: '再见',
        difficulty: 1,
      },
      {
        id: 'sh-lm-04',
        audioText: '苹果',
        question: '听到的词是什么意思？',
        options: ['橙子', '苹果', '香蕉', '葡萄'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'sh-lm-05',
        audioText: '早安',
        question: '听到的词是什么意思？',
        options: ['晚上好', '你好', '再见', '早上好'],
        correctAnswer: '早上好',
        difficulty: 1,
      },
      {
        id: 'sh-lm-06',
        audioText: '饭店',
        question: '听到的词是什么意思？',
        options: ['酒店', '医院', '机场', '车站'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'sh-lm-07',
        audioText: '几钿',
        question: '听到的句子是什么意思？',
        options: ['几点了', '在哪里', '多少钱', '这是什么'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'sh-lm-08',
        audioText: '开会',
        question: '听到的词是什么意思？',
        options: ['聚会', '课程', '会议', '宴会'],
        correctAnswer: '会议',
        difficulty: 2,
      },
    ],
    word: [
      {
        id: 'sh-lw-01',
        audioText: '侬好 (nong2 hao3)',
        question: '听到的词是哪个？',
        options: ['侬好 (nong2 hao3)', '谢谢 (xia4 xia4)', '再会 (ze5 hui4)', '您好 (ning2 hao3)'],
        correctAnswer: '侬好 (nong2 hao3)',
        difficulty: 1,
      },
      {
        id: 'sh-lw-02',
        audioText: '谢谢 (xia4 xia4)',
        question: '听到的词是哪个？',
        options: ['多谢 (du1 xia4)', '对勿起 (de5 veh4 qi3)', '感谢 (ge3 xia4)', '谢谢 (xia4 xia4)'],
        correctAnswer: '谢谢 (xia4 xia4)',
        difficulty: 1,
      },
      {
        id: 'sh-lw-03',
        audioText: '苹果 (bing1 gu2)',
        question: '听到的词是哪个？',
        options: ['橙子 (cen2 zy3)', '香蕉 (xia1 jiao1)', '葡萄 (bu2 dao2)', '苹果 (bing1 gu2)'],
        correctAnswer: '苹果 (bing1 gu2)',
        difficulty: 1,
      },
      {
        id: 'sh-lw-04',
        audioText: '早安 (zao5 oe1)',
        question: '听到的词是哪个？',
        options: ['早安 (zao5 oe1)', '日安 (nyih8 oe1)', '晚安 (oe1 oe1)', '再会 (ze5 hui4)'],
        correctAnswer: '早安 (zao5 oe1)',
        difficulty: 1,
      },
      {
        id: 'sh-lw-05',
        audioText: '饭店 (ve5 di3)',
        question: '听到的词是哪个？',
        options: ['车站 (co1 ze3)', '医院 (yi1 yoe3)', '宾馆 (pin1 kuoe3)', '饭店 (ve5 di3)'],
        correctAnswer: '饭店 (ve5 di3)',
        difficulty: 2,
      },
      {
        id: 'sh-lw-06',
        audioText: '机场 (ji1 zan3)',
        question: '听到的词是哪个？',
        options: ['码头 (ma2 deu3)', '机场 (ji1 zan3)', '火车站 (hu3 co1 ze3)', '街市 (ka1 zy3)'],
        correctAnswer: '机场 (ji1 zan3)',
        difficulty: 2,
      },
      {
        id: 'sh-lw-07',
        audioText: '订位 (din4 vi4)',
        question: '听到的词是哪个？',
        options: ['订票 (din4 piao4)', '订餐 (din4 ce3)', '订位 (din4 vi4)', '订货 (din4 hu4)'],
        correctAnswer: '订位 (din4 vi4)',
        difficulty: 2,
      },
      {
        id: 'sh-lw-08',
        audioText: '面试 (mi4 sy4)',
        question: '听到的词是哪个？',
        options: ['面试 (mi4 sy4)', '商谈 (sau1 de3)', '会议 (we4 nyi4)', '面谈 (mi4 de3)'],
        correctAnswer: '面试 (mi4 sy4)',
        difficulty: 3,
      },
    ],
  },
  hak: {
    meaning: [
      {
        id: 'hak-lm-01',
        audioText: '你好',
        question: '听到的词是什么意思？',
        options: ['谢谢', '对不起', '你好', '再见'],
        correctAnswer: '你好',
        difficulty: 1,
      },
      {
        id: 'hak-lm-02',
        audioText: '多謝',
        question: '听到的词是什么意思？',
        options: ['对不起', '谢谢', '再见', '你好'],
        correctAnswer: '谢谢',
        difficulty: 1,
      },
      {
        id: 'hak-lm-03',
        audioText: '再會',
        question: '听到的词是什么意思？',
        options: ['你好', '谢谢', '再见', '早上好'],
        correctAnswer: '再见',
        difficulty: 1,
      },
      {
        id: 'hak-lm-04',
        audioText: '蘋果',
        question: '听到的词是什么意思？',
        options: ['橙子', '苹果', '香蕉', '葡萄'],
        correctAnswer: '苹果',
        difficulty: 1,
      },
      {
        id: 'hak-lm-05',
        audioText: '早安',
        question: '听到的词是什么意思？',
        options: ['再见', '晚上好', '早上好', '你好'],
        correctAnswer: '早上好',
        difficulty: 1,
      },
      {
        id: 'hak-lm-06',
        audioText: '飯店',
        question: '听到的词是什么意思？',
        options: ['机场', '医院', '酒店', '车站'],
        correctAnswer: '酒店',
        difficulty: 2,
      },
      {
        id: 'hak-lm-07',
        audioText: '幾多錢',
        question: '听到的句子是什么意思？',
        options: ['几点了', '在哪里', '这是什么', '多少钱'],
        correctAnswer: '多少钱',
        difficulty: 2,
      },
      {
        id: 'hak-lm-08',
        audioText: '開會',
        question: '听到的词是什么意思？',
        options: ['宴会', '会议', '课程', '聚会'],
        correctAnswer: '会议',
        difficulty: 2,
      },
    ],
    word: [
      {
        id: 'hak-lw-01',
        audioText: '你好 (ngi2 ho3)',
        question: '听到的词是哪个？',
        options: ['再會 (zai4 fi4)', '多謝 (do1 qia4)', '你好 (ngi2 ho3)', '您好 (ngin2 ho3)'],
        correctAnswer: '你好 (ngi2 ho3)',
        difficulty: 1,
      },
      {
        id: 'hak-lw-02',
        audioText: '多謝 (do1 qia4)',
        question: '听到的词是哪个？',
        options: ['對毋住 (dui4 m4 cu4)', '感謝 (gam3 qia4)', '多謝你 (do1 qia4 ngi2)', '多謝 (do1 qia4)'],
        correctAnswer: '多謝 (do1 qia4)',
        difficulty: 1,
      },
      {
        id: 'hak-lw-03',
        audioText: '蘋果 (pin2 go3)',
        question: '听到的词是哪个？',
        options: ['蘋果 (pin2 go3)', '葡萄 (pu2 to2)', '弓蕉 (giung1 jiau1)', '柑仔 (gam1 e3)'],
        correctAnswer: '蘋果 (pin2 go3)',
        difficulty: 1,
      },
      {
        id: 'hak-lw-04',
        audioText: '早安 (zau3 on1)',
        question: '听到的词是哪个？',
        options: ['日安 (ngit6 on1)', '早安 (zau3 on1)', '晚安 (van3 on1)', '再會 (zai4 fi4)'],
        correctAnswer: '早安 (zau3 on1)',
        difficulty: 1,
      },
      {
        id: 'hak-lw-05',
        audioText: '飯店 (fan4 diam4)',
        question: '听到的词是哪个？',
        options: ['車站 (ca1 zam4)', '賓館 (bin1 gon3)', '飯店 (fan4 diam4)', '醫院 (i1 yan4)'],
        correctAnswer: '飯店 (fan4 diam4)',
        difficulty: 2,
      },
      {
        id: 'hak-lw-06',
        audioText: '機場 (gi1 cong2)',
        question: '听到的词是哪个？',
        options: ['火車站 (fo3 ca1 zam4)', '機場 (gi1 cong2)', '碼頭 (ma2 teu2)', '街市 (gai1 sii4)'],
        correctAnswer: '機場 (gi1 cong2)',
        difficulty: 2,
      },
      {
        id: 'hak-lw-07',
        audioText: '訂位 (tin4 vi4)',
        question: '听到的词是哪个？',
        options: ['訂餐 (tin4 con1)', '訂票 (tin4 piau4)', '訂位 (tin4 vi4)', '訂貨 (tin4 fo4)'],
        correctAnswer: '訂位 (tin4 vi4)',
        difficulty: 2,
      },
      {
        id: 'hak-lw-08',
        audioText: '面試 (mien4 sii4)',
        question: '听到的词是哪个？',
        options: ['面試 (mien4 sii4)', '會議 (fi4 ngi4)', '商談 (song1 tam2)', '面談 (mien4 tam2)'],
        correctAnswer: '面試 (mien4 sii4)',
        difficulty: 3,
      },
    ],
  },
};

// Helper: get shuffled questions for a language
function getListeningQuestions(lang, type) {
  const data = LISTENING_DATA[lang];
  if (!data) return [];
  if (type === 'all') {
    const all = [...(data.meaning || []), ...(data.word || [])];
    return all.sort(() => Math.random() - 0.5);
  }
  return (data[type] || []).sort(() => Math.random() - 0.5);
}

Object.assign(window, { LISTENING_DATA, getListeningQuestions });
