// ========== Music / Song Data ==========
// Pre-built AI-original songs and lyrics for language learning

const SONG_LIBRARY = {
  en: [
    {
      id: 'en-song-1',
      title: 'Sunny Day Greeting',
      titleCn: '晴天问候',
      type: 'children',
      difficulty: 'beginner',
      description: 'A cheerful morning greeting song to start your day.',
      cover: '☀️',
      lyrics: [
        { text: 'Good morning, good morning, the sun is shining bright', highlight: [] },
        { text: 'Good morning, good morning, everything feels right', highlight: [] },
        { text: 'I say hello to the sky so blue', highlight: ['hello'] },
        { text: 'And wave to friends both old and new', highlight: ['friends'] },
        { text: 'Good morning, good morning, let\'s learn something new today', highlight: ['learn', 'new'] },
      ],
      fillBlanks: [
        { lineIndex: 2, blankIndex: 0, answer: 'hello', hint: 'h_llo' },
        { lineIndex: 3, blankIndex: 0, answer: 'friends', hint: 'fr__nds' },
        { lineIndex: 4, blankIndex: 0, answer: 'learn', hint: 'l__rn' },
      ],
      liaisons: [
        { lineIndex: 0, positions: [[0, 12]], note: 'good morning → goo(d) morning' },
        { lineIndex: 2, positions: [[2, 11]], note: 'say hello → say(y) hello' },
      ],
    },
    {
      id: 'en-song-2',
      title: 'Travel Song',
      titleCn: '旅行之歌',
      type: 'pop',
      difficulty: 'intermediate',
      description: 'A song about traveling and exploring new places.',
      cover: '🌍',
      lyrics: [
        { text: 'Pack your bags and grab your map', highlight: [] },
        { text: 'We\'re going on a trip, no time for a nap', highlight: [] },
        { text: 'The train is leaving at half past nine', highlight: ['train', 'leaving'] },
        { text: 'Adventure calls and the stars align', highlight: ['Adventure'] },
        { text: 'Every city has a story to tell', highlight: ['city', 'story'] },
        { text: 'With every hello, we break the shell', highlight: ['hello'] },
      ],
      fillBlanks: [
        { lineIndex: 2, blankIndex: 0, answer: 'train', hint: 'tr__n' },
        { lineIndex: 2, blankIndex: 1, answer: 'leaving', hint: 'l__ving' },
        { lineIndex: 4, blankIndex: 0, answer: 'city', hint: 'c_ty' },
      ],
      liaisons: [
        { lineIndex: 0, positions: [[0, 9]], note: 'pack your → pa(k) your' },
        { lineIndex: 5, positions: [[5, 16]], note: 'every hello → every(y) hello' },
      ],
    },
    {
      id: 'en-song-3',
      title: 'Daily Routine',
      titleCn: '日常 routine',
      type: 'children',
      difficulty: 'beginner',
      description: 'Learn daily activities with this catchy tune.',
      cover: '⏰',
      lyrics: [
        { text: 'Wake up, wake up, it\'s time to start the day', highlight: [] },
        { text: 'Brush your teeth and wash your face', highlight: ['Brush', 'teeth'] },
        { text: 'Eat your breakfast, don\'t be late', highlight: ['breakfast'] },
        { text: 'Off to school or work we go', highlight: ['school', 'work'] },
        { text: 'Learning, working, growing so', highlight: ['Learning', 'growing'] },
      ],
      fillBlanks: [
        { lineIndex: 1, blankIndex: 0, answer: 'Brush', hint: 'Br_sh' },
        { lineIndex: 1, blankIndex: 1, answer: 'teeth', hint: 't__th' },
        { lineIndex: 2, blankIndex: 0, answer: 'breakfast', hint: 'br__kf_st' },
      ],
      liaisons: [
        { lineIndex: 1, positions: [[0, 10]], note: 'brush your → brus(h) your' },
        { lineIndex: 2, positions: [[0, 8]], note: 'eat your → ea(t) your' },
      ],
    },
    {
      id: 'en-song-4',
      title: 'My Family',
      titleCn: '我的家',
      type: 'children',
      difficulty: 'beginner',
      description: 'A warm song about family members and love at home.',
      cover: '🏠',
      lyrics: [
        { text: 'This is my family, big and small', highlight: ['family'] },
        { text: 'We love each other, one and all', highlight: ['love'] },
        { text: 'My mother cooks and my father reads', highlight: ['mother', 'father'] },
        { text: 'My sister plays while my brother feeds', highlight: ['sister', 'brother'] },
        { text: 'Together we laugh and together we share', highlight: ['Together', 'share'] },
        { text: 'A family like ours is beyond compare', highlight: ['family'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'family', hint: 'f_m_l_' },
        { lineIndex: 2, blankIndex: 0, answer: 'mother', hint: 'm_th_r' },
        { lineIndex: 2, blankIndex: 1, answer: 'father', hint: 'f_th_r' },
        { lineIndex: 3, blankIndex: 0, answer: 'sister', hint: 's_st_r' },
      ],
      liaisons: [
        { lineIndex: 0, positions: [[8, 17]], note: 'my family → my(y) family' },
        { lineIndex: 2, positions: [[0, 9]], note: 'my mother → my(y) mother' },
        { lineIndex: 4, positions: [[9, 17]], note: 'we laugh → we(e) laugh' },
      ],
    },
    {
      id: 'en-song-5',
      title: 'Count with Me',
      titleCn: '一起数数',
      type: 'children',
      difficulty: 'beginner',
      description: 'A fun counting song from one to ten.',
      cover: '🔢',
      lyrics: [
        { text: 'One little finger, tap tap tap', highlight: ['One'] },
        { text: 'Two little feet go clap clap clap', highlight: ['Two'] },
        { text: 'Three little birds up in a tree', highlight: ['Three', 'birds'] },
        { text: 'Four little fish swimming in the sea', highlight: ['Four', 'fish'] },
        { text: 'Five little stars shining in the night', highlight: ['Five', 'stars'] },
        { text: 'Count with me, it will be all right', highlight: ['Count', 'right'] },
      ],
      fillBlanks: [
        { lineIndex: 2, blankIndex: 0, answer: 'Three', hint: 'Thr__' },
        { lineIndex: 2, blankIndex: 1, answer: 'birds', hint: 'b_rds' },
        { lineIndex: 4, blankIndex: 0, answer: 'Five', hint: 'F_v_' },
        { lineIndex: 5, blankIndex: 0, answer: 'Count', hint: 'C__nt' },
      ],
      liaisons: [
        { lineIndex: 0, positions: [[0, 10]], note: 'one little → one(e) little' },
        { lineIndex: 5, positions: [[6, 13]], note: 'with me → with(h) me' },
      ],
    },
    {
      id: 'en-song-6',
      title: 'Colors of the World',
      titleCn: '世界的颜色',
      type: 'children',
      difficulty: 'beginner',
      description: 'Learn color names with this bright and happy song.',
      cover: '🎨',
      lyrics: [
        { text: 'Red is the color of a juicy apple', highlight: ['Red'] },
        { text: 'Blue is the sky on a summer day', highlight: ['Blue'] },
        { text: 'Green are the leaves on the tallest tree', highlight: ['Green'] },
        { text: 'Yellow is the sun that lights our way', highlight: ['Yellow'] },
        { text: 'Colors all around, everywhere I see', highlight: ['Colors'] },
        { text: 'A rainbow of beauty for you and me', highlight: ['rainbow', 'beauty'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'Red', hint: 'R_d' },
        { lineIndex: 1, blankIndex: 0, answer: 'Blue', hint: 'Bl__' },
        { lineIndex: 2, blankIndex: 0, answer: 'Green', hint: 'Gr__n' },
        { lineIndex: 3, blankIndex: 0, answer: 'Yellow', hint: 'Y_ll_w' },
      ],
      liaisons: [
        { lineIndex: 0, positions: [[4, 10]], note: 'is the → is(s) the' },
        { lineIndex: 4, positions: [[7, 17]], note: 'all around → al(l) around' },
      ],
    },
    {
      id: 'en-song-7',
      title: 'Food Time',
      titleCn: '吃饭时间',
      type: 'children',
      difficulty: 'beginner',
      description: 'A yummy song about fruits, vegetables, and healthy eating.',
      cover: '🍎',
      lyrics: [
        { text: 'Apples and bananas, yummy yummy yum', highlight: ['Apples', 'bananas'] },
        { text: 'Carrots and potatoes, here they come', highlight: ['Carrots', 'potatoes'] },
        { text: 'Rice and noodles on my plate', highlight: ['Rice', 'noodles'] },
        { text: 'I love every bite, it tastes so great', highlight: ['love', 'great'] },
        { text: 'Drink some water, drink some juice', highlight: ['water', 'juice'] },
        { text: 'Healthy food gives us so much use', highlight: ['Healthy', 'food'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'Apples', hint: 'App__s' },
        { lineIndex: 0, blankIndex: 1, answer: 'bananas', hint: 'ban_n_s' },
        { lineIndex: 2, blankIndex: 0, answer: 'Rice', hint: 'R_c_' },
        { lineIndex: 4, blankIndex: 0, answer: 'water', hint: 'wat_r' },
      ],
      liaisons: [
        { lineIndex: 0, positions: [[7, 18]], note: 'and bananas → an(d) bananas' },
        { lineIndex: 3, positions: [[7, 17]], note: 'every bite → ever(y) bite' },
      ],
    },
    {
      id: 'en-song-8',
      title: 'Weather Watcher',
      titleCn: '天气观察员',
      type: 'children',
      difficulty: 'beginner',
      description: 'A song about different weather and what to wear.',
      cover: '🌈',
      lyrics: [
        { text: 'When the sun is shining, I wear my hat', highlight: ['sun', 'hat'] },
        { text: 'When the rain is falling, I grab my coat', highlight: ['rain', 'coat'] },
        { text: 'When the wind is blowing, I hold my kite', highlight: ['wind', 'kite'] },
        { text: 'When the snow is falling, it looks so white', highlight: ['snow', 'white'] },
        { text: 'Weather changes every single day', highlight: ['Weather'] },
        { text: 'Come outside and let us play', highlight: ['outside', 'play'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'sun', hint: 's_n' },
        { lineIndex: 1, blankIndex: 0, answer: 'rain', hint: 'r__n' },
        { lineIndex: 2, blankIndex: 0, answer: 'wind', hint: 'w__d' },
        { lineIndex: 4, blankIndex: 0, answer: 'Weather', hint: 'W__th_r' },
      ],
      liaisons: [
        { lineIndex: 0, positions: [[13, 23]], note: 'is shining → is(s) shining' },
        { lineIndex: 4, positions: [[8, 21]], note: 'changes every → changes(s) every' },
      ],
    },
  ],
  ja: [
    {
      id: 'ja-song-1',
      title: 'あさのうた',
      titleCn: '早晨之歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A simple Japanese morning song for beginners.',
      cover: '🌸',
      lyrics: [
        { text: 'おはよう　おはよう　あさがきたよ', highlight: [] },
        { text: 'とりたち　さえずり　そらがあおい', highlight: ['とりたち'] },
        { text: 'あたまを　あらって　はをみがこう', highlight: ['あたま', 'は'] },
        { text: 'あさごはん　たべて　がっこうへゆこう', highlight: ['あさごはん', 'がっこう'] },
      ],
      fillBlanks: [
        { lineIndex: 1, blankIndex: 0, answer: 'とりたち', hint: 'とり_ _' },
        { lineIndex: 2, blankIndex: 0, answer: 'あたま', hint: 'あ_ま' },
      ],
      liaisons: [],
    },
    {
      id: 'ja-song-2',
      title: 'かぞくのうた',
      titleCn: '家庭之歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A song about family members in Japanese. Practice family vocabulary.',
      cover: '👨‍👩‍👧‍👦',
      lyrics: [
        { text: 'おとうさん　おかあさん　だいすきだよ', highlight: ['おとうさん', 'おかあさん'] },
        { text: 'おにいちゃん　おねえちゃん　いっしょにあそぼ', highlight: ['おにいちゃん', 'おねえちゃん'] },
        { text: 'おとうと　いもうと　にっこりわらう', highlight: ['おとうと', 'いもうと'] },
        { text: 'かぞくみんな　しあわせです', highlight: ['かぞく', 'しあわせ'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'おとうさん', hint: 'おと_さん' },
        { lineIndex: 1, blankIndex: 0, answer: 'おにいちゃん', hint: 'おに_ちゃん' },
        { lineIndex: 2, blankIndex: 0, answer: 'おとうと', hint: 'おと_と' },
        { lineIndex: 3, blankIndex: 0, answer: 'かぞく', hint: 'か_く' },
      ],
      liaisons: [],
    },
    {
      id: 'ja-song-3',
      title: 'かずのうた',
      titleCn: '数字之歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'Learn Japanese numbers from one to five with this catchy song.',
      cover: '🔢',
      lyrics: [
        { text: 'いちに　さんし　ごのかぞえうた', highlight: ['いち', 'さん', 'ご'] },
        { text: 'ひとつ　ふたつ　みっつのりんご', highlight: ['ひとつ', 'ふたつ', 'りんご'] },
        { text: 'よっつ　いつつ　てをたたこう', highlight: ['よっつ', 'いつつ'] },
        { text: 'かずをおぼえて　げんきになろう', highlight: ['かず', 'げんき'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'いち', hint: 'い_　' },
        { lineIndex: 1, blankIndex: 0, answer: 'ひとつ', hint: 'ひ_つ' },
        { lineIndex: 1, blankIndex: 1, answer: 'りんご', hint: 'り_ご' },
        { lineIndex: 3, blankIndex: 0, answer: 'かず', hint: 'か_　' },
      ],
      liaisons: [],
    },
    {
      id: 'ja-song-4',
      title: 'しきのうた',
      titleCn: '四季之歌',
      type: 'children',
      difficulty: 'intermediate',
      description: 'A song about the four seasons in Japan.',
      cover: '🍁',
      lyrics: [
        { text: 'はるには　さくらが　さきます', highlight: ['はる', 'さくら'] },
        { text: 'なつには　うみへ　およぎにゆきます', highlight: ['なつ', 'うみ'] },
        { text: 'あきには　もみじが　あかくなります', highlight: ['あき', 'もみじ'] },
        { text: 'ふゆには　ゆきが　ふってきます', highlight: ['ふゆ', 'ゆき'] },
        { text: 'しきのうつりかわり　たのしいね', highlight: ['しき', 'たのしい'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'はる', hint: 'は_　' },
        { lineIndex: 1, blankIndex: 0, answer: 'なつ', hint: 'な_　' },
        { lineIndex: 2, blankIndex: 0, answer: 'あき', hint: 'あ_　' },
        { lineIndex: 3, blankIndex: 0, answer: 'ふゆ', hint: 'ふ_　' },
      ],
      liaisons: [],
    },
  ],
  ko: [
    {
      id: 'ko-song-1',
      title: '안녕 노래',
      titleCn: '问候歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Korean greeting song with romanization for pronunciation help.',
      cover: '👋',
      lyrics: [
        { text: '안녕하세요 친구들아 (annyeonghaseyo chingudeura)', highlight: ['안녕하세요'] },
        { text: '반가워요 모두들 (bangawoyo modeudeul)', highlight: ['반가워요'] },
        { text: '오늘도 함께 공부해요 (oneuldo hamkke gongbuhaeyo)', highlight: ['함께', '공부해요'] },
        { text: '즐거운 하루 볂내요 (jeulgeoun haru bonaeyo)', highlight: ['즐거운', '하루'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: '안녕하세요', hint: '안녕_ _요' },
        { lineIndex: 1, blankIndex: 0, answer: '반가워요', hint: '반가_요' },
        { lineIndex: 2, blankIndex: 0, answer: '함께', hint: '함_ _' },
      ],
      liaisons: [],
    },
    {
      id: 'ko-song-2',
      title: '나의 하루',
      titleCn: '我的一天',
      type: 'children',
      difficulty: 'beginner',
      description: 'A song about daily routines in Korean with romanization.',
      cover: '⏰',
      lyrics: [
        { text: '일곱 시에 일어나요 (ilgop sie ireonayo)', highlight: ['일어나요'] },
        { text: '이를 닦고 세수해요 (ireul dakgo sesuhaeyo)', highlight: ['이를', '세수해요'] },
        { text: '아침을 먹고 학교 가요 (achimeul meokgo hakgyo gayo)', highlight: ['아침을', '학교'] },
        { text: '책을 읽고 공부해요 (chaegueul ilggo gongbuhaeyo)', highlight: ['책을', '공부해요'] },
        { text: '밤이 오면 잠을 자요 (bami omyeon jameul jayo)', highlight: ['밤이', '잠을'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: '일어나요', hint: '일어나_' },
        { lineIndex: 2, blankIndex: 0, answer: '아침을', hint: '아침_　' },
        { lineIndex: 2, blankIndex: 1, answer: '학교', hint: '학_ _' },
        { lineIndex: 4, blankIndex: 0, answer: '잠을', hint: '잠_　' },
      ],
      liaisons: [],
    },
    {
      id: 'ko-song-3',
      title: '색깔 노래',
      titleCn: '颜色歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Korean colors song with romanization.',
      cover: '🌈',
      lyrics: [
        { text: '빨간색 사과 같아요 (ppalgansaek sagwa gatayo)', highlight: ['빨간색', '사과'] },
        { text: '파란색 하늘 같아요 (paransaek haneul gatayo)', highlight: ['파란색', '하늘'] },
        { text: '초록색 잔디 같아요 (choroksaek jandi gatayo)', highlight: ['초록색', '잔디'] },
        { text: '노란색 해바라기 같아요 (noransaek haebaragi gatayo)', highlight: ['노란색', '해바라기'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: '빨간색', hint: '빨간__' },
        { lineIndex: 1, blankIndex: 0, answer: '파란색', hint: '파란__' },
        { lineIndex: 2, blankIndex: 0, answer: '초록색', hint: '초록__' },
      ],
      liaisons: [],
    },
    {
      id: 'ko-song-4',
      title: '동물 노래',
      titleCn: '动物歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Korean animal song with romanization.',
      cover: '🐾',
      lyrics: [
        { text: '강아지는 멍멍 (gangajineun meongmeong)', highlight: ['강아지', '멍멍'] },
        { text: '고양이는 야옹 (goyangineun yaong)', highlight: ['고양이', '야옹'] },
        { text: '새들은 지저귀고 (saedeureun jjejeogwigo)', highlight: ['새들은'] },
        { text: '우리 모두 함께 노래해요 (uri modu hamkke noraehaeyo)', highlight: ['함께'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: '강아지', hint: '강아__' },
        { lineIndex: 1, blankIndex: 0, answer: '고양이', hint: '고양__' },
        { lineIndex: 2, blankIndex: 0, answer: '새들은', hint: '새__은' },
      ],
      liaisons: [],
    },

  ],
  "zh-CN": [
    {
      id: 'zh-CN-song-1',
      title: '春天来了',
      titleCn: 'Spring is Coming',
      type: 'children',
      difficulty: 'beginner',
      description: 'A cheerful song about spring and nature.',
      cover: '🌿',
      lyrics: [
        { text: '春天来了，花儿开了', highlight: ['春天', '花儿'] },
        { text: '小鸟唱歌，柳树摇啊摇', highlight: ['小鸟', '柳树'] },
        { text: '小朋友们，快出来玩', highlight: ['小朋友'] },
        { text: '阳光暖暖，心情真好', highlight: ['阳光', '心情'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: '春天', hint: '春_' },
        { lineIndex: 1, blankIndex: 0, answer: '小鸟', hint: '小_' },
      ],
      liaisons: [],
    },
    {
      id: 'zh-CN-song-2',
      title: '我的家',
      titleCn: 'My Family',
      type: 'children',
      difficulty: 'beginner',
      description: 'A song about family members in Chinese.',
      cover: '👨‍👩‍👧‍👦',
      lyrics: [
        { text: '爸爸工作，妈妈做饭', highlight: ['爸爸', '妈妈'] },
        { text: '姐姐画画，弟弟玩球', highlight: ['姐姐', '弟弟'] },
        { text: '爷爷奶奶，一起散步', highlight: ['爷爷', '奶奶'] },
        { text: '我们全家，幸福长久', highlight: ['全家', '幸福'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: '爸爸', hint: '爸_' },
        { lineIndex: 0, blankIndex: 1, answer: '妈妈', hint: '妈_' },
        { lineIndex: 1, blankIndex: 0, answer: '姐姐', hint: '姐_' },
        { lineIndex: 3, blankIndex: 0, answer: '全家', hint: '全_' },
      ],
      liaisons: [],
    },
    {
      id: 'zh-CN-song-3',
      title: '数字歌',
      titleCn: 'Number Song',
      type: 'children',
      difficulty: 'beginner',
      description: 'Learn Chinese numbers from one to five.',
      cover: '🔢',
      lyrics: [
        { text: '一二三四五，上山打老虎', highlight: ['一', '二', '三', '四', '五'] },
        { text: '老虎没打着，打到小松鼠', highlight: ['老虎', '松鼠'] },
        { text: '松鼠有几只，让我数一数', highlight: ['松鼠', '数一数'] },
        { text: '数来又数去，一二三四五', highlight: ['数来', '一二三四五'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: '一', hint: '一' },
        { lineIndex: 1, blankIndex: 0, answer: '老虎', hint: '老_' },
        { lineIndex: 2, blankIndex: 0, answer: '松鼠', hint: '松_' },
        { lineIndex: 2, blankIndex: 1, answer: '数一数', hint: '数一_ _' },
      ],
      liaisons: [],
    },
  ],
  es: [
    {
      id: 'es-song-1',
      title: 'Colores del Arcoíris',
      titleCn: '彩虹的颜色',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Spanish colors song for beginners.',
      cover: '🌈',
      lyrics: [
        { text: 'Rojo como una manzana', highlight: ['Rojo'] },
        { text: 'Azul como el cielo está', highlight: ['Azul'] },
        { text: 'Verde como la hierba', highlight: ['Verde'] },
        { text: 'Amarillo como el sol', highlight: ['Amarillo'] },
        { text: 'Colores por doquier', highlight: ['Colores'] },
        { text: 'Pinta tu mundo mejor', highlight: ['mundo'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'Rojo', hint: 'R_j_' },
        { lineIndex: 1, blankIndex: 0, answer: 'Azul', hint: 'Az_l' },
        { lineIndex: 2, blankIndex: 0, answer: 'Verde', hint: 'V_rd_' },
        { lineIndex: 3, blankIndex: 0, answer: 'Amarillo', hint: 'Am_r_ll_' },
      ],
      liaisons: [],
    },
    {
      id: 'es-song-2',
      title: 'Canción de los Animales',
      titleCn: '动物歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Spanish animal song for children.',
      cover: '🐾',
      lyrics: [
        { text: 'El perro dice guau guau', highlight: ['perro', 'guau'] },
        { text: 'El gato dice miau miau', highlight: ['gato', 'miau'] },
        { text: 'Los pájaros cantan fuerte', highlight: ['pájaros', 'cantan'] },
        { text: 'Todos juntos hacen concierto', highlight: ['Todos', 'juntos'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'perro', hint: 'p_rro' },
        { lineIndex: 1, blankIndex: 0, answer: 'gato', hint: 'g_t_' },
        { lineIndex: 2, blankIndex: 0, answer: 'pájaros', hint: 'páj_ros' },
      ],
      liaisons: [
        { lineIndex: 0, positions: [[0,8]], note: 'el perro → e(l) perro' },
      ],
    },

  ],
  ru: [
    {
      id: 'ru-song-1',
      title: 'Привет и Пока',
      titleCn: '你好再见',
      type: 'children',
      difficulty: 'beginner',
      description: 'A simple Russian greeting song with romanization.',
      cover: '🎵',
      lyrics: [
        { text: 'Привет, привет, как дела? (Privet, privet, kak dela?)', highlight: ['Привет'] },
        { text: 'Я рад тебя видеть (Ya rad tebya videt)', highlight: ['рад'] },
        { text: 'Давай учиться вместе (Davay uchitsya vmeste)', highlight: ['учиться', 'вместе'] },
        { text: 'Пока, пока, до завтра (Poka, poka, do zavtra)', highlight: ['Пока', 'завтра'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'Привет', hint: 'Пр_в_т' },
        { lineIndex: 2, blankIndex: 0, answer: 'учиться', hint: 'уч_t_s_я' },
        { lineIndex: 3, blankIndex: 0, answer: 'Пока', hint: 'П_к_' },
      ],
      liaisons: [],
    },
    {
      id: 'ru-song-2',
      title: 'Песня о Цветах',
      titleCn: '颜色歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Russian colors song with romanization.',
      cover: '🌈',
      lyrics: [
        { text: 'Красный как яблоко (Krasnyy kak yabloko)', highlight: ['Красный', 'яблоко'] },
        { text: 'Синий как небо (Siniy kak nebo)', highlight: ['Синий', 'небо'] },
        { text: 'Зелёный как трава (Zelyonyy kak trava)', highlight: ['Зелёный', 'трава'] },
        { text: 'Жёлтый как солнце (Zhyoltyy kak solntse)', highlight: ['Жёлтый', 'солнце'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'Красный', hint: 'Кр__ный' },
        { lineIndex: 1, blankIndex: 0, answer: 'Синий', hint: 'С__ний' },
        { lineIndex: 2, blankIndex: 0, answer: 'Зелёный', hint: 'Зел__ный' },
      ],
      liaisons: [],
    },

  ],
  yue: [
    {
      id: 'yue-song-1',
      title: '我嘅一日',
      titleCn: '我的一天',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Cantonese daily routine song with romanization.',
      cover: '🌅',
      lyrics: [
        { text: '朝早起身刷牙仔 (ziu1 zou2 hei2 san1 caat3 ngaa4 zai2)', highlight: ['朝早', '起身'] },
        { text: '食咗早餐返學堂 (sik6 zo2 zou2 caan1 faan1 hok6 tong4)', highlight: ['早餐', '返學堂'] },
        { text: '上堂讀書好專心 (soeng5 tong4 duk6 syu1 hou2 zyun1 sam1)', highlight: ['讀書', '專心'] },
        { text: '放咗學同朋友玩 (fong3 zo2 hok6 tung4 pang4 jau5 waan2)', highlight: ['放咗學', '朋友'] },
        { text: '夜晚瞓覺發個夢 (je6 maan5 fan3 gaau3 faat3 go3 mung6)', highlight: ['夜晚', '瞓覺'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: '朝早', hint: '朝_' },
        { lineIndex: 1, blankIndex: 0, answer: '早餐', hint: '早_' },
        { lineIndex: 2, blankIndex: 0, answer: '讀書', hint: '讀_' },
        { lineIndex: 4, blankIndex: 0, answer: '夜晚', hint: '夜_' },
      ],
      liaisons: [],
    },
    {
      id: 'yue-song-2',
      title: '顏色歌',
      titleCn: '颜色歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Cantonese colors song with romanization.',
      cover: '🌈',
      lyrics: [
        { text: '紅色似蘋果 (hung4 sik1 ci5 ping4 gwo2)', highlight: ['紅色', '蘋果'] },
        { text: '藍色似天空 (laam4 sik1 ci5 tin1 hung1)', highlight: ['藍色', '天空'] },
        { text: '綠色似草地 (luk6 sik1 ci5 cou2 dei6)', highlight: ['綠色', '草地'] },
        { text: '黃色似太陽 (wong4 sik1 ci5 taai3 joeng4)', highlight: ['黃色', '太陽'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: '紅色', hint: '紅__' },
        { lineIndex: 1, blankIndex: 0, answer: '藍色', hint: '藍__' },
        { lineIndex: 2, blankIndex: 0, answer: '綠色', hint: '綠__' },
      ],
      liaisons: [],
    },

  ],
  de: [
    {
      id: 'de-song-1',
      title: 'Guten Tag Lied',
      titleCn: '问候歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A German greeting song for beginners.',
      cover: '👋',
      lyrics: [
        { text: 'Guten Tag, guten Tag, wie geht es dir?', highlight: [] },
        { text: 'Guten Morgen, guten Morgen, ich freue mich', highlight: [] },
        { text: 'Hallo Freunde, kommt und spielt', highlight: ['Freunde'] },
        { text: 'Lernen wir zusammen, es macht viel Spaß', highlight: ['zusammen', 'Spaß'] },
      ],
      fillBlanks: [
        { lineIndex: 2, blankIndex: 0, answer: 'Freunde', hint: 'Fr__nde' },
        { lineIndex: 3, blankIndex: 0, answer: 'zusammen', hint: 'zus__mmen' },
        { lineIndex: 3, blankIndex: 1, answer: 'Spaß', hint: 'Sp__' },
      ],
      liaisons: [
        { lineIndex: 0, positions: [[0,9]], note: 'guten tag → gu(ten) tag' },
      ],
    },
    {
      id: 'de-song-2',
      title: 'Zahlenlied',
      titleCn: '数字歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'Learn German numbers from one to five.',
      cover: '🔢',
      lyrics: [
        { text: 'Eins und zwei und drei und vier', highlight: ['Eins', 'zwei', 'drei', 'vier'] },
        { text: 'Fünf kleine Enten schwimmen hier', highlight: ['Fünf', 'Enten'] },
        { text: 'Zählen wir laut von eins bis zehn', highlight: ['Zählen'] },
        { text: 'Deutsch lernen macht uns allen froh', highlight: ['Deutsch', 'froh'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'Eins', hint: 'E_ns' },
        { lineIndex: 1, blankIndex: 0, answer: 'Fünf', hint: 'F__f' },
        { lineIndex: 2, blankIndex: 0, answer: 'Zählen', hint: 'Z__len' },
      ],
      liaisons: [
        { lineIndex: 0, positions: [[0, 8]], note: 'eins und → ein(s) und' },
      ],
    },
  ],
  fr: [
    {
      id: 'fr-song-1',
      title: 'Chanson des Couleurs',
      titleCn: '颜色歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A French colors song for beginners.',
      cover: '🌈',
      lyrics: [
        { text: 'Le rouge comme une rose', highlight: ['rouge', 'rose'] },
        { text: 'Le bleu comme le ciel là-haut', highlight: ['bleu', 'ciel'] },
        { text: 'Le vert comme l\'herbe du jardin', highlight: ['vert', 'herbe'] },
        { text: 'Le jaune comme le soleil si beau', highlight: ['jaune', 'soleil'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'rouge', hint: 'r__ge' },
        { lineIndex: 1, blankIndex: 0, answer: 'bleu', hint: 'bl__' },
        { lineIndex: 2, blankIndex: 0, answer: 'vert', hint: 'v__t' },
        { lineIndex: 3, blankIndex: 0, answer: 'jaune', hint: 'j__ne' },
      ],
      liaisons: [
        { lineIndex: 0, positions: [[0,8]], note: 'le rouge → l(e) rouge' },
      ],
    },
    {
      id: 'fr-song-2',
      title: 'Bonjour les Amis',
      titleCn: '朋友们好',
      type: 'children',
      difficulty: 'beginner',
      description: 'A French greeting song for children.',
      cover: '🌸',
      lyrics: [
        { text: 'Bonjour, bonjour, comment ça va?', highlight: ['Bonjour'] },
        { text: 'Je suis content de te voir là', highlight: ['content'] },
        { text: 'Les amis s\'amusent tous ensemble', highlight: ['amis', 'ensemble'] },
        { text: 'Apprenons le français, c\'est si simple', highlight: ['français'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'Bonjour', hint: 'B__jour' },
        { lineIndex: 1, blankIndex: 0, answer: 'content', hint: 'c__tent' },
        { lineIndex: 2, blankIndex: 0, answer: 'amis', hint: 'a__s' },
      ],
      liaisons: [
        { lineIndex: 0, positions: [[0,16]], note: 'bonjour, bonjour → bonjour(r) bonjour' },
      ],
    },
  ],
  it: [
    {
      id: 'it-song-1',
      title: 'Canzone dei Numeri',
      titleCn: '数字歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'Learn Italian numbers with this fun song.',
      cover: '🔢',
      lyrics: [
        { text: 'Uno, due, tre, quattro, cinque', highlight: ['Uno', 'due', 'tre', 'quattro', 'cinque'] },
        { text: 'Contiamo insieme, non ci stanchiamo', highlight: ['insieme'] },
        { text: 'Sei, sette, otto, nove, dieci', highlight: [] },
        { text: 'L\'italiano è bello, lo impariamo qui', highlight: ['italiano'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'Uno', hint: 'U__' },
        { lineIndex: 0, blankIndex: 1, answer: 'tre', hint: 't__' },
        { lineIndex: 3, blankIndex: 0, answer: 'italiano', hint: 'it____no' },
      ],
      liaisons: [
        { lineIndex: 1, positions: [[9, 21]], note: 'insieme, non → insieme(e) non' },
      ],
    },
    {
      id: 'it-song-2',
      title: 'Ciao Amici',
      titleCn: '你好朋友',
      type: 'children',
      difficulty: 'beginner',
      description: 'An Italian greeting song for beginners.',
      cover: '👋',
      lyrics: [
        { text: 'Ciao, ciao, come stai oggi?', highlight: ['Ciao'] },
        { text: 'Bene, bene, grazie a te', highlight: ['Bene', 'grazie'] },
        { text: 'Giochiamo insieme tutti quanti', highlight: ['insieme'] },
        { text: 'L\'amicizia è un tesoro vero', highlight: ['amicizia', 'tesoro'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'Ciao', hint: 'C__' },
        { lineIndex: 1, blankIndex: 0, answer: 'Bene', hint: 'B__e' },
        { lineIndex: 1, blankIndex: 1, answer: 'grazie', hint: 'gr___e' },
      ],
      liaisons: [
        { lineIndex: 0, positions: [[0,10]], note: 'ciao, ciao → ciao(o) ciao' },
      ],
    },
  ],
  pt: [
    {
      id: 'pt-song-1',
      title: 'Canção das Cores',
      titleCn: '颜色歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Portuguese colors song for beginners.',
      cover: '🌈',
      lyrics: [
        { text: 'Vermelho como um coração', highlight: ['Vermelho', 'coração'] },
        { text: 'Azul como o mar sem fim', highlight: ['Azul', 'mar'] },
        { text: 'Verde como a floresta', highlight: ['Verde', 'floresta'] },
        { text: 'Amarelo como o sol pra mim', highlight: ['Amarelo', 'sol'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'Vermelho', hint: 'Verm_lh_' },
        { lineIndex: 1, blankIndex: 0, answer: 'Azul', hint: 'Az_l' },
        { lineIndex: 2, blankIndex: 0, answer: 'Verde', hint: 'V__de' },
      ],
      liaisons: [
        { lineIndex: 0, positions: [[0, 13]], note: 'vermelho como → vermelho(o) como' },
      ],
    },
    {
      id: 'pt-song-2',
      title: 'Olá Amigos',
      titleCn: '朋友们好',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Portuguese greeting song.',
      cover: '👋',
      lyrics: [
        { text: 'Olá, olá, como vai você?', highlight: ['Olá'] },
        { text: 'Bom dia, bom dia, prazer em conhecer', highlight: ['Bom', 'dia', 'prazer'] },
        { text: 'Vamos brincar e aprender juntos', highlight: ['aprender', 'juntos'] },
        { text: 'O português é divertido demais', highlight: ['português'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'Olá', hint: 'Ol_' },
        { lineIndex: 1, blankIndex: 0, answer: 'Bom', hint: 'B__' },
        { lineIndex: 2, blankIndex: 0, answer: 'aprender', hint: 'apr__der' },
      ],
      liaisons: [
        { lineIndex: 0, positions: [[0, 8]], note: 'olá, olá → olá(á) olá' },
      ],
    },
  ],
  ar: [
    {
      id: 'ar-song-1',
      title: 'أغنية التحية',
      titleCn: '问候歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'An Arabic greeting song with romanization.',
      cover: '👋',
      lyrics: [
        { text: 'مرحباً، مرحباً، كيف حالك؟ (Marhaban, marhaban, kayfa halak?)', highlight: [] },
        { text: 'صباح الخير، يوم جميل (Sabah al-khayr, yawm jamil)', highlight: ['صباح', 'يوم'] },
        { text: 'أصدقاء نلعب معاً (Asdiqa nalaab maaan)', highlight: ['أصدقاء'] },
        { text: 'نتعلم العربية بسعادة (Nataallam al-arabiyya bisaaada)', highlight: ['عربية'] },
      ],
      fillBlanks: [
        { lineIndex: 1, blankIndex: 0, answer: 'صباح', hint: 'ص__ح' },
        { lineIndex: 2, blankIndex: 0, answer: 'أصدقاء', hint: 'أص___ء' },
        { lineIndex: 3, blankIndex: 0, answer: 'عربية', hint: 'ع__ية' },
      ],
      liaisons: [],
    },
    {
      id: 'ar-song-2',
      title: 'أغنية الألوان',
      titleCn: '颜色歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'An Arabic colors song with romanization.',
      cover: '🌈',
      lyrics: [
        { text: 'أحمر مثل التفاح (Ahmar mithl al-tuffah)', highlight: ['أحمر', 'التفاح'] },
        { text: 'أزرق مثل السماء (Azraq mithl al-sama)', highlight: ['أزرق', 'السماء'] },
        { text: 'أخضر مثل العشب (Akhdar mithl al-ashab)', highlight: ['أخضر', 'العشب'] },
        { text: 'أصفر مثل الشمس (Asfar mithl al-shams)', highlight: ['أصفر', 'الشمس'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'أحمر', hint: 'أح__' },
        { lineIndex: 1, blankIndex: 0, answer: 'أزرق', hint: 'أز__ق' },
        { lineIndex: 2, blankIndex: 0, answer: 'أخضر', hint: 'أخ__ر' },
      ],
      liaisons: [],
    },
  ],
  hi: [
    {
      id: 'hi-song-1',
      title: 'नमस्ते गीत',
      titleCn: '问候歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Hindi greeting song with romanization.',
      cover: '👋',
      lyrics: [
        { text: 'नमस्ते, नमस्ते, कैसे हो? (Namaste, namaste, kaise ho?)', highlight: [] },
        { text: 'सुप्रभात, सुप्रभात, मौसम अच्छा है (Suprabhaat, suprabhaat, mausam achha hai)', highlight: ['सुप्रभात', 'मौसम'] },
        { text: 'दोस्तों के साथ खेलेंगे (Doston ke saath khelenge)', highlight: ['दोस्तों'] },
        { text: 'हिंदी सीखेंगे, मज़ा आएगा (Hindi seekhenge, mazaa aayega)', highlight: ['हिंदी'] },
      ],
      fillBlanks: [
        { lineIndex: 1, blankIndex: 0, answer: 'सुप्रभात', hint: 'सु___भात' },
        { lineIndex: 2, blankIndex: 0, answer: 'दोस्तों', hint: 'दो___ों' },
        { lineIndex: 3, blankIndex: 0, answer: 'हिंदी', hint: 'हि___' },
      ],
      liaisons: [],
    },
    {
      id: 'hi-song-2',
      title: 'रंगों की गीत',
      titleCn: '颜色歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Hindi colors song with romanization.',
      cover: '🌈',
      lyrics: [
        { text: 'लाल सेब जैसा (Laal seb jaisa)', highlight: ['लाल', 'सेब'] },
        { text: 'नीला आकाश जैसा (Neela aakaash jaisa)', highlight: ['नीला', 'आकाश'] },
        { text: 'हरा घास जैसा (Hara ghaas jaisa)', highlight: ['हरा', 'घास'] },
        { text: 'पीला सूरज जैसा (Peela sooraj jaisa)', highlight: ['पीला', 'सूरज'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'लाल', hint: 'ला__' },
        { lineIndex: 1, blankIndex: 0, answer: 'नीला', hint: 'नी__' },
        { lineIndex: 2, blankIndex: 0, answer: 'हरा', hint: 'ह__' },
      ],
      liaisons: [],
    },
  ],
  th: [
    {
      id: 'th-song-1',
      title: 'เพลงทักทาย',
      titleCn: '问候歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Thai greeting song with romanization.',
      cover: '👋',
      lyrics: [
        { text: 'สวัสดี สวัสดี สบายดีไหม (sawatdee sawatdee sabaidee mai)', highlight: [] },
        { text: 'อรุณสวัสดิ์ อรุณสวัสดิ์ วันนี้สดใส (arun sawat arun sawat wan ni sot sai)', highlight: ['อรุณสวัสดิ์'] },
        { text: 'เพื่อนๆ เล่นด้วยกัน (phueng phueng len duai kan)', highlight: ['เพื่อนๆ'] },
        { text: 'เรียนภาษาไทย สนุกมาก (rian phasa thai sanuk mak)', highlight: ['ภาษาไทย'] },
      ],
      fillBlanks: [
        { lineIndex: 1, blankIndex: 0, answer: 'อรุณสวัสดิ์', hint: 'อรุณส___ดิ์' },
        { lineIndex: 2, blankIndex: 0, answer: 'เพื่อนๆ', hint: 'เพ__นๆ' },
        { lineIndex: 3, blankIndex: 0, answer: 'ภาษาไทย', hint: 'ภ__ษาไทย' },
      ],
      liaisons: [],
    },
    {
      id: 'th-song-2',
      title: 'เพลงสี',
      titleCn: '颜色歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Thai colors song with romanization.',
      cover: '🌈',
      lyrics: [
        { text: 'แดงเหมือนแอปเปิ้ล (daeng muean apple)', highlight: ['แดง', 'แอปเปิ้ล'] },
        { text: 'ฟ้าเหมือนท้องฟ้า (faa muean thong faa)', highlight: ['ฟ้า', 'ท้องฟ้า'] },
        { text: 'เขียวเหมือนหญ้า (khiao muean yaa)', highlight: ['เขียว', 'หญ้า'] },
        { text: 'เหลืองเหมือนพระอาทิตย์ (lueang muean phra athit)', highlight: ['เหลือง', 'พระอาทิตย์'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'แดง', hint: 'แ__ง' },
        { lineIndex: 1, blankIndex: 0, answer: 'ฟ้า', hint: 'ฟ__' },
        { lineIndex: 2, blankIndex: 0, answer: 'เขียว', hint: 'เ__ยว' },
      ],
      liaisons: [],
    },
  ],
  vi: [
    {
      id: 'vi-song-1',
      title: 'Bài Chào Hỏi',
      titleCn: '问候歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Vietnamese greeting song.',
      cover: '👋',
      lyrics: [
        { text: 'Xin chào, xin chào, bạn khỏe không?', highlight: ['Xin', 'chào'] },
        { text: 'Chào buổi sáng, trời thật đẹp', highlight: ['buổi', 'sáng'] },
        { text: 'Bạn bè cùng nhau vui chơi', highlight: ['Bạn', 'bè'] },
        { text: 'Học tiếng Việt, thật là vui', highlight: ['tiếng', 'Việt'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'chào', hint: 'ch__' },
        { lineIndex: 1, blankIndex: 0, answer: 'sáng', hint: 's__ng' },
        { lineIndex: 2, blankIndex: 0, answer: 'Bạn', hint: 'B__' },
      ],
      liaisons: [
        { lineIndex: 0, positions: [[0,8]], note: 'xin chào → xi(n) chào' },
      ],
    },
    {
      id: 'vi-song-2',
      title: 'Bài Hát Màu Sắc',
      titleCn: '颜色歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Vietnamese colors song.',
      cover: '🌈',
      lyrics: [
        { text: 'Màu đỏ như trái táo', highlight: ['đỏ', 'táo'] },
        { text: 'Màu xanh như bầu trời', highlight: ['xanh', 'trời'] },
        { text: 'Màu xanh lá như cỏ', highlight: ['xanh', 'lá'] },
        { text: 'Màu vàng như mặt trời', highlight: ['vàng', 'trời'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'đỏ', hint: 'đ_' },
        { lineIndex: 1, blankIndex: 0, answer: 'xanh', hint: 'x__h' },
        { lineIndex: 3, blankIndex: 0, answer: 'vàng', hint: 'v__ng' },
      ],
      liaisons: [],
    },
  ],
  tr: [
    {
      id: 'tr-song-1',
      title: 'Selam Şarkısı',
      titleCn: '问候歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Turkish greeting song.',
      cover: '👋',
      lyrics: [
        { text: 'Merhaba, merhaba, nasılsın?', highlight: ['Merhaba'] },
        { text: 'Günaydın, günaydın, hava güzel', highlight: ['Günaydın', 'güzel'] },
        { text: 'Arkadaşlarla oynayalım', highlight: ['Arkadaşlarla'] },
        { text: 'Türkçe öğrenelim, çok eğlenceli', highlight: ['Türkçe'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'Merhaba', hint: 'Mer___a' },
        { lineIndex: 1, blankIndex: 0, answer: 'Günaydın', hint: 'Gün___ın' },
        { lineIndex: 2, blankIndex: 0, answer: 'Arkadaşlarla', hint: 'Arka_____la' },
      ],
      liaisons: [
        { lineIndex: 0, positions: [[0,16]], note: 'merhaba, merhaba → merhaba(a) merhaba' },
      ],
    },
    {
      id: 'tr-song-2',
      title: 'Renkler Şarkısı',
      titleCn: '颜色歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Turkish colors song.',
      cover: '🌈',
      lyrics: [
        { text: 'Kırmızı gibi elma', highlight: ['Kırmızı', 'elma'] },
        { text: 'Mavi gibi gökyüzü', highlight: ['Mavi', 'gökyüzü'] },
        { text: 'Yeşil gibi çimen', highlight: ['Yeşil', 'çimen'] },
        { text: 'Sarı gibi güneş', highlight: ['Sarı', 'güneş'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'Kırmızı', hint: 'K_rm_z_' },
        { lineIndex: 1, blankIndex: 0, answer: 'Mavi', hint: 'M_v_' },
        { lineIndex: 2, blankIndex: 0, answer: 'Yeşil', hint: 'Y__il' },
      ],
      liaisons: [],
    },
  ],
  pl: [
    {
      id: 'pl-song-1',
      title: 'Piosenka Powitalna',
      titleCn: '问候歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Polish greeting song.',
      cover: '👋',
      lyrics: [
        { text: 'Cześć, cześć, jak się masz?', highlight: ['Cześć'] },
        { text: 'Dzień dobry, dzień dobry, piękna pogoda', highlight: ['Dzień', 'dobry'] },
        { text: 'Z przyjaciółmi bawimy się razem', highlight: ['przyjaciółmi'] },
        { text: 'Uczymy się polskiego, to świetna zabawa', highlight: ['polskiego'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'Cześć', hint: 'Cz__ś' },
        { lineIndex: 1, blankIndex: 0, answer: 'Dzień', hint: 'Dz__ń' },
        { lineIndex: 2, blankIndex: 0, answer: 'przyjaciółmi', hint: 'przy____mi' },
      ],
      liaisons: [
        { lineIndex: 0, positions: [[0,12]], note: 'cześć, cześć → cześć(ć) cześć' },
      ],
    },
    {
      id: 'pl-song-2',
      title: 'Piosenka o Kolorach',
      titleCn: '颜色歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Polish colors song.',
      cover: '🌈',
      lyrics: [
        { text: 'Czerwony jak jabłko', highlight: ['Czerwony', 'jabłko'] },
        { text: 'Niebieski jak niebo', highlight: ['Niebieski', 'niebo'] },
        { text: 'Zielony jak trawa', highlight: ['Zielony', 'trawa'] },
        { text: 'Żółty jak słońce', highlight: ['Żółty', 'słońce'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'Czerwony', hint: 'Cz_rw_ny' },
        { lineIndex: 1, blankIndex: 0, answer: 'Niebieski', hint: 'Nieb__ski' },
        { lineIndex: 2, blankIndex: 0, answer: 'Zielony', hint: 'Zi__ny' },
      ],
      liaisons: [],
    },
  ],
  nl: [
    {
      id: 'nl-song-1',
      title: 'Groetjeslied',
      titleCn: '问候歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Dutch greeting song.',
      cover: '👋',
      lyrics: [
        { text: 'Hallo, hallo, hoe gaat het?', highlight: ['Hallo'] },
        { text: 'Goedemorgen, wat een mooie dag', highlight: ['Goedemorgen'] },
        { text: 'Met vrienden spelen we samen', highlight: ['vrienden'] },
        { text: 'Nederlands leren is zo leuk', highlight: ['Nederlands'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'Hallo', hint: 'Ha__o' },
        { lineIndex: 1, blankIndex: 0, answer: 'Goedemorgen', hint: 'Go___morgen' },
        { lineIndex: 2, blankIndex: 0, answer: 'vrienden', hint: 'vr___den' },
      ],
      liaisons: [
        { lineIndex: 0, positions: [[0, 12]], note: 'hallo, hallo → hallo(o) hallo' },
      ],
    },
    {
      id: 'nl-song-2',
      title: 'Kleurenlied',
      titleCn: '颜色歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Dutch colors song.',
      cover: '🌈',
      lyrics: [
        { text: 'Rood als een appel', highlight: ['Rood', 'appel'] },
        { text: 'Blauw als de lucht', highlight: ['Blauw', 'lucht'] },
        { text: 'Groen als het gras', highlight: ['Groen', 'gras'] },
        { text: 'Geel als de zon', highlight: ['Geel', 'zon'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'Rood', hint: 'R__d' },
        { lineIndex: 1, blankIndex: 0, answer: 'Blauw', hint: 'Bl__w' },
        { lineIndex: 2, blankIndex: 0, answer: 'Groen', hint: 'Gr__n' },
      ],
      liaisons: [],
    },
  ],
  el: [
    {
      id: 'el-song-1',
      title: 'Τραγούδι Χαιρετισμού',
      titleCn: '问候歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Greek greeting song with romanization.',
      cover: '👋',
      lyrics: [
        { text: 'Γεια σου, γεια σου, τι κάνεις? (Ya su, ya su, ti kanis?)', highlight: [] },
        { text: 'Καλημέρα, καλημέρα, όμορφη μέρα (Kalimera, kalimera, omorfi mera)', highlight: ['Καλημέρα', 'μέρα'] },
        { text: 'Με φίλους παίζουμε μαζί (Me filous pezoume mazi)', highlight: ['φίλους'] },
        { text: 'Μαθαίνουμε ελληνικά, χαρά (Mathainoume ellinika, hara)', highlight: ['ελληνικά'] },
      ],
      fillBlanks: [
        { lineIndex: 1, blankIndex: 0, answer: 'Καλημέρα', hint: 'Καλη__ρα' },
        { lineIndex: 2, blankIndex: 0, answer: 'φίλους', hint: 'φ__λους' },
        { lineIndex: 3, blankIndex: 0, answer: 'ελληνικά', hint: 'ελλ__νικά' },
      ],
      liaisons: [],
    },
    {
      id: 'el-song-2',
      title: 'Τραγούδι Χρωμάτων',
      titleCn: '颜色歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Greek colors song with romanization.',
      cover: '🌈',
      lyrics: [
        { text: 'Κόκκινο σαν μήλο (Kokino san milo)', highlight: ['Κόκκινο', 'μήλο'] },
        { text: 'Μπλε σαν τον ουρανό (Ble san ton ourano)', highlight: ['Μπλε', 'ουρανό'] },
        { text: 'Πράσινο σαν γρασίδι (Prasino san grasidi)', highlight: ['Πράσινο', 'γρασίδι'] },
        { text: 'Κίτρινο σαν τον ήλιο (Kitrino san ton ilio)', highlight: ['Κίτρινο', 'ήλιο'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: 'Κόκκινο', hint: 'Κ__κινο' },
        { lineIndex: 1, blankIndex: 0, answer: 'Μπλε', hint: 'Μ__ε' },
        { lineIndex: 2, blankIndex: 0, answer: 'Πράσινο', hint: 'Π__σινο' },
      ],
      liaisons: [],
    },
  ],
  nan: [
    {
      id: 'nan-song-1',
      title: '問候歌',
      titleCn: '问候歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Hokkien greeting song with POJ romanization.',
      cover: '👋',
      lyrics: [
        { text: '你好，你好，你食飽未？ (li-ho, li-ho, li tsia̍h-pá buē?)', highlight: [] },
        { text: '早安安，天氣真好 (tsá-uan-uan, thinn-khì tsin hó)', highlight: ['早安安', '天氣'] },
        { text: '朋友做伙來鬥陣 (pîng-iú tsò-hué lâi tàu-tīn)', highlight: ['朋友'] },
        { text: '學台語，誠歡喜 (o̍h tâi-gí, tsiânn hua-hi)', highlight: ['台語'] },
      ],
      fillBlanks: [
        { lineIndex: 1, blankIndex: 0, answer: '早安安', hint: '早__安' },
        { lineIndex: 2, blankIndex: 0, answer: '朋友', hint: '朋__' },
        { lineIndex: 3, blankIndex: 0, answer: '台語', hint: '台__' },
      ],
      liaisons: [],
    },
    {
      id: 'nan-song-2',
      title: '顏色歌',
      titleCn: '颜色歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Hokkien colors song with POJ romanization.',
      cover: '🌈',
      lyrics: [
        { text: '紅色親像蘋果 (âng-sik tshin-tshiūnn pîn-kó)', highlight: ['紅色', '蘋果'] },
        { text: '青色親像天 (tshenn-sik tshin-tshiūnn thinn)', highlight: ['青色', '天'] },
        { text: '綠色親像草 (li̍k-sik tshin-tshiūnn tsháu)', highlight: ['綠色', '草'] },
        { text: '黃色親像日頭 (n̂g-sik tshin-tshiūnn ji̍t-thâu)', highlight: ['黃色', '日頭'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: '紅色', hint: '紅__' },
        { lineIndex: 1, blankIndex: 0, answer: '青色', hint: '青__' },
        { lineIndex: 2, blankIndex: 0, answer: '綠色', hint: '綠__' },
      ],
      liaisons: [],
    },
  ],
  "zh-SC": [
    {
      id: 'zh-SC-song-1',
      title: '问候歌',
      titleCn: '问候歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Sichuan dialect greeting song.',
      cover: '👋',
      lyrics: [
        { text: '你好噻，你好噻，吃了没得？', highlight: ['你好噻'] },
        { text: '早上好，天气巴适', highlight: ['早上好', '巴适'] },
        { text: '朋友们一起耍', highlight: ['朋友们'] },
        { text: '学四川话，好安逸', highlight: ['四川话', '安逸'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: '你好噻', hint: '你__噻' },
        { lineIndex: 1, blankIndex: 0, answer: '巴适', hint: '巴__' },
        { lineIndex: 3, blankIndex: 0, answer: '四川话', hint: '四__话' },
      ],
      liaisons: [],
    },
    {
      id: 'zh-SC-song-2',
      title: '颜色歌',
      titleCn: '颜色歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Sichuan dialect colors song.',
      cover: '🌈',
      lyrics: [
        { text: '红颜色像苹果', highlight: ['红颜色', '苹果'] },
        { text: '蓝颜色像天空', highlight: ['蓝颜色', '天空'] },
        { text: '绿颜色像草草', highlight: ['绿颜色', '草草'] },
        { text: '黄颜色像太阳', highlight: ['黄颜色', '太阳'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: '红颜色', hint: '红__色' },
        { lineIndex: 1, blankIndex: 0, answer: '蓝颜色', hint: '蓝__色' },
        { lineIndex: 2, blankIndex: 0, answer: '绿颜色', hint: '绿__色' },
      ],
      liaisons: [],
    },
  ],
  "zh-DB": [
    {
      id: 'zh-DB-song-1',
      title: '问候歌',
      titleCn: '问候歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Northeast dialect greeting song.',
      cover: '👋',
      lyrics: [
        { text: '你好啊，你好啊，吃了吗？', highlight: ['你好啊'] },
        { text: '早上好，天气真不错', highlight: ['早上好', '不错'] },
        { text: '朋友们一起嗨', highlight: ['朋友们'] },
        { text: '学东北话，老带劲了', highlight: ['东北话', '带劲'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: '你好啊', hint: '你__啊' },
        { lineIndex: 1, blankIndex: 0, answer: '不错', hint: '不__' },
        { lineIndex: 3, blankIndex: 0, answer: '东北话', hint: '东__话' },
      ],
      liaisons: [],
    },
    {
      id: 'zh-DB-song-2',
      title: '颜色歌',
      titleCn: '颜色歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Northeast dialect colors song.',
      cover: '🌈',
      lyrics: [
        { text: '红彤彤的像苹果', highlight: ['红彤彤', '苹果'] },
        { text: '蓝哇哇的像天空', highlight: ['蓝哇哇', '天空'] },
        { text: '绿油油的像草地', highlight: ['绿油油', '草地'] },
        { text: '黄澄澄的像太阳', highlight: ['黄澄澄', '太阳'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: '红彤彤', hint: '红__彤' },
        { lineIndex: 1, blankIndex: 0, answer: '蓝哇哇', hint: '蓝__哇' },
        { lineIndex: 2, blankIndex: 0, answer: '绿油油', hint: '绿__油' },
      ],
      liaisons: [],
    },
  ],
  sh: [
    {
      id: 'sh-song-1',
      title: '问候歌',
      titleCn: '问候歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Shanghai dialect greeting song.',
      cover: '👋',
      lyrics: [
        { text: '侬好，侬好，饭吃过伐？', highlight: ['侬好'] },
        { text: '早向好，天气蛮好', highlight: ['早向好', '蛮好'] },
        { text: '朋友一道白相', highlight: ['朋友'] },
        { text: '学上海言话，老开心', highlight: ['上海言话', '开心'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: '侬好', hint: '侬__' },
        { lineIndex: 1, blankIndex: 0, answer: '蛮好', hint: '蛮__' },
        { lineIndex: 3, blankIndex: 0, answer: '上海言话', hint: '上__言话' },
      ],
      liaisons: [],
    },
    {
      id: 'sh-song-2',
      title: '颜色歌',
      titleCn: '颜色歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Shanghai dialect colors song.',
      cover: '🌈',
      lyrics: [
        { text: '红颜色像苹果', highlight: ['红颜色', '苹果'] },
        { text: '蓝颜色像天空', highlight: ['蓝颜色', '天空'] },
        { text: '绿颜色像草地', highlight: ['绿颜色', '草地'] },
        { text: '黄颜色像太阳', highlight: ['黄颜色', '太阳'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: '红颜色', hint: '红__色' },
        { lineIndex: 1, blankIndex: 0, answer: '蓝颜色', hint: '蓝__色' },
        { lineIndex: 2, blankIndex: 0, answer: '绿颜色', hint: '绿__色' },
      ],
      liaisons: [],
    },
  ],
  hak: [
    {
      id: 'hak-song-1',
      title: '問候歌',
      titleCn: '问候歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Hakka greeting song with romanization.',
      cover: '👋',
      lyrics: [
        { text: '你好，你好，食飽無？ (ngi ho, ngi ho, sit pau mo?)', highlight: [] },
        { text: '早辰好，天時幾好 (cho shin ho, thien shi ki ho)', highlight: ['早辰好', '天時'] },
        { text: '朋友共下來遊戲 (phien yu kiung ha loi yu hi)', highlight: ['朋友'] },
        { text: '學客家話，當歡喜 (hok hak ka fa, tong fon hi)', highlight: ['客家話'] },
      ],
      fillBlanks: [
        { lineIndex: 1, blankIndex: 0, answer: '早辰好', hint: '早__好' },
        { lineIndex: 2, blankIndex: 0, answer: '朋友', hint: '朋__' },
        { lineIndex: 3, blankIndex: 0, answer: '客家話', hint: '客__話' },
      ],
      liaisons: [],
    },
    {
      id: 'hak-song-2',
      title: '顏色歌',
      titleCn: '颜色歌',
      type: 'children',
      difficulty: 'beginner',
      description: 'A Hakka colors song with romanization.',
      cover: '🌈',
      lyrics: [
        { text: '紅色像蘋果 (fung sitt chhiong pin ko)', highlight: ['紅色', '蘋果'] },
        { text: '藍色像天空 (lam sitt chhiong thien khung)', highlight: ['藍色', '天空'] },
        { text: '綠色像草地 (liuk sitt chhiong chhau thi)', highlight: ['綠色', '草地'] },
        { text: '黃色像日頭 (vong sitt chhiong ngit theu)', highlight: ['黃色', '日頭'] },
      ],
      fillBlanks: [
        { lineIndex: 0, blankIndex: 0, answer: '紅色', hint: '紅__' },
        { lineIndex: 1, blankIndex: 0, answer: '藍色', hint: '藍__' },
        { lineIndex: 2, blankIndex: 0, answer: '綠色', hint: '綠__' },
      ],
      liaisons: [],
    },
  ],
};

function getSongs(language) {
  return SONG_LIBRARY[language] || SONG_LIBRARY['en'] || [];
}

Object.assign(window, { SONG_LIBRARY, getSongs });
