const NEW_QUIZ_DATA = {

  de: {
    themes: [
      {
        id: 'basic',
        name: '基础词汇',
        color: '#1E3A8A',
        levels: [
          {
            levelId: 'de-basic-01',
            title: '问候与礼貌',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: [],
            questions: [
              { id: 'de-b-01-1', type: 'translate', question: '你好', options: ['hallo', 'danke', 'ja', 'nein'], correctAnswer: 'hallo', difficulty: 1 },
              { id: 'de-b-01-2', type: 'translate', question: '谢谢', options: ['danke', 'bitte', 'ja', 'hallo'], correctAnswer: 'danke', difficulty: 1 },
              { id: 'de-b-01-3', type: 'fill-blank', question: '___ Morgen!（早上好）', options: ['Guten', 'Gute', 'Gut', 'Guter'], correctAnswer: 'Guten', difficulty: 2 },
              { id: 'de-b-01-4', type: 'match', question: '德语配对', pairs: [['hallo', '你好'], ['danke', '谢谢'], ['ja', '是'], ['nein', '不是']], correctAnswer: 'match', difficulty: 2 },
              { id: 'de-b-01-5', type: 'translate', question: '我爱你', options: ['ich liebe dich', 'danke schön', 'guten tag', 'auf wiedersehen'], correctAnswer: 'ich liebe dich', difficulty: 2 },
              { id: 'de-b-01-6', type: 'dictation', question: '听写：水', audioWord: 'wasser', correctAnswer: 'wasser', difficulty: 2 },
            ],
          },
          {
            levelId: 'de-basic-02',
            title: '数字与颜色',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: ['de-basic-01'],
            questions: [
              { id: 'de-b-02-1', type: 'translate', question: '红色', options: ['rot', 'blau', 'grün', 'gelb'], correctAnswer: 'rot', difficulty: 1 },
              { id: 'de-b-02-2', type: 'translate', question: '三', options: ['eins', 'zwei', 'drei', 'vier'], correctAnswer: 'drei', difficulty: 1 },
              { id: 'de-b-02-3', type: 'fill-blank', question: 'Das ist ___.（这是蓝色的）', options: ['rot', 'blau', 'grün', 'gelb'], correctAnswer: 'blau', difficulty: 1 },
              { id: 'de-b-02-4', type: 'match', question: '数字配对', pairs: [['eins', '一'], ['zwei', '二'], ['drei', '三'], ['vier', '四']], correctAnswer: 'match', difficulty: 2 },
              { id: 'de-b-02-5', type: 'translate', question: '绿色', options: ['rot', 'blau', 'grün', 'schwarz'], correctAnswer: 'grün', difficulty: 1 },
              { id: 'de-b-02-6', type: 'dictation', question: '听写：苹果', audioWord: 'apfel', correctAnswer: 'apfel', difficulty: 2 },
            ],
          },
        ],
      },
      {
        id: 'daily',
        name: '日常对话',
        color: '#3B82F6',
        levels: [
          {
            levelId: 'de-daily-01',
            title: '出行与问路',
            timeLimit: 150,
            minScoreFor1Star: 40,
            minScoreFor2Star: 60,
            minScoreFor3Star: 80,
            prerequisites: [],
            questions: [
              { id: 'de-d-01-1', type: 'translate', question: '洗手间在哪里？', options: ['Wo ist die Toilette?', 'Wie viel kostet das?', 'Wie spät ist es?', 'Wo wohnen Sie?'], correctAnswer: 'Wo ist die Toilette?', difficulty: 2 },
              { id: 'de-d-01-2', type: 'fill-blank', question: 'Nehmen Sie den ___ zum Bahnhof.（坐出租车去火车站）', options: ['Bus', 'Zug', 'Taxi', 'Flugzeug'], correctAnswer: 'Taxi', difficulty: 2 },
              { id: 'de-d-01-3', type: 'translate', question: '多少钱？', options: ['Wie viele?', 'Wie viel?', 'Wie lange?', 'Wie weit?'], correctAnswer: 'Wie viel?', difficulty: 2 },
              { id: 'de-d-01-4', type: 'match', question: '出行配对', pairs: [['Bahnhof', '火车站'], ['Hotel', '酒店'], ['Restaurant', '餐厅'], ['Flughafen', '机场']], correctAnswer: 'match', difficulty: 2 },
              { id: 'de-d-01-5', type: 'translate', question: '我迷路了', options: ['Ich habe mich verlaufen', 'Ich bin müde', 'Ich habe Hunger', 'Ich bin krank'], correctAnswer: 'Ich habe mich verlaufen', difficulty: 2 },
              { id: 'de-d-01-6', type: 'dictation', question: '听写：餐厅', audioWord: 'restaurant', correctAnswer: 'restaurant', difficulty: 2 },
            ],
          },
        ],
      },
    ],
  },

  fr: {
    themes: [
      {
        id: 'basic',
        name: '基础词汇',
        color: '#1D4ED8',
        levels: [
          {
            levelId: 'fr-basic-01',
            title: '问候与礼貌',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: [],
            questions: [
              { id: 'fr-b-01-1', type: 'translate', question: '你好', options: ['bonjour', 'merci', 'oui', 'non'], correctAnswer: 'bonjour', difficulty: 1 },
              { id: 'fr-b-01-2', type: 'translate', question: '谢谢', options: ['merci', "s'il vous plaît", 'oui', 'bonjour'], correctAnswer: 'merci', difficulty: 1 },
              { id: 'fr-b-01-3', type: 'fill-blank', question: '___ matin!（早上好）', options: ['Bon', 'Bonne', 'Beau', 'Bons'], correctAnswer: 'Bon', difficulty: 2 },
              { id: 'fr-b-01-4', type: 'match', question: '法语配对', pairs: [['bonjour', '你好'], ['merci', '谢谢'], ['oui', '是'], ['non', '不是']], correctAnswer: 'match', difficulty: 2 },
              { id: 'fr-b-01-5', type: 'translate', question: '我爱你', options: ["je t'aime", 'merci beaucoup', 'bonjour', 'au revoir'], correctAnswer: "je t'aime", difficulty: 2 },
              { id: 'fr-b-01-6', type: 'dictation', question: '听写：水', audioWord: 'eau', correctAnswer: 'eau', difficulty: 2 },
            ],
          },
          {
            levelId: 'fr-basic-02',
            title: '数字与颜色',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: ['fr-basic-01'],
            questions: [
              { id: 'fr-b-02-1', type: 'translate', question: '红色', options: ['rouge', 'bleu', 'vert', 'jaune'], correctAnswer: 'rouge', difficulty: 1 },
              { id: 'fr-b-02-2', type: 'translate', question: '三', options: ['un', 'deux', 'trois', 'quatre'], correctAnswer: 'trois', difficulty: 1 },
              { id: 'fr-b-02-3', type: 'fill-blank', question: 'Le ciel est ___.（天空是蓝色的）', options: ['rouge', 'bleu', 'vert', 'blanc'], correctAnswer: 'bleu', difficulty: 1 },
              { id: 'fr-b-02-4', type: 'match', question: '数字配对', pairs: [['un', '一'], ['deux', '二'], ['trois', '三'], ['quatre', '四']], correctAnswer: 'match', difficulty: 2 },
              { id: 'fr-b-02-5', type: 'translate', question: '绿色', options: ['rouge', 'bleu', 'vert', 'noir'], correctAnswer: 'vert', difficulty: 1 },
              { id: 'fr-b-02-6', type: 'dictation', question: '听写：苹果', audioWord: 'pomme', correctAnswer: 'pomme', difficulty: 2 },
            ],
          },
        ],
      },
      {
        id: 'daily',
        name: '日常对话',
        color: '#60A5FA',
        levels: [
          {
            levelId: 'fr-daily-01',
            title: '出行与问路',
            timeLimit: 150,
            minScoreFor1Star: 40,
            minScoreFor2Star: 60,
            minScoreFor3Star: 80,
            prerequisites: [],
            questions: [
              { id: 'fr-d-01-1', type: 'translate', question: '洗手间在哪里？', options: ['Où sont les toilettes?', 'Combien ça coûte?', 'Quelle heure est-il?', 'Où habitez-vous?'], correctAnswer: 'Où sont les toilettes?', difficulty: 2 },
              { id: 'fr-d-01-2', type: 'fill-blank', question: "Prenez le ___ pour l'aéroport.（坐出租车去机场）", options: ['bus', 'train', 'taxi', 'avion'], correctAnswer: 'taxi', difficulty: 2 },
              { id: 'fr-d-01-3', type: 'translate', question: '多少钱？', options: ['Combien?', 'Combien ça coûte?', 'Quand?', 'Où?'], correctAnswer: 'Combien ça coûte?', difficulty: 2 },
              { id: 'fr-d-01-4', type: 'match', question: '出行配对', pairs: [['gare', '火车站'], ['hôtel', '酒店'], ['restaurant', '餐厅'], ['aéroport', '机场']], correctAnswer: 'match', difficulty: 2 },
              { id: 'fr-d-01-5', type: 'translate', question: '我迷路了', options: ['Je suis perdu', 'Je suis fatigué', "J'ai faim", 'Je suis malade'], correctAnswer: 'Je suis perdu', difficulty: 2 },
              { id: 'fr-d-01-6', type: 'dictation', question: '听写：餐厅', audioWord: 'restaurant', correctAnswer: 'restaurant', difficulty: 2 },
            ],
          },
        ],
      },
    ],
  },

  it: {
    themes: [
      {
        id: 'basic',
        name: '基础词汇',
        color: '#047857',
        levels: [
          {
            levelId: 'it-basic-01',
            title: '问候与礼貌',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: [],
            questions: [
              { id: 'it-b-01-1', type: 'translate', question: '你好', options: ['ciao', 'grazie', 'sì', 'no'], correctAnswer: 'ciao', difficulty: 1 },
              { id: 'it-b-01-2', type: 'translate', question: '谢谢', options: ['grazie', 'per favore', 'sì', 'ciao'], correctAnswer: 'grazie', difficulty: 1 },
              { id: 'it-b-01-3', type: 'fill-blank', question: '___ giorno!（早上好）', options: ['Buon', 'Buona', 'Bella', 'Bel'], correctAnswer: 'Buon', difficulty: 2 },
              { id: 'it-b-01-4', type: 'match', question: '意大利语配对', pairs: [['ciao', '你好'], ['grazie', '谢谢'], ['sì', '是'], ['no', '不是']], correctAnswer: 'match', difficulty: 2 },
              { id: 'it-b-01-5', type: 'translate', question: '我爱你', options: ['ti amo', 'grazie mille', 'ciao', 'arrivederci'], correctAnswer: 'ti amo', difficulty: 2 },
              { id: 'it-b-01-6', type: 'dictation', question: '听写：水', audioWord: 'acqua', correctAnswer: 'acqua', difficulty: 2 },
            ],
          },
          {
            levelId: 'it-basic-02',
            title: '数字与颜色',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: ['it-basic-01'],
            questions: [
              { id: 'it-b-02-1', type: 'translate', question: '红色', options: ['rosso', 'blu', 'verde', 'giallo'], correctAnswer: 'rosso', difficulty: 1 },
              { id: 'it-b-02-2', type: 'translate', question: '三', options: ['uno', 'due', 'tre', 'quattro'], correctAnswer: 'tre', difficulty: 1 },
              { id: 'it-b-02-3', type: 'fill-blank', question: 'Il cielo è ___.（天空是蓝色的）', options: ['rosso', 'blu', 'verde', 'bianco'], correctAnswer: 'blu', difficulty: 1 },
              { id: 'it-b-02-4', type: 'match', question: '数字配对', pairs: [['uno', '一'], ['due', '二'], ['tre', '三'], ['quattro', '四']], correctAnswer: 'match', difficulty: 2 },
              { id: 'it-b-02-5', type: 'translate', question: '绿色', options: ['rosso', 'blu', 'verde', 'nero'], correctAnswer: 'verde', difficulty: 1 },
              { id: 'it-b-02-6', type: 'dictation', question: '听写：苹果', audioWord: 'mela', correctAnswer: 'mela', difficulty: 2 },
            ],
          },
        ],
      },
      {
        id: 'daily',
        name: '日常对话',
        color: '#34D399',
        levels: [
          {
            levelId: 'it-daily-01',
            title: '出行与问路',
            timeLimit: 150,
            minScoreFor1Star: 40,
            minScoreFor2Star: 60,
            minScoreFor3Star: 80,
            prerequisites: [],
            questions: [
              { id: 'it-d-01-1', type: 'translate', question: '洗手间在哪里？', options: ['Dove è il bagno?', 'Quanto costa?', 'Che ore sono?', 'Dove abiti?'], correctAnswer: 'Dove è il bagno?', difficulty: 2 },
              { id: 'it-d-01-2', type: 'fill-blank', question: "Prendi il ___ per l'aeroporto.（坐出租车去机场）", options: ['bus', 'treno', 'taxi', 'aereo'], correctAnswer: 'taxi', difficulty: 2 },
              { id: 'it-d-01-3', type: 'translate', question: '多少钱？', options: ['Quanti?', 'Quanto costa?', 'Quando?', 'Dove?'], correctAnswer: 'Quanto costa?', difficulty: 2 },
              { id: 'it-d-01-4', type: 'match', question: '出行配对', pairs: [['stazione', '火车站'], ['albergo', '酒店'], ['ristorante', '餐厅'], ['aeroporto', '机场']], correctAnswer: 'match', difficulty: 2 },
              { id: 'it-d-01-5', type: 'translate', question: '我迷路了', options: ['Mi sono perso', 'Sono stanco', 'Ho fame', 'Sono malato'], correctAnswer: 'Mi sono perso', difficulty: 2 },
              { id: 'it-d-01-6', type: 'dictation', question: '听写：餐厅', audioWord: 'ristorante', correctAnswer: 'ristorante', difficulty: 2 },
            ],
          },
        ],
      },
    ],
  },

  pt: {
    themes: [
      {
        id: 'basic',
        name: '基础词汇',
        color: '#B45309',
        levels: [
          {
            levelId: 'pt-basic-01',
            title: '问候与礼貌',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: [],
            questions: [
              { id: 'pt-b-01-1', type: 'translate', question: '你好', options: ['olá', 'obrigado', 'sim', 'não'], correctAnswer: 'olá', difficulty: 1 },
              { id: 'pt-b-01-2', type: 'translate', question: '谢谢', options: ['obrigado', 'por favor', 'sim', 'olá'], correctAnswer: 'obrigado', difficulty: 1 },
              { id: 'pt-b-01-3', type: 'fill-blank', question: '___ dia!（早上好）', options: ['Bom', 'Boa', 'Bons', 'Boas'], correctAnswer: 'Bom', difficulty: 2 },
              { id: 'pt-b-01-4', type: 'match', question: '葡萄牙语配对', pairs: [['olá', '你好'], ['obrigado', '谢谢'], ['sim', '是'], ['não', '不是']], correctAnswer: 'match', difficulty: 2 },
              { id: 'pt-b-01-5', type: 'translate', question: '我爱你', options: ['eu te amo', 'muito obrigado', 'olá', 'adeus'], correctAnswer: 'eu te amo', difficulty: 2 },
              { id: 'pt-b-01-6', type: 'dictation', question: '听写：水', audioWord: 'água', correctAnswer: 'água', difficulty: 2 },
            ],
          },
          {
            levelId: 'pt-basic-02',
            title: '数字与颜色',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: ['pt-basic-01'],
            questions: [
              { id: 'pt-b-02-1', type: 'translate', question: '红色', options: ['vermelho', 'azul', 'verde', 'amarelo'], correctAnswer: 'vermelho', difficulty: 1 },
              { id: 'pt-b-02-2', type: 'translate', question: '三', options: ['um', 'dois', 'três', 'quatro'], correctAnswer: 'três', difficulty: 1 },
              { id: 'pt-b-02-3', type: 'fill-blank', question: 'O céu é ___.（天空是蓝色的）', options: ['vermelho', 'azul', 'verde', 'branco'], correctAnswer: 'azul', difficulty: 1 },
              { id: 'pt-b-02-4', type: 'match', question: '数字配对', pairs: [['um', '一'], ['dois', '二'], ['três', '三'], ['quatro', '四']], correctAnswer: 'match', difficulty: 2 },
              { id: 'pt-b-02-5', type: 'translate', question: '绿色', options: ['vermelho', 'azul', 'verde', 'preto'], correctAnswer: 'verde', difficulty: 1 },
              { id: 'pt-b-02-6', type: 'dictation', question: '听写：苹果', audioWord: 'maçã', correctAnswer: 'maçã', difficulty: 2 },
            ],
          },
        ],
      },
      {
        id: 'daily',
        name: '日常对话',
        color: '#F59E0B',
        levels: [
          {
            levelId: 'pt-daily-01',
            title: '出行与问路',
            timeLimit: 150,
            minScoreFor1Star: 40,
            minScoreFor2Star: 60,
            minScoreFor3Star: 80,
            prerequisites: [],
            questions: [
              { id: 'pt-d-01-1', type: 'translate', question: '洗手间在哪里？', options: ['Onde fica o banheiro?', 'Quanto custa isso?', 'Que horas são?', 'Onde você mora?'], correctAnswer: 'Onde fica o banheiro?', difficulty: 2 },
              { id: 'pt-d-01-2', type: 'fill-blank', question: 'Pegue o ___ para o aeroporto.（坐出租车去机场）', options: ['ônibus', 'trem', 'táxi', 'avião'], correctAnswer: 'táxi', difficulty: 2 },
              { id: 'pt-d-01-3', type: 'translate', question: '多少钱？', options: ['Quantos?', 'Quanto custa?', 'Quando?', 'Onde?'], correctAnswer: 'Quanto custa?', difficulty: 2 },
              { id: 'pt-d-01-4', type: 'match', question: '出行配对', pairs: [['estação', '火车站'], ['hotel', '酒店'], ['restaurante', '餐厅'], ['aeroporto', '机场']], correctAnswer: 'match', difficulty: 2 },
              { id: 'pt-d-01-5', type: 'translate', question: '我迷路了', options: ['Estou perdido', 'Estou cansado', 'Estou com fome', 'Estou doente'], correctAnswer: 'Estou perdido', difficulty: 2 },
              { id: 'pt-d-01-6', type: 'dictation', question: '听写：餐厅', audioWord: 'restaurante', correctAnswer: 'restaurante', difficulty: 2 },
            ],
          },
        ],
      },
    ],
  },

  ar: {
    themes: [
      {
        id: 'basic',
        name: '基础词汇',
        color: '#065F46',
        levels: [
          {
            levelId: 'ar-basic-01',
            title: '问候与礼貌',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: [],
            questions: [
              { id: 'ar-b-01-1', type: 'translate', question: '你好', options: ['مرحبا', 'شكرا', 'نعم', 'لا'], correctAnswer: 'مرحبا', difficulty: 1 },
              { id: 'ar-b-01-2', type: 'translate', question: '谢谢', options: ['شكرا', 'من فضلك', 'نعم', 'مرحبا'], correctAnswer: 'شكرا', difficulty: 1 },
              { id: 'ar-b-01-3', type: 'fill-blank', question: '___ الخير（早上好）', options: ['صباح', 'مساء', 'ليلة', 'يوم'], correctAnswer: 'صباح', difficulty: 2 },
              { id: 'ar-b-01-4', type: 'match', question: '阿拉伯语配对', pairs: [['مرحبا', '你好'], ['شكرا', '谢谢'], ['نعم', '是'], ['لا', '不是']], correctAnswer: 'match', difficulty: 2 },
              { id: 'ar-b-01-5', type: 'translate', question: '我爱你', options: ['أحبك', 'شكرا جزيلا', 'مرحبا', 'مع السلامة'], correctAnswer: 'أحبك', difficulty: 2 },
              { id: 'ar-b-01-6', type: 'dictation', question: '听写：水', audioWord: 'ماء', correctAnswer: 'ماء', difficulty: 2 },
            ],
          },
          {
            levelId: 'ar-basic-02',
            title: '数字与颜色',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: ['ar-basic-01'],
            questions: [
              { id: 'ar-b-02-1', type: 'translate', question: '红色', options: ['أحمر', 'أزرق', 'أخضر', 'أصفر'], correctAnswer: 'أحمر', difficulty: 1 },
              { id: 'ar-b-02-2', type: 'translate', question: '三', options: ['واحد', 'اثنان', 'ثلاثة', 'أربعة'], correctAnswer: 'ثلاثة', difficulty: 1 },
              { id: 'ar-b-02-3', type: 'fill-blank', question: 'السماء ___.（天空是蓝色的）', options: ['حمراء', 'زرقاء', 'خضراء', 'بيضاء'], correctAnswer: 'زرقاء', difficulty: 1 },
              { id: 'ar-b-02-4', type: 'match', question: '数字配对', pairs: [['واحد', '一'], ['اثنان', '二'], ['ثلاثة', '三'], ['أربعة', '四']], correctAnswer: 'match', difficulty: 2 },
              { id: 'ar-b-02-5', type: 'translate', question: '绿色', options: ['أحمر', 'أزرق', 'أخضر', 'أسود'], correctAnswer: 'أخضر', difficulty: 1 },
              { id: 'ar-b-02-6', type: 'dictation', question: '听写：苹果', audioWord: 'تفاح', correctAnswer: 'تفاح', difficulty: 2 },
            ],
          },
        ],
      },
      {
        id: 'daily',
        name: '日常对话',
        color: '#10B981',
        levels: [
          {
            levelId: 'ar-daily-01',
            title: '出行与问路',
            timeLimit: 150,
            minScoreFor1Star: 40,
            minScoreFor2Star: 60,
            minScoreFor3Star: 80,
            prerequisites: [],
            questions: [
              { id: 'ar-d-01-1', type: 'translate', question: '洗手间在哪里？', options: ['أين الحمام؟', 'كم سعر هذا؟', 'كم الساعة؟', 'أين تسكن؟'], correctAnswer: 'أين الحمام؟', difficulty: 2 },
              { id: 'ar-d-01-2', type: 'fill-blank', question: 'خذ ال___ إلى المطار.（坐出租车去机场）', options: ['حافلة', 'قطار', 'تاكسي', 'طائرة'], correctAnswer: 'تاكسي', difficulty: 2 },
              { id: 'ar-d-01-3', type: 'translate', question: '多少钱？', options: ['كم عدد؟', 'كم السعر؟', 'متى؟', 'أين؟'], correctAnswer: 'كم السعر؟', difficulty: 2 },
              { id: 'ar-d-01-4', type: 'match', question: '出行配对', pairs: [['محطة', '火车站'], ['فندق', '酒店'], ['مطعم', '餐厅'], ['مطار', '机场']], correctAnswer: 'match', difficulty: 2 },
              { id: 'ar-d-01-5', type: 'translate', question: '我迷路了', options: ['أنا ضائع', 'أنا متعب', 'أنا جائع', 'أنا مريض'], correctAnswer: 'أنا ضائع', difficulty: 2 },
              { id: 'ar-d-01-6', type: 'dictation', question: '听写：餐厅', audioWord: 'مطعم', correctAnswer: 'مطعم', difficulty: 2 },
            ],
          },
        ],
      },
    ],
  },

  hi: {
    themes: [
      {
        id: 'basic',
        name: '基础词汇',
        color: '#7C3AED',
        levels: [
          {
            levelId: 'hi-basic-01',
            title: '问候与礼貌',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: [],
            questions: [
              { id: 'hi-b-01-1', type: 'translate', question: '你好', options: ['नमस्ते', 'धन्यवाद', 'हाँ', 'नहीं'], correctAnswer: 'नमस्ते', difficulty: 1 },
              { id: 'hi-b-01-2', type: 'translate', question: '谢谢', options: ['धन्यवाद', 'कृपया', 'हाँ', 'नमस्ते'], correctAnswer: 'धन्यवाद', difficulty: 1 },
              { id: 'hi-b-01-3', type: 'fill-blank', question: '___ प्रभात（早上好）', options: ['शुभ', 'सुप्रभात', 'शुभ', 'सुबह'], correctAnswer: 'शुभ', difficulty: 2 },
              { id: 'hi-b-01-4', type: 'match', question: '印地语配对', pairs: [['नमस्ते', '你好'], ['धन्यवाद', '谢谢'], ['हाँ', '是'], ['नहीं', '不是']], correctAnswer: 'match', difficulty: 2 },
              { id: 'hi-b-01-5', type: 'translate', question: '我爱你', options: ['मैं तुमसे प्यार करता हूँ', 'बहुत धन्यवाद', 'नमस्ते', 'अलविदा'], correctAnswer: 'मैं तुमसे प्यार करता हूँ', difficulty: 2 },
              { id: 'hi-b-01-6', type: 'dictation', question: '听写：水', audioWord: 'पानी', correctAnswer: 'पानी', difficulty: 2 },
            ],
          },
          {
            levelId: 'hi-basic-02',
            title: '数字与颜色',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: ['hi-basic-01'],
            questions: [
              { id: 'hi-b-02-1', type: 'translate', question: '红色', options: ['लाल', 'नीला', 'हरा', 'पीला'], correctAnswer: 'लाल', difficulty: 1 },
              { id: 'hi-b-02-2', type: 'translate', question: '三', options: ['एक', 'दो', 'तीन', 'चार'], correctAnswer: 'तीन', difficulty: 1 },
              { id: 'hi-b-02-3', type: 'fill-blank', question: 'आसमान ___ है।（天空是蓝色的）', options: ['लाल', 'नीला', 'हरा', 'सफ़ेद'], correctAnswer: 'नीला', difficulty: 1 },
              { id: 'hi-b-02-4', type: 'match', question: '数字配对', pairs: [['एक', '一'], ['दो', '二'], ['तीन', '三'], ['चार', '四']], correctAnswer: 'match', difficulty: 2 },
              { id: 'hi-b-02-5', type: 'translate', question: '绿色', options: ['लाल', 'नीला', 'हरा', 'काला'], correctAnswer: 'हरा', difficulty: 1 },
              { id: 'hi-b-02-6', type: 'dictation', question: '听写：苹果', audioWord: 'सेब', correctAnswer: 'सेब', difficulty: 2 },
            ],
          },
        ],
      },
      {
        id: 'daily',
        name: '日常对话',
        color: '#A78BFA',
        levels: [
          {
            levelId: 'hi-daily-01',
            title: '出行与问路',
            timeLimit: 150,
            minScoreFor1Star: 40,
            minScoreFor2Star: 60,
            minScoreFor3Star: 80,
            prerequisites: [],
            questions: [
              { id: 'hi-d-01-1', type: 'translate', question: '洗手间在哪里？', options: ['शौचालय कहाँ है?', 'इसकी कीमत क्या है?', 'कितना बजा है?', 'आप कहाँ रहते हैं?'], correctAnswer: 'शौचालय कहाँ है?', difficulty: 2 },
              { id: 'hi-d-01-2', type: 'fill-blank', question: 'हवाई अड्डे के लिए ___ लें।（坐出租车去机场）', options: ['बस', 'ट्रेन', 'टैक्सी', 'हवाई जहाज़'], correctAnswer: 'टैक्सी', difficulty: 2 },
              { id: 'hi-d-01-3', type: 'translate', question: '多少钱？', options: ['कितने?', 'कीमत क्या है?', 'कब?', 'कहाँ?'], correctAnswer: 'कीमत क्या है?', difficulty: 2 },
              { id: 'hi-d-01-4', type: 'match', question: '出行配对', pairs: [['स्टेशन', '火车站'], ['होटल', '酒店'], ['रेस्टोरेंट', '餐厅'], ['हवाई अड्डा', '机场']], correctAnswer: 'match', difficulty: 2 },
              { id: 'hi-d-01-5', type: 'translate', question: '我迷路了', options: ['मैं रास्ता भूल गया', 'मैं थका हुआ हूँ', 'मुझे भूख लगी है', 'मैं बीमार हूँ'], correctAnswer: 'मैं रास्ता भूल गया', difficulty: 2 },
              { id: 'hi-d-01-6', type: 'dictation', question: '听写：餐厅', audioWord: 'रेस्टोरेंट', correctAnswer: 'रेस्टोरेंट', difficulty: 2 },
            ],
          },
        ],
      },
    ],
  },
  th: {
    themes: [
      {
        id: 'basic',
        name: '泰语基础词汇',
        color: '#1E3A8A',
        levels: [
          {
            levelId: 'th-basic-01',
            title: '问候与礼貌',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: [],
            questions: [
              { id: 'th-b-01-1', type: 'translate', question: '你好', options: ["\u0e2a\u0e27\u0e31\u0e2a\u0e14\u0e35", "\u0e02\u0e2d\u0e1a\u0e04\u0e38\u0e13", "\u0e02\u0e2d\u0e42\u0e17\u0e29", "\u0e2a\u0e27\u0e31\u0e2a\u0e14\u0e35\u0e15\u0e2d\u0e19\u0e40\u0e0a\u0e49\u0e32"], correctAnswer: 'สวัสดี', difficulty: 1 },
              { id: 'th-b-01-2', type: 'translate', question: '谢谢', options: ["\u0e02\u0e2d\u0e1a\u0e04\u0e38\u0e13", "\u0e2a\u0e27\u0e31\u0e2a\u0e14\u0e35", "\u0e02\u0e2d\u0e42\u0e17\u0e29", "\u0e2a\u0e27\u0e31\u0e2a\u0e14\u0e35\u0e15\u0e2d\u0e19\u0e40\u0e0a\u0e49\u0e32"], correctAnswer: 'ขอบคุณ', difficulty: 1 },
              { id: 'th-b-01-3', type: 'fill-blank', question: '___ ตอนเช้า!（早上好）', options: ["\u0e2a\u0e27\u0e31\u0e2a\u0e14\u0e35", "\u0e23\u0e32\u0e15\u0e23\u0e35\u0e2a\u0e27\u0e31\u0e2a\u0e14\u0e34\u0e4c", "\u0e02\u0e2d\u0e1a\u0e04\u0e38\u0e13", "\u0e25\u0e32\u0e01\u0e48\u0e2d\u0e19"], correctAnswer: 'สวัสดี', difficulty: 2 },
              { id: 'th-b-01-4', type: 'match', question: '泰语配对', pairs: [["\u0e2a\u0e27\u0e31\u0e2a\u0e14\u0e35", "\u4f60\u597d"], ["\u0e02\u0e2d\u0e1a\u0e04\u0e38\u0e13", "\u8c22\u8c22"], ["\u0e02\u0e2d\u0e42\u0e17\u0e29", "\u5bf9\u4e0d\u8d77"], ["\u0e2a\u0e27\u0e31\u0e2a\u0e14\u0e35\u0e15\u0e2d\u0e19\u0e40\u0e0a\u0e49\u0e32", "\u65e9\u4e0a\u597d"]], correctAnswer: 'match', difficulty: 2 },
              { id: 'th-b-01-5', type: 'translate', question: '晚安', options: ["\u0e23\u0e32\u0e15\u0e23\u0e35\u0e2a\u0e27\u0e31\u0e2a\u0e14\u0e34\u0e4c", "\u0e2a\u0e27\u0e31\u0e2a\u0e14\u0e35", "\u0e02\u0e2d\u0e1a\u0e04\u0e38\u0e13", "\u0e02\u0e2d\u0e42\u0e17\u0e29"], correctAnswer: 'ราตรีสวัสดิ์', difficulty: 2 },
              { id: 'th-b-01-6', type: 'dictation', question: '听写：水', audioWord: 'น้ำ', correctAnswer: 'น้ำ', difficulty: 2 },
            ],
          },
          {
            levelId: 'th-basic-02',
            title: '数字与颜色',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: ['th-basic-01'],
            questions: [
              { id: 'th-b-02-1', type: 'translate', question: '红色', options: ["\u0e41\u0e14\u0e07", "\u0e19\u0e49\u0e33\u0e40\u0e07\u0e34\u0e19", "\u0e40\u0e02\u0e35\u0e22\u0e27", "\u0e40\u0e2b\u0e25\u0e37\u0e2d\u0e07"], correctAnswer: 'แดง', difficulty: 1 },
              { id: 'th-b-02-2', type: 'translate', question: '三', options: ["\u0e2a\u0e32\u0e21", "\u0e2b\u0e19\u0e36\u0e48\u0e07", "\u0e2a\u0e2d\u0e07", "\u0e2a\u0e35\u0e48"], correctAnswer: 'สาม', difficulty: 1 },
              { id: 'th-b-02-3', type: 'fill-blank', question: 'นี่คือสี ___（这是红色的）', options: ["\u0e41\u0e14\u0e07", "\u0e19\u0e49\u0e33\u0e40\u0e07\u0e34\u0e19", "\u0e40\u0e02\u0e35\u0e22\u0e27", "\u0e40\u0e2b\u0e25\u0e37\u0e2d\u0e07"], correctAnswer: 'แดง', difficulty: 1 },
              { id: 'th-b-02-4', type: 'match', question: '数字配对', pairs: [["\u0e2b\u0e19\u0e36\u0e48\u0e07", "\u4e00"], ["\u0e2a\u0e2d\u0e07", "\u4e8c"], ["\u0e2a\u0e32\u0e21", "\u4e09"], ["\u0e2a\u0e35\u0e48", "\u56db"]], correctAnswer: 'match', difficulty: 2 },
              { id: 'th-b-02-5', type: 'translate', question: '绿色', options: ["\u0e40\u0e02\u0e35\u0e22\u0e27", "\u0e41\u0e14\u0e07", "\u0e19\u0e49\u0e33\u0e40\u0e07\u0e34\u0e19", "\u0e40\u0e2b\u0e25\u0e37\u0e2d\u0e07"], correctAnswer: 'เขียว', difficulty: 1 },
              { id: 'th-b-02-6', type: 'dictation', question: '听写：米饭', audioWord: 'ข้าว', correctAnswer: 'ข้าว', difficulty: 2 },
            ],
          },
        ],
      },
      {
        id: 'daily',
        name: '日常对话',
        color: '#3B82F6',
        levels: [
          {
            levelId: 'th-daily-01',
            title: '出行与问路',
            timeLimit: 150,
            minScoreFor1Star: 40,
            minScoreFor2Star: 60,
            minScoreFor3Star: 80,
            prerequisites: [],
            questions: [
              { id: 'th-d-01-1', type: 'translate', question: '洗手间在哪里？', options: ["\u0e2b\u0e49\u0e2d\u0e07\u0e19\u0e49\u0e33\u0e2d\u0e22\u0e39\u0e48\u0e17\u0e35\u0e48\u0e44\u0e2b\u0e19", "\u0e2d\u0e31\u0e19\u0e19\u0e35\u0e49\u0e40\u0e17\u0e48\u0e32\u0e44\u0e2b\u0e23\u0e48", "\u0e09\u0e31\u0e19\u0e2b\u0e25\u0e07\u0e17\u0e32\u0e07", "\u0e09\u0e31\u0e19\u0e15\u0e49\u0e2d\u0e07\u0e01\u0e32\u0e23\u0e2b\u0e21\u0e2d"], correctAnswer: 'ห้องน้ำอยู่ที่ไหน', difficulty: 2 },
              { id: 'th-d-01-2', type: 'translate', question: '这个多少钱？', options: ["\u0e2d\u0e31\u0e19\u0e19\u0e35\u0e49\u0e40\u0e17\u0e48\u0e32\u0e44\u0e2b\u0e23\u0e48", "\u0e2b\u0e49\u0e2d\u0e07\u0e19\u0e49\u0e33\u0e2d\u0e22\u0e39\u0e48\u0e17\u0e35\u0e48\u0e44\u0e2b\u0e19", "\u0e09\u0e31\u0e19\u0e2b\u0e25\u0e07\u0e17\u0e32\u0e07", "\u0e09\u0e31\u0e19\u0e15\u0e49\u0e2d\u0e07\u0e01\u0e32\u0e23\u0e2b\u0e21\u0e2d"], correctAnswer: 'อันนี้เท่าไหร่', difficulty: 2 },
              { id: 'th-d-01-3', type: 'translate', question: '我迷路了？', options: ["\u0e09\u0e31\u0e19\u0e2b\u0e25\u0e07\u0e17\u0e32\u0e07", "\u0e2b\u0e49\u0e2d\u0e07\u0e19\u0e49\u0e33\u0e2d\u0e22\u0e39\u0e48\u0e17\u0e35\u0e48\u0e44\u0e2b\u0e19", "\u0e2d\u0e31\u0e19\u0e19\u0e35\u0e49\u0e40\u0e17\u0e48\u0e32\u0e44\u0e2b\u0e23\u0e48", "\u0e09\u0e31\u0e19\u0e15\u0e49\u0e2d\u0e07\u0e01\u0e32\u0e23\u0e2b\u0e21\u0e2d"], correctAnswer: 'ฉันหลงทาง', difficulty: 2 },
              { id: 'th-d-01-4', type: 'translate', question: '我需要医生？', options: ["\u0e09\u0e31\u0e19\u0e15\u0e49\u0e2d\u0e07\u0e01\u0e32\u0e23\u0e2b\u0e21\u0e2d", "\u0e2b\u0e49\u0e2d\u0e07\u0e19\u0e49\u0e33\u0e2d\u0e22\u0e39\u0e48\u0e17\u0e35\u0e48\u0e44\u0e2b\u0e19", "\u0e2d\u0e31\u0e19\u0e19\u0e35\u0e49\u0e40\u0e17\u0e48\u0e32\u0e44\u0e2b\u0e23\u0e48", "\u0e09\u0e31\u0e19\u0e2b\u0e25\u0e07\u0e17\u0e32\u0e07"], correctAnswer: 'ฉันต้องการหมอ', difficulty: 2 },
              { id: 'th-d-01-5', type: 'match', question: '出行配对', pairs: [["\u0e23\u0e16\u0e44\u0e1f", "\u706b\u8f66"], ["\u0e42\u0e23\u0e07\u0e1e\u0e22\u0e32\u0e1a\u0e32\u0e25", "\u533b\u9662"], ["\u0e42\u0e23\u0e07\u0e40\u0e23\u0e35\u0e22\u0e19", "\u5b66\u6821"], ["\u0e40\u0e04\u0e23\u0e37\u0e48\u0e2d\u0e07\u0e1a\u0e34\u0e19", "\u98de\u673a"]], correctAnswer: 'match', difficulty: 2 },
              { id: 'th-d-01-6', type: 'fill-blank', question: '___ ให้หน่อย（请结账）', options: ["\u0e40\u0e0a\u0e47\u0e04\u0e1a\u0e34\u0e25", "\u0e02\u0e2d\u0e1a\u0e04\u0e38\u0e13", "\u0e2a\u0e27\u0e31\u0e2a\u0e14\u0e35", "\u0e25\u0e32\u0e01\u0e48\u0e2d\u0e19"], correctAnswer: 'เช็คบิล', difficulty: 2 },
            ],
          },
        ],
      },
    ],
  },
  vi: {
    themes: [
      {
        id: 'basic',
        name: '越南语基础词汇',
        color: '#1D4ED8',
        levels: [
          {
            levelId: 'vi-basic-01',
            title: '问候与礼貌',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: [],
            questions: [
              { id: 'vi-b-01-1', type: 'translate', question: '你好', options: ["xin ch\u00e0o", "c\u1ea3m \u01a1n", "xin l\u1ed7i", "ch\u00e0o bu\u1ed5i s\u00e1ng"], correctAnswer: 'xin chào', difficulty: 1 },
              { id: 'vi-b-01-2', type: 'translate', question: '谢谢', options: ["c\u1ea3m \u01a1n", "xin ch\u00e0o", "xin l\u1ed7i", "ch\u00e0o bu\u1ed5i s\u00e1ng"], correctAnswer: 'cảm ơn', difficulty: 1 },
              { id: 'vi-b-01-3', type: 'fill-blank', question: '___ buổi sáng!（早上好）', options: ["Ch\u00e0o", "C\u1ea3m \u01a1n", "Xin l\u1ed7i", "T\u1ea1m bi\u1ec7t"], correctAnswer: 'Chào', difficulty: 2 },
              { id: 'vi-b-01-4', type: 'match', question: '越南语配对', pairs: [["xin ch\u00e0o", "\u4f60\u597d"], ["c\u1ea3m \u01a1n", "\u8c22\u8c22"], ["xin l\u1ed7i", "\u5bf9\u4e0d\u8d77"], ["ch\u00e0o bu\u1ed5i s\u00e1ng", "\u65e9\u4e0a\u597d"]], correctAnswer: 'match', difficulty: 2 },
              { id: 'vi-b-01-5', type: 'translate', question: '晚安', options: ["ch\u00fac ng\u1ee7 ngon", "xin ch\u00e0o", "c\u1ea3m \u01a1n", "xin l\u1ed7i"], correctAnswer: 'chúc ngủ ngon', difficulty: 2 },
              { id: 'vi-b-01-6', type: 'dictation', question: '听写：水', audioWord: 'nước', correctAnswer: 'nước', difficulty: 2 },
            ],
          },
          {
            levelId: 'vi-basic-02',
            title: '数字与颜色',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: ['vi-basic-01'],
            questions: [
              { id: 'vi-b-02-1', type: 'translate', question: '红色', options: ["\u0111\u1ecf", "xanh d\u01b0\u01a1ng", "xanh l\u00e1", "v\u00e0ng"], correctAnswer: 'đỏ', difficulty: 1 },
              { id: 'vi-b-02-2', type: 'translate', question: '三', options: ["ba", "m\u1ed9t", "hai", "b\u1ed1n"], correctAnswer: 'ba', difficulty: 1 },
              { id: 'vi-b-02-3', type: 'fill-blank', question: 'Đây là màu ___（这是红色的）', options: ["\u0111\u1ecf", "xanh d\u01b0\u01a1ng", "xanh l\u00e1", "v\u00e0ng"], correctAnswer: 'đỏ', difficulty: 1 },
              { id: 'vi-b-02-4', type: 'match', question: '数字配对', pairs: [["m\u1ed9t", "\u4e00"], ["hai", "\u4e8c"], ["ba", "\u4e09"], ["b\u1ed1n", "\u56db"]], correctAnswer: 'match', difficulty: 2 },
              { id: 'vi-b-02-5', type: 'translate', question: '绿色', options: ["xanh l\u00e1", "\u0111\u1ecf", "xanh d\u01b0\u01a1ng", "v\u00e0ng"], correctAnswer: 'xanh lá', difficulty: 1 },
              { id: 'vi-b-02-6', type: 'dictation', question: '听写：米饭', audioWord: 'cơm', correctAnswer: 'cơm', difficulty: 2 },
            ],
          },
        ],
      },
      {
        id: 'daily',
        name: '日常对话',
        color: '#3B82F6',
        levels: [
          {
            levelId: 'vi-daily-01',
            title: '出行与问路',
            timeLimit: 150,
            minScoreFor1Star: 40,
            minScoreFor2Star: 60,
            minScoreFor3Star: 80,
            prerequisites: [],
            questions: [
              { id: 'vi-d-01-1', type: 'translate', question: '洗手间在哪里？', options: ["nh\u00e0 v\u1ec7 sinh \u1edf \u0111\u00e2u", "c\u00e1i n\u00e0y bao nhi\u00eau ti\u1ec1n", "t\u00f4i b\u1ecb l\u1ea1c", "t\u00f4i c\u1ea7n b\u00e1c s\u0129"], correctAnswer: 'nhà vệ sinh ở đâu', difficulty: 2 },
              { id: 'vi-d-01-2', type: 'translate', question: '这个多少钱？', options: ["c\u00e1i n\u00e0y bao nhi\u00eau ti\u1ec1n", "nh\u00e0 v\u1ec7 sinh \u1edf \u0111\u00e2u", "t\u00f4i b\u1ecb l\u1ea1c", "t\u00f4i c\u1ea7n b\u00e1c s\u0129"], correctAnswer: 'cái này bao nhiêu tiền', difficulty: 2 },
              { id: 'vi-d-01-3', type: 'translate', question: '我迷路了？', options: ["t\u00f4i b\u1ecb l\u1ea1c", "nh\u00e0 v\u1ec7 sinh \u1edf \u0111\u00e2u", "c\u00e1i n\u00e0y bao nhi\u00eau ti\u1ec1n", "t\u00f4i c\u1ea7n b\u00e1c s\u0129"], correctAnswer: 'tôi bị lạc', difficulty: 2 },
              { id: 'vi-d-01-4', type: 'translate', question: '我需要医生？', options: ["t\u00f4i c\u1ea7n b\u00e1c s\u0129", "nh\u00e0 v\u1ec7 sinh \u1edf \u0111\u00e2u", "c\u00e1i n\u00e0y bao nhi\u00eau ti\u1ec1n", "t\u00f4i b\u1ecb l\u1ea1c"], correctAnswer: 'tôi cần bác sĩ', difficulty: 2 },
              { id: 'vi-d-01-5', type: 'match', question: '出行配对', pairs: [["xe l\u1eeda", "\u706b\u8f66"], ["b\u1ec7nh vi\u1ec7n", "\u533b\u9662"], ["tr\u01b0\u1eddng h\u1ecdc", "\u5b66\u6821"], ["m\u00e1y bay", "\u98de\u673a"]], correctAnswer: 'match', difficulty: 2 },
              { id: 'vi-d-01-6', type: 'fill-blank', question: '___ tiền giúp tôi（请结账）', options: ["T\u00ednh", "C\u1ea3m \u01a1n", "Xin ch\u00e0o", "T\u1ea1m bi\u1ec7t"], correctAnswer: 'Tính', difficulty: 2 },
            ],
          },
        ],
      },
    ],
  },
  tr: {
    themes: [
      {
        id: 'basic',
        name: '土耳其语基础词汇',
        color: '#7C3AED',
        levels: [
          {
            levelId: 'tr-basic-01',
            title: '问候与礼貌',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: [],
            questions: [
              { id: 'tr-b-01-1', type: 'translate', question: '你好', options: ["merhaba", "te\u015fekk\u00fcr ederim", "\u00f6z\u00fcr dilerim", "g\u00fcnayd\u0131n"], correctAnswer: 'merhaba', difficulty: 1 },
              { id: 'tr-b-01-2', type: 'translate', question: '谢谢', options: ["te\u015fekk\u00fcr ederim", "merhaba", "\u00f6z\u00fcr dilerim", "g\u00fcnayd\u0131n"], correctAnswer: 'teşekkür ederim', difficulty: 1 },
              { id: 'tr-b-01-3', type: 'fill-blank', question: '___ ederim!（谢谢）', options: ["Te\u015fekk\u00fcr", "\u00d6z\u00fcr", "Merhaba", "Ho\u015f\u00e7a"], correctAnswer: 'Teşekkür', difficulty: 2 },
              { id: 'tr-b-01-4', type: 'match', question: '土耳其语配对', pairs: [["merhaba", "\u4f60\u597d"], ["te\u015fekk\u00fcr ederim", "\u8c22\u8c22"], ["\u00f6z\u00fcr dilerim", "\u5bf9\u4e0d\u8d77"], ["g\u00fcnayd\u0131n", "\u65e9\u4e0a\u597d"]], correctAnswer: 'match', difficulty: 2 },
              { id: 'tr-b-01-5', type: 'translate', question: '晚安', options: ["iyi geceler", "merhaba", "te\u015fekk\u00fcr ederim", "\u00f6z\u00fcr dilerim"], correctAnswer: 'iyi geceler', difficulty: 2 },
              { id: 'tr-b-01-6', type: 'dictation', question: '听写：水', audioWord: 'su', correctAnswer: 'su', difficulty: 2 },
            ],
          },
          {
            levelId: 'tr-basic-02',
            title: '数字与颜色',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: ['tr-basic-01'],
            questions: [
              { id: 'tr-b-02-1', type: 'translate', question: '红色', options: ["k\u0131rm\u0131z\u0131", "mavi", "ye\u015fil", "sar\u0131"], correctAnswer: 'kırmızı', difficulty: 1 },
              { id: 'tr-b-02-2', type: 'translate', question: '三', options: ["\u00fc\u00e7", "bir", "iki", "d\u00f6rt"], correctAnswer: 'üç', difficulty: 1 },
              { id: 'tr-b-02-3', type: 'fill-blank', question: 'Bu ___ renk（这是红色的）', options: ["k\u0131rm\u0131z\u0131", "mavi", "ye\u015fil", "sar\u0131"], correctAnswer: 'kırmızı', difficulty: 1 },
              { id: 'tr-b-02-4', type: 'match', question: '数字配对', pairs: [["bir", "\u4e00"], ["iki", "\u4e8c"], ["\u00fc\u00e7", "\u4e09"], ["d\u00f6rt", "\u56db"]], correctAnswer: 'match', difficulty: 2 },
              { id: 'tr-b-02-5', type: 'translate', question: '绿色', options: ["ye\u015fil", "k\u0131rm\u0131z\u0131", "mavi", "sar\u0131"], correctAnswer: 'yeşil', difficulty: 1 },
              { id: 'tr-b-02-6', type: 'dictation', question: '听写：米饭', audioWord: 'pilav', correctAnswer: 'pilav', difficulty: 2 },
            ],
          },
        ],
      },
      {
        id: 'daily',
        name: '日常对话',
        color: '#8B5CF6',
        levels: [
          {
            levelId: 'tr-daily-01',
            title: '出行与问路',
            timeLimit: 150,
            minScoreFor1Star: 40,
            minScoreFor2Star: 60,
            minScoreFor3Star: 80,
            prerequisites: [],
            questions: [
              { id: 'tr-d-01-1', type: 'translate', question: '洗手间在哪里？', options: ["tuvalet nerede", "bu ne kadar", "kayboldum", "doktora ihtiyac\u0131m var"], correctAnswer: 'tuvalet nerede', difficulty: 2 },
              { id: 'tr-d-01-2', type: 'translate', question: '这个多少钱？', options: ["bu ne kadar", "tuvalet nerede", "kayboldum", "doktora ihtiyac\u0131m var"], correctAnswer: 'bu ne kadar', difficulty: 2 },
              { id: 'tr-d-01-3', type: 'translate', question: '我迷路了？', options: ["kayboldum", "tuvalet nerede", "bu ne kadar", "doktora ihtiyac\u0131m var"], correctAnswer: 'kayboldum', difficulty: 2 },
              { id: 'tr-d-01-4', type: 'translate', question: '我需要医生？', options: ["doktora ihtiyac\u0131m var", "tuvalet nerede", "bu ne kadar", "kayboldum"], correctAnswer: 'doktora ihtiyacım var', difficulty: 2 },
              { id: 'tr-d-01-5', type: 'match', question: '出行配对', pairs: [["tren", "\u706b\u8f66"], ["hastane", "\u533b\u9662"], ["okul", "\u5b66\u6821"], ["u\u00e7ak", "\u98de\u673a"]], correctAnswer: 'match', difficulty: 2 },
              { id: 'tr-d-01-6', type: 'fill-blank', question: '___ lütfen（请结账）', options: ["Hesap", "Te\u015fekk\u00fcr", "Merhaba", "Ho\u015f\u00e7a"], correctAnswer: 'Hesap', difficulty: 2 },
            ],
          },
        ],
      },
    ],
  },
  pl: {
    themes: [
      {
        id: 'basic',
        name: '波兰语基础词汇',
        color: '#DC2626',
        levels: [
          {
            levelId: 'pl-basic-01',
            title: '问候与礼貌',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: [],
            questions: [
              { id: 'pl-b-01-1', type: 'translate', question: '你好', options: ["cze\u015b\u0107", "dzi\u0119kuj\u0119", "przepraszam", "dzie\u0144 dobry"], correctAnswer: 'cześć', difficulty: 1 },
              { id: 'pl-b-01-2', type: 'translate', question: '谢谢', options: ["dzi\u0119kuj\u0119", "cze\u015b\u0107", "przepraszam", "dzie\u0144 dobry"], correctAnswer: 'dziękuję', difficulty: 1 },
              { id: 'pl-b-01-3', type: 'fill-blank', question: '___ dobry!（早上好）', options: ["Dzie\u0144", "Dobranoc", "Cze\u015b\u0107", "Do widzenia"], correctAnswer: 'Dzień', difficulty: 2 },
              { id: 'pl-b-01-4', type: 'match', question: '波兰语配对', pairs: [["cze\u015b\u0107", "\u4f60\u597d"], ["dzi\u0119kuj\u0119", "\u8c22\u8c22"], ["przepraszam", "\u5bf9\u4e0d\u8d77"], ["dzie\u0144 dobry", "\u65e9\u4e0a\u597d"]], correctAnswer: 'match', difficulty: 2 },
              { id: 'pl-b-01-5', type: 'translate', question: '晚安', options: ["dobranoc", "cze\u015b\u0107", "dzi\u0119kuj\u0119", "przepraszam"], correctAnswer: 'dobranoc', difficulty: 2 },
              { id: 'pl-b-01-6', type: 'dictation', question: '听写：水', audioWord: 'woda', correctAnswer: 'woda', difficulty: 2 },
            ],
          },
          {
            levelId: 'pl-basic-02',
            title: '数字与颜色',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: ['pl-basic-01'],
            questions: [
              { id: 'pl-b-02-1', type: 'translate', question: '红色', options: ["czerwony", "niebieski", "zielony", "\u017c\u00f3\u0142ty"], correctAnswer: 'czerwony', difficulty: 1 },
              { id: 'pl-b-02-2', type: 'translate', question: '三', options: ["trzy", "jeden", "dwa", "cztery"], correctAnswer: 'trzy', difficulty: 1 },
              { id: 'pl-b-02-3', type: 'fill-blank', question: 'To jest ___（这是红色的）', options: ["czerwony", "niebieski", "zielony", "\u017c\u00f3\u0142ty"], correctAnswer: 'czerwony', difficulty: 1 },
              { id: 'pl-b-02-4', type: 'match', question: '数字配对', pairs: [["jeden", "\u4e00"], ["dwa", "\u4e8c"], ["trzy", "\u4e09"], ["cztery", "\u56db"]], correctAnswer: 'match', difficulty: 2 },
              { id: 'pl-b-02-5', type: 'translate', question: '绿色', options: ["zielony", "czerwony", "niebieski", "\u017c\u00f3\u0142ty"], correctAnswer: 'zielony', difficulty: 1 },
              { id: 'pl-b-02-6', type: 'dictation', question: '听写：米饭', audioWord: 'ryż', correctAnswer: 'ryż', difficulty: 2 },
            ],
          },
        ],
      },
      {
        id: 'daily',
        name: '日常对话',
        color: '#EF4444',
        levels: [
          {
            levelId: 'pl-daily-01',
            title: '出行与问路',
            timeLimit: 150,
            minScoreFor1Star: 40,
            minScoreFor2Star: 60,
            minScoreFor3Star: 80,
            prerequisites: [],
            questions: [
              { id: 'pl-d-01-1', type: 'translate', question: '洗手间在哪里？', options: ["gdzie jest toaleta", "ile to kosztuje", "zgubi\u0142em si\u0119", "potrzebuj\u0119 lekarza"], correctAnswer: 'gdzie jest toaleta', difficulty: 2 },
              { id: 'pl-d-01-2', type: 'translate', question: '这个多少钱？', options: ["ile to kosztuje", "gdzie jest toaleta", "zgubi\u0142em si\u0119", "potrzebuj\u0119 lekarza"], correctAnswer: 'ile to kosztuje', difficulty: 2 },
              { id: 'pl-d-01-3', type: 'translate', question: '我迷路了？', options: ["zgubi\u0142em si\u0119", "gdzie jest toaleta", "ile to kosztuje", "potrzebuj\u0119 lekarza"], correctAnswer: 'zgubiłem się', difficulty: 2 },
              { id: 'pl-d-01-4', type: 'translate', question: '我需要医生？', options: ["potrzebuj\u0119 lekarza", "gdzie jest toaleta", "ile to kosztuje", "zgubi\u0142em si\u0119"], correctAnswer: 'potrzebuję lekarza', difficulty: 2 },
              { id: 'pl-d-01-5', type: 'match', question: '出行配对', pairs: [["poci\u0105g", "\u706b\u8f66"], ["szpital", "\u533b\u9662"], ["szko\u0142a", "\u5b66\u6821"], ["samolot", "\u98de\u673a"]], correctAnswer: 'match', difficulty: 2 },
              { id: 'pl-d-01-6', type: 'fill-blank', question: '___ rachunek（请结账）', options: ["Prosz\u0119", "Dzi\u0119kuj\u0119", "Cze\u015b\u0107", "Do widzenia"], correctAnswer: 'Proszę', difficulty: 2 },
            ],
          },
        ],
      },
    ],
  },
  nl: {
    themes: [
      {
        id: 'basic',
        name: '荷兰语基础词汇',
        color: '#F59E0B',
        levels: [
          {
            levelId: 'nl-basic-01',
            title: '问候与礼貌',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: [],
            questions: [
              { id: 'nl-b-01-1', type: 'translate', question: '你好', options: ["hallo", "bedankt", "sorry", "goedemorgen"], correctAnswer: 'hallo', difficulty: 1 },
              { id: 'nl-b-01-2', type: 'translate', question: '谢谢', options: ["bedankt", "hallo", "sorry", "goedemorgen"], correctAnswer: 'bedankt', difficulty: 1 },
              { id: 'nl-b-01-3', type: 'fill-blank', question: '___ morgen!（早上好）', options: ["Goede", "Welterusten", "Hallo", "Tot ziens"], correctAnswer: 'Goede', difficulty: 2 },
              { id: 'nl-b-01-4', type: 'match', question: '荷兰语配对', pairs: [["hallo", "\u4f60\u597d"], ["bedankt", "\u8c22\u8c22"], ["sorry", "\u5bf9\u4e0d\u8d77"], ["goedemorgen", "\u65e9\u4e0a\u597d"]], correctAnswer: 'match', difficulty: 2 },
              { id: 'nl-b-01-5', type: 'translate', question: '晚安', options: ["welterusten", "hallo", "bedankt", "sorry"], correctAnswer: 'welterusten', difficulty: 2 },
              { id: 'nl-b-01-6', type: 'dictation', question: '听写：水', audioWord: 'water', correctAnswer: 'water', difficulty: 2 },
            ],
          },
          {
            levelId: 'nl-basic-02',
            title: '数字与颜色',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: ['nl-basic-01'],
            questions: [
              { id: 'nl-b-02-1', type: 'translate', question: '红色', options: ["rood", "blauw", "groen", "geel"], correctAnswer: 'rood', difficulty: 1 },
              { id: 'nl-b-02-2', type: 'translate', question: '三', options: ["drie", "een", "twee", "vier"], correctAnswer: 'drie', difficulty: 1 },
              { id: 'nl-b-02-3', type: 'fill-blank', question: 'Dit is ___（这是红色的）', options: ["rood", "blauw", "groen", "geel"], correctAnswer: 'rood', difficulty: 1 },
              { id: 'nl-b-02-4', type: 'match', question: '数字配对', pairs: [["een", "\u4e00"], ["twee", "\u4e8c"], ["drie", "\u4e09"], ["vier", "\u56db"]], correctAnswer: 'match', difficulty: 2 },
              { id: 'nl-b-02-5', type: 'translate', question: '绿色', options: ["groen", "rood", "blauw", "geel"], correctAnswer: 'groen', difficulty: 1 },
              { id: 'nl-b-02-6', type: 'dictation', question: '听写：米饭', audioWord: 'rijst', correctAnswer: 'rijst', difficulty: 2 },
            ],
          },
        ],
      },
      {
        id: 'daily',
        name: '日常对话',
        color: '#FBBF24',
        levels: [
          {
            levelId: 'nl-daily-01',
            title: '出行与问路',
            timeLimit: 150,
            minScoreFor1Star: 40,
            minScoreFor2Star: 60,
            minScoreFor3Star: 80,
            prerequisites: [],
            questions: [
              { id: 'nl-d-01-1', type: 'translate', question: '洗手间在哪里？', options: ["waar is het toilet", "hoeveel kost dit", "ik ben verdwaald", "ik heb een dokter nodig"], correctAnswer: 'waar is het toilet', difficulty: 2 },
              { id: 'nl-d-01-2', type: 'translate', question: '这个多少钱？', options: ["hoeveel kost dit", "waar is het toilet", "ik ben verdwaald", "ik heb een dokter nodig"], correctAnswer: 'hoeveel kost dit', difficulty: 2 },
              { id: 'nl-d-01-3', type: 'translate', question: '我迷路了？', options: ["ik ben verdwaald", "waar is het toilet", "hoeveel kost dit", "ik heb een dokter nodig"], correctAnswer: 'ik ben verdwaald', difficulty: 2 },
              { id: 'nl-d-01-4', type: 'translate', question: '我需要医生？', options: ["ik heb een dokter nodig", "waar is het toilet", "hoeveel kost dit", "ik ben verdwaald"], correctAnswer: 'ik heb een dokter nodig', difficulty: 2 },
              { id: 'nl-d-01-5', type: 'match', question: '出行配对', pairs: [["trein", "\u706b\u8f66"], ["ziekenhuis", "\u533b\u9662"], ["school", "\u5b66\u6821"], ["vliegtuig", "\u98de\u673a"]], correctAnswer: 'match', difficulty: 2 },
              { id: 'nl-d-01-6', type: 'fill-blank', question: '___ ik de rekening（请结账）', options: ["Mag", "Bedankt", "Hallo", "Tot ziens"], correctAnswer: 'Mag', difficulty: 2 },
            ],
          },
        ],
      },
    ],
  },
  el: {
    themes: [
      {
        id: 'basic',
        name: '希腊语基础词汇',
        color: '#0891B2',
        levels: [
          {
            levelId: 'el-basic-01',
            title: '问候与礼貌',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: [],
            questions: [
              { id: 'el-b-01-1', type: 'translate', question: '你好', options: ["\u03b3\u03b5\u03b9\u03ac \u03c3\u03bf\u03c5", "\u03b5\u03c5\u03c7\u03b1\u03c1\u03b9\u03c3\u03c4\u03ce", "\u03c3\u03c5\u03b3\u03b3\u03bd\u03ce\u03bc\u03b7", "\u03ba\u03b1\u03bb\u03b7\u03bc\u03ad\u03c1\u03b1"], correctAnswer: 'γειά σου', difficulty: 1 },
              { id: 'el-b-01-2', type: 'translate', question: '谢谢', options: ["\u03b5\u03c5\u03c7\u03b1\u03c1\u03b9\u03c3\u03c4\u03ce", "\u03b3\u03b5\u03b9\u03ac \u03c3\u03bf\u03c5", "\u03c3\u03c5\u03b3\u03b3\u03bd\u03ce\u03bc\u03b7", "\u03ba\u03b1\u03bb\u03b7\u03bc\u03ad\u03c1\u03b1"], correctAnswer: 'ευχαριστώ', difficulty: 1 },
              { id: 'el-b-01-3', type: 'fill-blank', question: '___ μέρα!（早上好）', options: ["\u039a\u03b1\u03bb\u03b7", "\u0395\u03c5\u03c7\u03b1\u03c1\u03b9\u03c3\u03c4\u03ce", "\u0393\u03b5\u03b9\u03ac", "\u0391\u03bd\u03c4\u03af\u03bf"], correctAnswer: 'Καλη', difficulty: 2 },
              { id: 'el-b-01-4', type: 'match', question: '希腊语配对', pairs: [["\u03b3\u03b5\u03b9\u03ac \u03c3\u03bf\u03c5", "\u4f60\u597d"], ["\u03b5\u03c5\u03c7\u03b1\u03c1\u03b9\u03c3\u03c4\u03ce", "\u8c22\u8c22"], ["\u03c3\u03c5\u03b3\u03b3\u03bd\u03ce\u03bc\u03b7", "\u5bf9\u4e0d\u8d77"], ["\u03ba\u03b1\u03bb\u03b7\u03bc\u03ad\u03c1\u03b1", "\u65e9\u4e0a\u597d"]], correctAnswer: 'match', difficulty: 2 },
              { id: 'el-b-01-5', type: 'translate', question: '晚安', options: ["\u03ba\u03b1\u03bb\u03b7\u03bd\u03cd\u03c7\u03c4\u03b1", "\u03b3\u03b5\u03b9\u03ac \u03c3\u03bf\u03c5", "\u03b5\u03c5\u03c7\u03b1\u03c1\u03b9\u03c3\u03c4\u03ce", "\u03c3\u03c5\u03b3\u03b3\u03bd\u03ce\u03bc\u03b7"], correctAnswer: 'καληνύχτα', difficulty: 2 },
              { id: 'el-b-01-6', type: 'dictation', question: '听写：水', audioWord: 'νερό', correctAnswer: 'νερό', difficulty: 2 },
            ],
          },
          {
            levelId: 'el-basic-02',
            title: '数字与颜色',
            timeLimit: 120,
            minScoreFor1Star: 30,
            minScoreFor2Star: 50,
            minScoreFor3Star: 70,
            prerequisites: ['el-basic-01'],
            questions: [
              { id: 'el-b-02-1', type: 'translate', question: '红色', options: ["\u03ba\u03cc\u03ba\u03ba\u03b9\u03bd\u03bf", "\u03bc\u03c0\u03bb\u03b5", "\u03c0\u03c1\u03ac\u03c3\u03b9\u03bd\u03bf", "\u03ba\u03af\u03c4\u03c1\u03b9\u03bd\u03bf"], correctAnswer: 'κόκκινο', difficulty: 1 },
              { id: 'el-b-02-2', type: 'translate', question: '三', options: ["\u03c4\u03c1\u03af\u03b1", "\u03ad\u03bd\u03b1", "\u03b4\u03cd\u03bf", "\u03c4\u03ad\u03c3\u03c3\u03b5\u03c1\u03b1"], correctAnswer: 'τρία', difficulty: 1 },
              { id: 'el-b-02-3', type: 'fill-blank', question: 'Αυτό είναι ___（这是红色的）', options: ["\u03ba\u03cc\u03ba\u03ba\u03b9\u03bd\u03bf", "\u03bc\u03c0\u03bb\u03b5", "\u03c0\u03c1\u03ac\u03c3\u03b9\u03bd\u03bf", "\u03ba\u03af\u03c4\u03c1\u03b9\u03bd\u03bf"], correctAnswer: 'κόκκινο', difficulty: 1 },
              { id: 'el-b-02-4', type: 'match', question: '数字配对', pairs: [["\u03ad\u03bd\u03b1", "\u4e00"], ["\u03b4\u03cd\u03bf", "\u4e8c"], ["\u03c4\u03c1\u03af\u03b1", "\u4e09"], ["\u03c4\u03ad\u03c3\u03c3\u03b5\u03c1\u03b1", "\u56db"]], correctAnswer: 'match', difficulty: 2 },
              { id: 'el-b-02-5', type: 'translate', question: '绿色', options: ["\u03c0\u03c1\u03ac\u03c3\u03b9\u03bd\u03bf", "\u03ba\u03cc\u03ba\u03ba\u03b9\u03bd\u03bf", "\u03bc\u03c0\u03bb\u03b5", "\u03ba\u03af\u03c4\u03c1\u03b9\u03bd\u03bf"], correctAnswer: 'πράσινο', difficulty: 1 },
              { id: 'el-b-02-6', type: 'dictation', question: '听写：米饭', audioWord: 'ρύζι', correctAnswer: 'ρύζι', difficulty: 2 },
            ],
          },
        ],
      },
      {
        id: 'daily',
        name: '日常对话',
        color: '#06B6D4',
        levels: [
          {
            levelId: 'el-daily-01',
            title: '出行与问路',
            timeLimit: 150,
            minScoreFor1Star: 40,
            minScoreFor2Star: 60,
            minScoreFor3Star: 80,
            prerequisites: [],
            questions: [
              { id: 'el-d-01-1', type: 'translate', question: '洗手间在哪里？', options: ["\u03c0\u03bf\u03cd \u03b5\u03af\u03bd\u03b1\u03b9 \u03b7 \u03c4\u03bf\u03c5\u03b1\u03bb\u03ad\u03c4\u03b1", "\u03c0\u03cc\u03c3\u03bf \u03ba\u03bf\u03c3\u03c4\u03af\u03b6\u03b5\u03b9 \u03b1\u03c5\u03c4\u03cc", "\u03c7\u03ac\u03b8\u03b7\u03ba\u03b1", "\u03c7\u03c1\u03b5\u03b9\u03ac\u03b6\u03bf\u03bc\u03b1\u03b9 \u03b3\u03b9\u03b1\u03c4\u03c1\u03cc"], correctAnswer: 'πού είναι η τουαλέτα', difficulty: 2 },
              { id: 'el-d-01-2', type: 'translate', question: '这个多少钱？', options: ["\u03c0\u03cc\u03c3\u03bf \u03ba\u03bf\u03c3\u03c4\u03af\u03b6\u03b5\u03b9 \u03b1\u03c5\u03c4\u03cc", "\u03c0\u03bf\u03cd \u03b5\u03af\u03bd\u03b1\u03b9 \u03b7 \u03c4\u03bf\u03c5\u03b1\u03bb\u03ad\u03c4\u03b1", "\u03c7\u03ac\u03b8\u03b7\u03ba\u03b1", "\u03c7\u03c1\u03b5\u03b9\u03ac\u03b6\u03bf\u03bc\u03b1\u03b9 \u03b3\u03b9\u03b1\u03c4\u03c1\u03cc"], correctAnswer: 'πόσο κοστίζει αυτό', difficulty: 2 },
              { id: 'el-d-01-3', type: 'translate', question: '我迷路了？', options: ["\u03c7\u03ac\u03b8\u03b7\u03ba\u03b1", "\u03c0\u03bf\u03cd \u03b5\u03af\u03bd\u03b1\u03b9 \u03b7 \u03c4\u03bf\u03c5\u03b1\u03bb\u03ad\u03c4\u03b1", "\u03c0\u03cc\u03c3\u03bf \u03ba\u03bf\u03c3\u03c4\u03af\u03b6\u03b5\u03b9 \u03b1\u03c5\u03c4\u03cc", "\u03c7\u03c1\u03b5\u03b9\u03ac\u03b6\u03bf\u03bc\u03b1\u03b9 \u03b3\u03b9\u03b1\u03c4\u03c1\u03cc"], correctAnswer: 'χάθηκα', difficulty: 2 },
              { id: 'el-d-01-4', type: 'translate', question: '我需要医生？', options: ["\u03c7\u03c1\u03b5\u03b9\u03ac\u03b6\u03bf\u03bc\u03b1\u03b9 \u03b3\u03b9\u03b1\u03c4\u03c1\u03cc", "\u03c0\u03bf\u03cd \u03b5\u03af\u03bd\u03b1\u03b9 \u03b7 \u03c4\u03bf\u03c5\u03b1\u03bb\u03ad\u03c4\u03b1", "\u03c0\u03cc\u03c3\u03bf \u03ba\u03bf\u03c3\u03c4\u03af\u03b6\u03b5\u03b9 \u03b1\u03c5\u03c4\u03cc", "\u03c7\u03ac\u03b8\u03b7\u03ba\u03b1"], correctAnswer: 'χρειάζομαι γιατρό', difficulty: 2 },
              { id: 'el-d-01-5', type: 'match', question: '出行配对', pairs: [["\u03c4\u03c1\u03ad\u03bd\u03bf", "\u706b\u8f66"], ["\u03bd\u03bf\u03c3\u03bf\u03ba\u03bf\u03bc\u03b5\u03af\u03bf", "\u533b\u9662"], ["\u03c3\u03c7\u03bf\u03bb\u03b5\u03af\u03bf", "\u5b66\u6821"], ["\u03b1\u03b5\u03c1\u03bf\u03c0\u03bb\u03ac\u03bd\u03bf", "\u98de\u673a"]], correctAnswer: 'match', difficulty: 2 },
              { id: 'el-d-01-6', type: 'fill-blank', question: 'Το ___ παρακαλώ（请结账）', options: ["\u03bb\u03bf\u03b3\u03b1\u03c1\u03b9\u03b1\u03c3\u03bc\u03cc", "\u03b5\u03c5\u03c7\u03b1\u03c1\u03b9\u03c3\u03c4\u03ce", "\u03b3\u03b5\u03b9\u03ac", "\u03b1\u03bd\u03c4\u03af\u03bf"], correctAnswer: 'λογαριασμό', difficulty: 2 },
            ],
          },
        ],
      },
    ],
  },
  sh: {
    themes: [
        {
          id: 'basic',
          name: '基础词汇',
          color: '#DC2626',
          levels: [
            {
              levelId: 'sh-basic-01',
              title: '问候与礼貌',
              timeLimit: 120,
              minScoreFor1Star: 30,
              minScoreFor2Star: 50,
              minScoreFor3Star: 70,
              prerequisites: [],
              questions: [
                {id: 'sh-b-01-1', type: 'translate', question: '你好', options: ['侬好', '谢谢', '再见', '对不起'], correctAnswer: '侬好', difficulty: 1},
                {id: 'sh-b-01-2', type: 'translate', question: '谢谢', options: ['谢谢/多谢', '对不起', '你好', '再见'], correctAnswer: '谢谢/多谢', difficulty: 1},
                {id: 'sh-b-01-3', type: 'fill-blank', question: '___早！（早上好！）', options: ['侬', '阿拉', '伊', '伊拉'], correctAnswer: '侬', difficulty: 2},
                {id: 'sh-b-01-4', type: 'match', question: '上海话问候配对', pairs: [['侬好', '你好'], ['谢谢', '谢谢'], ['对勿住', '对不起'], ['明朝见', '明天见']], correctAnswer: 'match', difficulty: 2},
                {id: 'sh-b-01-5', type: 'translate', question: '再见', options: ['明朝见', '侬好', '谢谢', '对勿住'], correctAnswer: '明朝见', difficulty: 1},
                {id: 'sh-b-01-6', type: 'dictation', question: '听写：朋友', correctAnswer: '朋友', difficulty: 2, audioWord: '朋友'}
              ],
            },
            {
              levelId: 'sh-basic-02',
              title: '代词与称呼',
              timeLimit: 120,
              minScoreFor1Star: 30,
              minScoreFor2Star: 50,
              minScoreFor3Star: 70,
              prerequisites: ['sh-basic-01'],
              questions: [
                {id: 'sh-b-02-1', type: 'translate', question: '我', options: ['阿拉', '侬', '伊', '伊拉'], correctAnswer: '阿拉', difficulty: 1},
                {id: 'sh-b-02-2', type: 'translate', question: '你', options: ['侬', '阿拉', '伊', '伊拉'], correctAnswer: '侬', difficulty: 1},
                {id: 'sh-b-02-3', type: 'fill-blank', question: '___是啥人？（他是谁？）', options: ['伊', '阿拉', '侬', '伊拉'], correctAnswer: '伊', difficulty: 2},
                {id: 'sh-b-02-4', type: 'match', question: '代词配对', pairs: [['阿拉', '我/我们'], ['侬', '你'], ['伊', '他/她'], ['伊拉', '他们']], correctAnswer: 'match', difficulty: 2},
                {id: 'sh-b-02-5', type: 'translate', question: '我们', options: ['阿拉', '侬', '伊', '伊拉'], correctAnswer: '阿拉', difficulty: 1},
                {id: 'sh-b-02-6', type: 'translate', question: '他们', options: ['伊拉', '阿拉', '侬', '伊'], correctAnswer: '伊拉', difficulty: 1}
              ],
            },
            {
              levelId: 'sh-basic-03',
              title: '数字与时间',
              timeLimit: 120,
              minScoreFor1Star: 35,
              minScoreFor2Star: 55,
              minScoreFor3Star: 75,
              prerequisites: ['sh-basic-02'],
              questions: [
                {id: 'sh-b-03-1', type: 'translate', question: '一', options: ['一', '两', '三', '四'], correctAnswer: '一', difficulty: 1},
                {id: 'sh-b-03-2', type: 'translate', question: '今天', options: ['今朝', '明朝', '昨日', '后日'], correctAnswer: '今朝', difficulty: 1},
                {id: 'sh-b-03-3', type: 'fill-blank', question: '明朝___（明天）', options: ['明朝', '今朝', '昨日', '后日'], correctAnswer: '明朝', difficulty: 2},
                {id: 'sh-b-03-4', type: 'match', question: '时间配对', pairs: [['今朝', '今天'], ['明朝', '明天'], ['昨日', '昨天'], ['后日', '后天']], correctAnswer: 'match', difficulty: 2},
                {id: 'sh-b-03-5', type: 'translate', question: '昨天', options: ['昨日', '今朝', '明朝', '后日'], correctAnswer: '昨日', difficulty: 1},
                {id: 'sh-b-03-6', type: 'dictation', question: '听写：吃饭', correctAnswer: '吃饭', difficulty: 2, audioWord: '吃饭'}
              ],
            }
          ],
        },
        {
          id: 'daily',
          name: '日常对话',
          color: '#7C3AED',
          levels: [
            {
              levelId: 'sh-daily-01',
              title: '饮食与生活',
              timeLimit: 150,
              minScoreFor1Star: 40,
              minScoreFor2Star: 60,
              minScoreFor3Star: 80,
              prerequisites: [],
              questions: [
                {id: 'sh-d-01-1', type: 'translate', question: '吃饭', options: ['吃饭', '吃酒', '吃茶', '吃水'], correctAnswer: '吃饭', difficulty: 1},
                {id: 'sh-d-01-2', type: 'translate', question: '喝水', options: ['吃水', '吃饭', '吃茶', '吃酒'], correctAnswer: '吃水', difficulty: 1},
                {id: 'sh-d-01-3', type: 'fill-blank', question: '饭___了（吃好了）', options: ['吃过', '吃饭', '吃水', '吃茶'], correctAnswer: '吃过', difficulty: 2},
                {id: 'sh-d-01-4', type: 'match', question: '饮食配对', pairs: [['吃饭', '吃饭'], ['吃水', '喝水'], ['吃茶', '喝茶'], ['吃酒', '喝酒']], correctAnswer: 'match', difficulty: 2},
                {id: 'sh-d-01-5', type: 'translate', question: '多少钱', options: ['几钿', '几岁', '几人', '几点'], correctAnswer: '几钿', difficulty: 2},
                {id: 'sh-d-01-6', type: 'repeat', question: '跟读：侬饭吃过𠲎？', correctAnswer: 'repeat', difficulty: 2, sentence: '侬饭吃过𠲎？'}
              ],
            },
            {
              levelId: 'sh-daily-02',
              title: '出行与问路',
              timeLimit: 150,
              minScoreFor1Star: 40,
              minScoreFor2Star: 60,
              minScoreFor3Star: 80,
              prerequisites: ['sh-daily-01'],
              questions: [
                {id: 'sh-d-02-1', type: 'translate', question: '去哪里', options: ['到啥地方去', '做啥事体', '为啥', '几时'], correctAnswer: '到啥地方去', difficulty: 2},
                {id: 'sh-d-02-2', type: 'fill-blank', question: '地铁站___（在哪里）', options: ['阿里', '啥人', '几钿', '几岁'], correctAnswer: '阿里', difficulty: 2},
                {id: 'sh-d-02-3', type: 'translate', question: '地铁站在哪里', options: ['地铁站在阿里', '地铁站几钿', '地铁站几岁', '地铁站啥人'], correctAnswer: '地铁站在阿里', difficulty: 2},
                {id: 'sh-d-02-4', type: 'match', question: '出行配对', pairs: [['地铁', '地铁'], ['公交', '公交'], ['出租车', '出租车'], ['飞机', '飞机']], correctAnswer: 'match', difficulty: 2},
                {id: 'sh-d-02-5', type: 'listen-pic', question: '听词选图：地铁', options: ['🚇', '🚌', '🚕', '✈️'], correctAnswer: '地铁', difficulty: 2},
                {id: 'sh-d-02-6', type: 'translate', question: '上海', options: ['上海', '北京', '广州', '香港'], correctAnswer: '上海', difficulty: 1}
              ],
            },
            {
              levelId: 'sh-daily-03',
              title: '情感与表达',
              timeLimit: 150,
              minScoreFor1Star: 40,
              minScoreFor2Star: 60,
              minScoreFor3Star: 80,
              prerequisites: ['sh-daily-02'],
              questions: [
                {id: 'sh-d-03-1', type: 'translate', question: '很漂亮', options: ['交关漂亮', '老丑', '老高', '老矮'], correctAnswer: '交关漂亮', difficulty: 2},
                {id: 'sh-d-03-2', type: 'translate', question: '很开心', options: ['邪气开心', '勿开心', '难过', '生气'], correctAnswer: '邪气开心', difficulty: 2},
                {id: 'sh-d-03-3', type: 'fill-blank', question: '___赞！（很棒！）', options: ['老', '勿', '邪气', '交关'], correctAnswer: '老', difficulty: 2},
                {id: 'sh-d-03-4', type: 'match', question: '程度副词配对', pairs: [['邪气', '很'], ['老', '很'], ['交关', '非常'], ['一眼眼', '一点点']], correctAnswer: 'match', difficulty: 3},
                {id: 'sh-d-03-5', type: 'translate', question: '谢谢侬', options: ['谢谢侬', '对勿住', '侬好', '明朝见'], correctAnswer: '谢谢侬', difficulty: 1},
                {id: 'sh-d-03-6', type: 'repeat', question: '跟读：阿拉上海见！', correctAnswer: 'repeat', difficulty: 2, sentence: '阿拉上海见！'}
              ],
            }
          ],
        },
        {
          id: 'scenes',
          name: '场景实战',
          color: '#0EA5E9',
          levels: [
            {
              levelId: 'sh-scenes-01',
              title: '购物消费',
              timeLimit: 150,
              minScoreFor1Star: 40,
              minScoreFor2Star: 60,
              minScoreFor3Star: 80,
              prerequisites: [],
              questions: [
                {id: 'sh-s-01-1', type: 'translate', question: '便宜点', options: ['便宜眼', '贵点', '买单', '找零'], correctAnswer: '便宜眼', difficulty: 2},
                {id: 'sh-s-01-2', type: 'translate', question: '多少钱', options: ['几钿', '几岁', '几人', '几点'], correctAnswer: '几钿', difficulty: 1},
                {id: 'sh-s-01-3', type: 'fill-blank', question: '我要___个（买这个）', options: ['迭', '伊', '侬', '阿拉'], correctAnswer: '迭', difficulty: 2},
                {id: 'sh-s-01-4', type: 'match', question: '购物配对', pairs: [['便宜眼', '便宜点'], ['几钿', '多少钱'], ['买单', '结账'], ['找零', '找零钱']], correctAnswer: 'match', difficulty: 2},
                {id: 'sh-s-01-5', type: 'translate', question: '太贵了', options: ['太贵了', '便宜', '好', '不好'], correctAnswer: '太贵了', difficulty: 1},
                {id: 'sh-s-01-6', type: 'translate', question: '我喜欢', options: ['我喜欢', '我勿喜欢', '我晓得了', '我勿晓得'], correctAnswer: '我喜欢', difficulty: 1}
              ],
            },
            {
              levelId: 'sh-scenes-02',
              title: '工作与学习',
              timeLimit: 150,
              minScoreFor1Star: 40,
              minScoreFor2Star: 60,
              minScoreFor3Star: 80,
              prerequisites: ['sh-scenes-01'],
              questions: [
                {id: 'sh-s-02-1', type: 'translate', question: '工作', options: ['做生活', '读书', '吃饭', '睏觉'], correctAnswer: '做生活', difficulty: 2},
                {id: 'sh-s-02-2', type: 'translate', question: '公司', options: ['公司', '学堂', '屋里', '店里'], correctAnswer: '公司', difficulty: 1},
                {id: 'sh-s-02-3', type: 'fill-blank', question: '我去___班（上班）', options: ['上', '下', '读', '吃'], correctAnswer: '上', difficulty: 2},
                {id: 'sh-s-02-4', type: 'match', question: '工作配对', pairs: [['做生活', '工作'], ['上班', '上班'], ['下班', '下班'], ['加班', '加班']], correctAnswer: 'match', difficulty: 2},
                {id: 'sh-s-02-5', type: 'translate', question: '老师', options: ['老师', '学生', '医生', '护士'], correctAnswer: '老师', difficulty: 1},
                {id: 'sh-s-02-6', type: 'repeat', question: '跟读：阿拉一道去上班。', correctAnswer: 'repeat', difficulty: 2, sentence: '阿拉一道去上班。'}
              ],
            },
            {
              levelId: 'sh-scenes-03',
              title: '沪语特色表达',
              timeLimit: 180,
              minScoreFor1Star: 40,
              minScoreFor2Star: 60,
              minScoreFor3Star: 80,
              prerequisites: ['sh-scenes-02'],
              questions: [
                {id: 'sh-s-03-1', type: 'translate', question: '上海', options: ['上海', '北京', '广州', '深圳'], correctAnswer: '上海', difficulty: 1},
                {id: 'sh-s-03-2', type: 'translate', question: '弄堂', options: ['弄堂', '马路', '地铁', '公交'], correctAnswer: '弄堂', difficulty: 2},
                {id: 'sh-s-03-3', type: 'translate', question: '老克勒', options: ['老克勒', '小朋友', '老师', '医生'], correctAnswer: '老克勒', difficulty: 3},
                {id: 'sh-s-03-4', type: 'match', question: '沪语特色词', pairs: [['弄堂', '小巷'], ['老克勒', '老绅士'], ['小囡', '小孩'], ['戆度', '傻瓜']], correctAnswer: 'match', difficulty: 3},
                {id: 'sh-s-03-5', type: 'translate', question: '小孩', options: ['小囡', '老人家', '老师', '学生'], correctAnswer: '小囡', difficulty: 2},
                {id: 'sh-s-03-6', type: 'repeat', question: '跟读：阿拉上海人，侬好！', correctAnswer: 'repeat', difficulty: 2, sentence: '阿拉上海人，侬好！'}
              ],
            }
          ],
        }
    ],
  },
  hak: {
    themes: [
        {
          id: 'basic',
          name: '基础词汇',
          color: '#16A34A',
          levels: [
            {
              levelId: 'hak-basic-01',
              title: '问候与礼貌',
              timeLimit: 120,
              minScoreFor1Star: 30,
              minScoreFor2Star: 50,
              minScoreFor3Star: 70,
              prerequisites: [],
              questions: [
                {id: 'hak-b-01-1', type: 'translate', question: '你好', options: ['你好', '多谢', '细伢仔', '𠊎'], correctAnswer: '你好', difficulty: 1},
                {id: 'hak-b-01-2', type: 'translate', question: '谢谢', options: ['多谢', '你好', '对唔住', '𠊎'], correctAnswer: '多谢', difficulty: 1},
                {id: 'hak-b-01-3', type: 'fill-blank', question: '___係麼个？（这是什么？）', options: ['𠊎', '你', '佢', '佢兜'], correctAnswer: '𠊎', difficulty: 2},
                {id: 'hak-b-01-4', type: 'match', question: '客家话问候配对', pairs: [['你好', '你好'], ['多谢', '谢谢'], ['对唔住', '对不起'], ['𠊎係客家人', '我是客家人']], correctAnswer: 'match', difficulty: 2},
                {id: 'hak-b-01-5', type: 'translate', question: '对不起', options: ['对唔住', '多谢', '你好', '𠊎'], correctAnswer: '对唔住', difficulty: 1},
                {id: 'hak-b-01-6', type: 'dictation', question: '听写：朋友', correctAnswer: '朋友', difficulty: 2, audioWord: '朋友'}
              ],
            },
            {
              levelId: 'hak-basic-02',
              title: '代词与家庭',
              timeLimit: 120,
              minScoreFor1Star: 30,
              minScoreFor2Star: 50,
              minScoreFor3Star: 70,
              prerequisites: ['hak-basic-01'],
              questions: [
                {id: 'hak-b-02-1', type: 'translate', question: '我', options: ['𠊎', '你', '佢', '佢兜'], correctAnswer: '𠊎', difficulty: 1},
                {id: 'hak-b-02-2', type: 'translate', question: '你', options: ['你', '𠊎', '佢', '佢兜'], correctAnswer: '你', difficulty: 1},
                {id: 'hak-b-02-3', type: 'fill-blank', question: '___係客家人（我是客家人）', options: ['𠊎', '你', '佢', '佢兜'], correctAnswer: '𠊎', difficulty: 2},
                {id: 'hak-b-02-4', type: 'match', question: '代词配对', pairs: [['𠊎', '我'], ['你', '你'], ['佢', '他'], ['𠊎兜', '我们']], correctAnswer: 'match', difficulty: 2},
                {id: 'hak-b-02-5', type: 'translate', question: '我们', options: ['𠊎兜', '佢兜', '你', '佢'], correctAnswer: '𠊎兜', difficulty: 1},
                {id: 'hak-b-02-6', type: 'translate', question: '他们', options: ['佢兜', '𠊎兜', '你', '佢'], correctAnswer: '佢兜', difficulty: 1}
              ],
            },
            {
              levelId: 'hak-basic-03',
              title: '数字与时间',
              timeLimit: 120,
              minScoreFor1Star: 35,
              minScoreFor2Star: 55,
              minScoreFor3Star: 75,
              prerequisites: ['hak-basic-02'],
              questions: [
                {id: 'hak-b-03-1', type: 'translate', question: '一', options: ['一', '二', '三', '四'], correctAnswer: '一', difficulty: 1},
                {id: 'hak-b-03-2', type: 'translate', question: '今天', options: ['今晡日', '天光日', '昨日', '前日'], correctAnswer: '今晡日', difficulty: 1},
                {id: 'hak-b-03-3', type: 'fill-blank', question: '天光日___去（明天去）', options: ['天光日', '今晡日', '昨日', '前日'], correctAnswer: '天光日', difficulty: 2},
                {id: 'hak-b-03-4', type: 'match', question: '时间配对', pairs: [['今晡日', '今天'], ['天光日', '明天'], ['昨日', '昨天'], ['前日', '前天']], correctAnswer: 'match', difficulty: 2},
                {id: 'hak-b-03-5', type: 'translate', question: '昨天', options: ['昨日', '今晡日', '天光日', '前日'], correctAnswer: '昨日', difficulty: 1},
                {id: 'hak-b-03-6', type: 'dictation', question: '听写：吃饭', correctAnswer: '食饭', difficulty: 2, audioWord: '食饭'}
              ],
            }
          ],
        },
        {
          id: 'daily',
          name: '日常对话',
          color: '#EA580C',
          levels: [
            {
              levelId: 'hak-daily-01',
              title: '饮食与生活',
              timeLimit: 150,
              minScoreFor1Star: 40,
              minScoreFor2Star: 60,
              minScoreFor3Star: 80,
              prerequisites: [],
              questions: [
                {id: 'hak-d-01-1', type: 'translate', question: '吃饭', options: ['食饭', '食水', '食茶', '食酒'], correctAnswer: '食饭', difficulty: 1},
                {id: 'hak-d-01-2', type: 'translate', question: '喝水', options: ['食水', '食饭', '食茶', '食酒'], correctAnswer: '食水', difficulty: 1},
                {id: 'hak-d-01-3', type: 'fill-blank', question: '食___吂？（吃饭了吗？）', options: ['饭', '水', '茶', '酒'], correctAnswer: '饭', difficulty: 2},
                {id: 'hak-d-01-4', type: 'match', question: '饮食配对', pairs: [['食饭', '吃饭'], ['食水', '喝水'], ['食茶', '喝茶'], ['食酒', '喝酒']], correctAnswer: 'match', difficulty: 2},
                {id: 'hak-d-01-5', type: 'translate', question: '多少钱', options: ['几多钱', '几多岁', '几只', '几时'], correctAnswer: '几多钱', difficulty: 2},
                {id: 'hak-d-01-6', type: 'repeat', question: '跟读：𠊎去食饭。', correctAnswer: 'repeat', difficulty: 2, sentence: '𠊎去食饭。'}
              ],
            },
            {
              levelId: 'hak-daily-02',
              title: '出行与问路',
              timeLimit: 150,
              minScoreFor1Star: 40,
              minScoreFor2Star: 60,
              minScoreFor3Star: 80,
              prerequisites: ['hak-daily-01'],
              questions: [
                {id: 'hak-d-02-1', type: 'translate', question: '去哪里', options: ['去哪位', '做麼个', '为麼个', '几时'], correctAnswer: '去哪位', difficulty: 2},
                {id: 'hak-d-02-2', type: 'fill-blank', question: '地铁站___？（地铁站在哪里？）', options: ['在哪位', '做麼个', '为麼个', '几多钱'], correctAnswer: '在哪位', difficulty: 2},
                {id: 'hak-d-02-3', type: 'translate', question: '梅州', options: ['梅州', '广州', '深圳', '香港'], correctAnswer: '梅州', difficulty: 1},
                {id: 'hak-d-02-4', type: 'match', question: '出行配对', pairs: [['地铁', '地铁'], ['公交', '公交'], ['出租车', '的士'], ['飞机', '飞机']], correctAnswer: 'match', difficulty: 2},
                {id: 'hak-d-02-5', type: 'listen-pic', question: '听词选图：的士', options: ['🚇', '🚌', '🚕', '✈️'], correctAnswer: '的士', difficulty: 2},
                {id: 'hak-d-02-6', type: 'translate', question: '走路', options: ['行路', '食饭', '食水', '睡觉'], correctAnswer: '行路', difficulty: 1}
              ],
            },
            {
              levelId: 'hak-daily-03',
              title: '情感与表达',
              timeLimit: 150,
              minScoreFor1Star: 40,
              minScoreFor2Star: 60,
              minScoreFor3Star: 80,
              prerequisites: ['hak-daily-02'],
              questions: [
                {id: 'hak-d-03-1', type: 'translate', question: '很漂亮', options: ['当靓', '当丑', '当高', '当矮'], correctAnswer: '当靓', difficulty: 2},
                {id: 'hak-d-03-2', type: 'translate', question: '很开心', options: ['当开心', '毋开心', '愁', '发恼'], correctAnswer: '当开心', difficulty: 2},
                {id: 'hak-d-03-3', type: 'fill-blank', question: '___好！（很好！）', options: ['当', '毋', '唔', '𠮟'], correctAnswer: '当', difficulty: 2},
                {id: 'hak-d-03-4', type: 'match', question: '程度副词配对', pairs: [['当', '很'], ['十分', '非常'], ['一滴子', '一点点'], ['几多', '多少']], correctAnswer: 'match', difficulty: 3},
                {id: 'hak-d-03-5', type: 'translate', question: '我爱你', options: ['𠊎爱你', '𠊎多谢你', '𠊎对唔住', '𠊎想你'], correctAnswer: '𠊎爱你', difficulty: 1},
                {id: 'hak-d-03-6', type: 'repeat', question: '跟读：𠊎係客家人！', correctAnswer: 'repeat', difficulty: 2, sentence: '𠊎係客家人！'}
              ],
            }
          ],
        },
        {
          id: 'scenes',
          name: '场景实战',
          color: '#9333EA',
          levels: [
            {
              levelId: 'hak-scenes-01',
              title: '购物消费',
              timeLimit: 150,
              minScoreFor1Star: 40,
              minScoreFor2Star: 60,
              minScoreFor3Star: 80,
              prerequisites: [],
              questions: [
                {id: 'hak-s-01-1', type: 'translate', question: '便宜点', options: ['便宜滴子', '贵点', '买单', '找钱'], correctAnswer: '便宜滴子', difficulty: 2},
                {id: 'hak-s-01-2', type: 'translate', question: '多少钱', options: ['几多钱', '几多岁', '几只', '几时'], correctAnswer: '几多钱', difficulty: 1},
                {id: 'hak-s-01-3', type: 'fill-blank', question: '𠊎爱___个（我要这个）', options: ['𠊢', '你', '佢', '𠊎'], correctAnswer: '𠊢', difficulty: 2},
                {id: 'hak-s-01-4', type: 'match', question: '购物配对', pairs: [['便宜滴子', '便宜点'], ['几多钱', '多少钱'], ['买单', '结账'], ['找钱', '找零钱']], correctAnswer: 'match', difficulty: 2},
                {id: 'hak-s-01-5', type: 'translate', question: '太贵了', options: ['太贵了', '便宜', '好', '唔好'], correctAnswer: '太贵了', difficulty: 1},
                {id: 'hak-s-01-6', type: 'translate', question: '我喜欢', options: ['𠊎欢喜', '𠊎毋欢喜', '𠊎知', '𠊎唔知'], correctAnswer: '𠊎欢喜', difficulty: 1}
              ],
            },
            {
              levelId: 'hak-scenes-02',
              title: '客家文化',
              timeLimit: 150,
              minScoreFor1Star: 40,
              minScoreFor2Star: 60,
              minScoreFor3Star: 80,
              prerequisites: ['hak-scenes-01'],
              questions: [
                {id: 'hak-s-02-1', type: 'translate', question: '客家话', options: ['客家话', '普通话', '广东话', '上海话'], correctAnswer: '客家话', difficulty: 1},
                {id: 'hak-s-02-2', type: 'translate', question: '客家人', options: ['客家人', '广东人', '上海人', '北京人'], correctAnswer: '客家人', difficulty: 1},
                {id: 'hak-s-02-3', type: 'fill-blank', question: '___是客家文化中心（梅州）', options: ['梅州', '广州', '深圳', '北京'], correctAnswer: '梅州', difficulty: 2},
                {id: 'hak-s-02-4', type: 'match', question: '客家配对', pairs: [['客家话', '客家话'], ['客家人', '客家人'], ['围龙屋', '客家围屋'], ['擂茶', '客家擂茶']], correctAnswer: 'match', difficulty: 3},
                {id: 'hak-s-02-5', type: 'translate', question: '围屋', options: ['围龙屋', '学校', '公司', '商店'], correctAnswer: '围龙屋', difficulty: 2},
                {id: 'hak-s-02-6', type: 'repeat', question: '跟读：𠊎係客家人。', correctAnswer: 'repeat', difficulty: 2, sentence: '𠊎係客家人。'}
              ],
            },
            {
              levelId: 'hak-scenes-03',
              title: '客家特色表达',
              timeLimit: 180,
              minScoreFor1Star: 40,
              minScoreFor2Star: 60,
              minScoreFor3Star: 80,
              prerequisites: ['hak-scenes-02'],
              questions: [
                {id: 'hak-s-03-1', type: 'translate', question: '男孩', options: ['细赖仔', '细妹仔', '老人家', '老师'], correctAnswer: '细赖仔', difficulty: 2},
                {id: 'hak-s-03-2', type: 'translate', question: '女孩', options: ['细妹仔', '细赖仔', '老人家', '老师'], correctAnswer: '细妹仔', difficulty: 2},
                {id: 'hak-s-03-3', type: 'translate', question: '爷爷', options: ['阿公', '阿婆', '爷哀', '爸爸'], correctAnswer: '阿公', difficulty: 2},
                {id: 'hak-s-03-4', type: 'match', question: '亲属称谓', pairs: [['阿公', '爷爷'], ['阿婆', '奶奶'], ['爷哀', '父母'], ['阿爸', '爸爸']], correctAnswer: 'match', difficulty: 3},
                {id: 'hak-s-03-5', type: 'translate', question: '奶奶', options: ['阿婆', '阿公', '爷哀', '阿爸'], correctAnswer: '阿婆', difficulty: 2},
                {id: 'hak-s-03-6', type: 'repeat', question: '跟读：𠊎去梅州看阿公阿婆。', correctAnswer: 'repeat', difficulty: 2, sentence: '𠊎去梅州看阿公阿婆。'}
              ],
            }
          ],
        }
    ],
  },
};
Object.assign(window, { NEW_QUIZ_DATA });
